import React, { useState } from "react";
import { DEMO_TRUTH } from "../../../../../packages/contracts/src/index";
import { useWorkbench } from "../store";
import { Icon, MetricRail, TruthMark } from "./PresentationSystem";

const backtestTabs = ["Review", "Run Matrix", "Holdings", "Orders / Fills", "Attribution"] as const;

function TruthStatus() {
  return <span data-truth-classification={DEMO_TRUTH.wave3} title={DEMO_TRUTH.wave3}><TruthMark detail="非正式金融输出"/></span>;
}

export function BacktestPanel() {
  const [tab, setTab] = useState<typeof backtestTabs[number]>("Review");
  const [scenarioOpen, setScenarioOpen] = useState(false);
  const [queue, setQueue] = useState("paused");
  const [queueNotice, setQueueNotice] = useState("Demo 队列已暂停");
  const focusContext = useWorkbench((state) => state.focusContext);
  const updateQueue = (next: string) => { setQueue(next); setQueueNotice(`Demo 队列状态 · ${next.toUpperCase()}`); };
  return <section className="panel-page backtest-workspace" data-testid="backtest-surface" data-primary-panel="backtest-review" data-major-panel>
    <header className="analysis-header"><div className="analysis-title"><small>BACKTEST EXPERIMENT / BT-DEMO-021</small><h1>Risk parity · 执行复盘</h1><p><TruthStatus/><span>available 2026-06-30 18:45 CST</span></p></div><div className="experiment-trail"><span><small>HANDOFF</small>demo-v8</span><Icon name="chevron" size={13}/><span><small>SCENARIO</small>Monthly · 2023—2026</span><Icon name="chevron" size={13}/><span><small>QUEUE</small><b className={queue === "running" ? "ok" : "warn"}>{queue.toUpperCase()}</b></span></div><div className="analysis-actions"><button data-action="backtest-scenario" aria-pressed={scenarioOpen} onClick={() => setScenarioOpen(!scenarioOpen)}>场景设置</button><button className={queue === "running" ? "" : "primary"} onClick={() => updateQueue("running")} disabled={queue === "running"}><Icon name="pulse" size={14}/>{queue === "running" ? "运行中" : "运行 Demo"}</button></div></header>
    <div className="analysis-contextline"><span>Benchmark 沪深300 · Demo</span><span>Costs 8 bps</span><span>Industry neutral ±5%</span><span className="action-receipt" role="status" aria-live="polite">{queueNotice}</span></div>
    <div className="mini-tabs" role="tablist" aria-label="回测分析视图">{backtestTabs.map((item) => <button role="tab" aria-selected={tab === item} data-backtest-tab={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)} key={item}>{item}</button>)}</div>
    <div className="backtest-primary primary-canvas" data-primary-canvas>{tab === "Review" ? <BacktestReview queue={queue} setQueue={updateQueue} onRun={() => focusContext({ kind: "backtest", eyebrow: "BACKTEST RUN", title: "BT-DEMO-021 · Risk parity", summary: "运行选择已映射到权益、回撤、成交与约束证据。", facts: [{ label: "Return", value: "+26.84%" }, { label: "Drawdown", value: "-8.31%" }, { label: "Turnover", value: "38.4%" }], provenance: "Backtest deterministic Demo provider", trace: "backtest.run.selected → execution.review.updated → inspector.explained" })} /> : tab === "Run Matrix" ? <RunMatrix queue={queue} onRun={(id) => focusContext({ kind: "backtest", eyebrow: "RUN MATRIX", title: id, summary: "批量运行已关联场景、状态与约束检查。", facts: [{ label: "Queue", value: queue }, { label: "Scenario", value: "Risk parity" }], provenance: "Backtest deterministic Demo provider", trace: "run.matrix.selected → scenario.context.updated → inspector.explained" })} /> : <ExecutionTable tab={tab} />}</div>
    {scenarioOpen && <div className="context-drawer scenario-drawer" role="region" aria-label="回测场景设置" data-major-panel><div className="drawer-head"><div><small>SCENARIO / EXPERIMENT</small><b>回测场景设置</b></div><button onClick={() => setScenarioOpen(false)} aria-label="关闭场景设置">×</button></div><div className="scenario-form"><label>开始<input type="date" defaultValue="2023-01-01"/></label><label>结束<input type="date" defaultValue="2026-06-30"/></label><label>调仓<select><option>Monthly</option><option>Weekly</option></select></label><label>组合构建<select><option>Risk parity</option><option>Equal weight</option></select></label><label>最大单股权重<input type="number" defaultValue="4"/></label><label>交易成本 (bps)<input type="number" defaultValue="8"/></label><label>约束<select><option>行业中性 ±5%</option><option>无行业约束</option></select></label><div className="dimension-line"><b>批量维度</b><span>2 Universe</span><span>3 Rebalance</span><span>2 Cost</span><span>12 Runs</span></div><button className="primary" onClick={() => { setQueueNotice("场景参数已应用到前端 Demo 会话"); setScenarioOpen(false); }}>应用场景</button></div></div>}
  </section>;
}

function BacktestReview({ queue, setQueue, onRun }: { queue: string; setQueue: (next: string) => void; onRun: () => void }) {
  return <div className="review-layout"><div className="performance-canvas"><MetricRail items={[{ label: "Demo Return", value: "+26.84%", tone: "positive" }, { label: "Drawdown", value: "-8.31%", tone: "negative" }, { label: "Sharpe", value: "1.42" }, { label: "Turnover", value: "38.4%" }]}/><PerformanceChart /></div><aside className="run-evidence"><div className="section-head"><div><small>EXECUTION CONTEXT</small><h2>BT-DEMO-021</h2></div><button onClick={onRun}><Icon name="inspector" size={14}/>证据</button></div><dl><dt>Strategy</dt><dd>StrategyDraft/demo-v8</dd><dt>Signal</dt><dd>PredictionSignalVersion/demo-alpha-v3</dd><dt>Orders / fills</dt><dd>1,284 / 1,279</dd><dt>Constraint</dt><dd><span className="warn">Turnover 38.4%</span></dd></dl><div className="constraint-list"><span className="ok">✓ Gross exposure</span><span className="ok">✓ Industry deviation</span><span className="warn">! Turnover threshold</span></div><div className="queue-actions">{queue === "running" ? <button onClick={() => setQueue("paused")}>Ⅱ Pause</button> : <button onClick={() => setQueue("running")}>↻ Resume</button>}<button onClick={() => setQueue("cancelled")} className="danger" disabled={queue === "cancelled"}>× Cancel</button></div></aside></div>;
}

function RunMatrix({ queue, onRun }: { queue: string; onRun: (id: string) => void }) {
  return <div className="run-matrix"><div className="section-head"><div><small>RUN MATRIX / QUEUE</small><h2>12 Demo Runs</h2></div><span className={`state ${queue}`}>{queue.toUpperCase()}</span></div>{["BT-DEMO-021", "BT-DEMO-022", "BT-DEMO-023", "BT-DEMO-024", "BT-DEMO-025"].map((id, index) => <button className="matrix-row" key={id} onClick={() => onRun(id)}><b>{id}</b><span>{index === 0 ? "Risk parity" : "Equal weight"}</span><span>Monthly</span><progress max="100" value={queue === "running" ? 32 + index * 12 : index === 0 ? 100 : 58 - index * 7}/><small>{queue === "running" ? "RUNNING" : index === 0 ? "COMPLETE" : "PAUSED"}</small></button>)}</div>;
}

function PerformanceChart({ detailed = false }: { detailed?: boolean }) {
  return <div className={`performance-chart ${detailed ? "detailed" : ""}`} aria-label="权益、基准与回撤图"><svg viewBox="0 0 900 320" preserveAspectRatio="none"><defs><linearGradient id="equity-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4FC3F7" stopOpacity=".2"/><stop offset="1" stopColor="#4FC3F7" stopOpacity="0"/></linearGradient></defs><g className="grid-lines"><path d="M0 55 H900 M0 110 H900 M0 165 H900 M0 220 H900"/></g><path className="area" d="M0 238 C80 220 115 235 170 188 S260 172 310 158 S400 175 455 122 S560 140 620 95 S720 112 780 68 S850 88 900 42 L900 252 L0 252Z"/><path className="equity-line" d="M0 238 C80 220 115 235 170 188 S260 172 310 158 S400 175 455 122 S560 140 620 95 S720 112 780 68 S850 88 900 42"/><path className="benchmark-line" d="M0 242 C120 225 180 214 260 196 S420 186 500 160 S650 148 720 116 S840 104 900 82"/><path className="drawdown-line" d="M0 282 C110 286 155 266 230 288 S360 270 420 296 S550 262 660 286 S790 266 900 290"/></svg><div className="axis-years"><span>2023</span><span>2024</span><span>2025</span><span>2026</span></div></div>;
}

function ExecutionTable({ tab }: { tab: string }) {
  const [selectedRow, setSelectedRow] = useState<string | null>(null);
  const rows = tab.includes("Holding") || tab.includes("Position") ? [["600519.SH", "贵州茅台", "3.8%", "+1.28%", "Momentum"], ["300750.SZ", "宁德时代", "3.6%", "+2.43%", "Quality"], ["601318.SH", "中国平安", "3.4%", "+0.74%", "Value"]] : tab.includes("Order") ? [["ORD-1021", "600519.SH", "BUY 120", "FILLED", "09:31:02"], ["ORD-1022", "300750.SZ", "SELL 80", "PARTIAL", "10:04:18"], ["TRD-8821", "601318.SH", "BUY 300", "FILLED", "10:41:37"]] : [["Industry deviation", "3.1%", "≤5%", "PASS", "constraint"], ["Single weight", "3.8%", "≤4%", "PASS", "constraint"], ["Turnover", "38.4%", "≤35%", "WARN", "execution"]];
  return <div className="execution-table"><div className="section-head"><div><small>SECONDARY EVIDENCE</small><h2>{tab}</h2></div><span className="action-receipt" role="status" aria-live="polite">{selectedRow ? `${selectedRow} 已选中` : "选择一行查看上下文"}</span><TruthStatus/></div><div className="table-head"><span>IDENTITY</span><span>CONTEXT</span><span>VALUE</span><span>STATE</span><span>SOURCE</span></div>{rows.map((row) => <button key={row[0]} className={selectedRow === row[0] ? "selected" : ""} aria-pressed={selectedRow === row[0]} onClick={() => setSelectedRow(row[0])}>{row.map((cell) => <span key={cell}>{cell}</span>)}</button>)}</div>;
}
