import React, { useState } from "react";
import { DEMO_TRUTH } from "../../../../../packages/contracts/src/index";

const TruthBanner = () => <div className="wave3-banner"><b>{DEMO_TRUTH.label}</b><span>{DEMO_TRUTH.wave3}</span><small>未声明 Wave 3 acceptance · 不构成正式金融结果</small></div>;

export function BacktestPanel() {
  const [tab, setTab] = useState("实验维度"); const [queue, setQueue] = useState("paused"); const tabs = ["实验维度", "组合与风险", "约束与成本", "Run Matrix"];
  return <section className="panel-page recovered-page" data-testid="backtest-surface"><TruthBanner/><div className="recovered-head"><div><small>BACKTEST LAB · RECOVERED PRODUCT DESIGN</small><h1>批量实验与执行队列</h1></div><button>载入 BacktestHandoffDraft</button><button className="primary" onClick={() => setQueue("running")}>▶ 加入 Demo 队列</button></div><div className="mini-tabs">{tabs.map((x) => <button className={tab===x?"active":""} onClick={() => setTab(x)} key={x}>{x}</button>)}</div><div className="backtest-grid"><div className="config-card"><h3>{tab}</h3><div className="form-grid"><label>时间范围<input type="date" defaultValue="2023-01-01"/></label><label>结束<input type="date" defaultValue="2026-06-30"/></label><label>调仓<select><option>Monthly</option><option>Weekly</option></select></label><label>基准<select><option>沪深300 · Demo</option><option>中证500 · Demo</option></select></label><label>组合构建<select><option>Risk parity</option><option>Equal weight</option></select></label><label>最大单股权重<input type="number" defaultValue="4"/></label><label>交易成本 (bps)<input type="number" defaultValue="8"/></label><label>约束<select><option>行业中性 ±5%</option><option>无行业约束</option></select></label></div><div className="dimension-chips"><b>批量维度预览</b><span>2 Universe</span><span>3 Rebalance</span><span>2 Cost</span><span>12 Runs</span></div></div><div className="queue-card"><div className="section-head"><div><small>RUN MATRIX / QUEUE</small><h2>12 Demo Runs</h2></div><span className={`state ${queue}`}>{queue.toUpperCase()}</span></div>{["BT-DEMO-021","BT-DEMO-022","BT-DEMO-023","BT-DEMO-024"].map((id,i)=><div className="queue-row" key={id}><b>{id}</b><span>{i===0?"Risk parity":"Equal weight"}</span><progress max="100" value={queue==="running"?32+i*18:i===0?100:58-i*9}/><small>{queue==="running"?"RUNNING":i===0?"COMPLETE":"PAUSED"}</small></div>)}<div className="queue-actions"><button onClick={() => setQueue("paused")}>Ⅱ Pause</button><button onClick={() => setQueue("cancelled")} className="danger">× Cancel</button><button onClick={() => setQueue("running")}>↻ Resume</button></div><div className="constraint-status"><b>Risk / Constraint checks</b><span className="ok">✓ Gross exposure</span><span className="ok">✓ Industry deviation</span><span className="warn">! Turnover 38.4%</span></div></div></div></section>;
}

export function ResultPanel() {
  const [tab, setTab] = useState("权益 / 回撤"); const tabs=["权益 / 回撤","滚动指标","持仓","订单 / 成交","风险 / 约束","比较 / Lineage"];
  return <section className="panel-page recovered-page result-page" data-testid="result-surface"><TruthBanner/><div className="recovered-head"><div><small>RESULT LAB · RECOVERED PRODUCT DESIGN</small><h1>结果、归因与可追溯比较</h1></div><select><option>BT-DEMO-021 · Risk parity</option><option>BT-DEMO-022 · Equal weight</option></select><button>＋ 加入比较</button></div><div className="mini-tabs">{tabs.map((x)=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="result-grid"><div className="result-main"><div className="metric-strip"><Metric k="Demo Return" v="+26.84%"/><Metric k="Demo Drawdown" v="-8.31%"/><Metric k="Demo Sharpe" v="1.42"/><Metric k="Demo Turnover" v="38.4%"/></div>{tab==="权益 / 回撤"||tab==="滚动指标"?<div className="equity-chart"><svg viewBox="0 0 900 260" preserveAspectRatio="none"><defs><linearGradient id="eq" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#36d9d0" stopOpacity=".25"/><stop offset="1" stopColor="#36d9d0" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 220 C80 205 115 225 170 178 S260 162 310 148 S400 165 455 112 S560 130 620 85 S720 102 780 58 S850 78 900 32 L900 260 L0 260Z"/><path className="line" d="M0 220 C80 205 115 225 170 178 S260 162 310 148 S400 165 455 112 S560 130 620 85 S720 102 780 58 S850 78 900 32"/><path className="drawdown" d="M0 238 C110 240 155 226 230 242 S360 230 420 247 S550 220 660 240 S790 225 900 242"/></svg><div><span>2023</span><span>2024</span><span>2025</span><span>2026</span></div></div>:<ResultTable tab={tab}/>}</div><aside className="lineage-card"><span className="truth-chip">DEMO PROVENANCE</span><h3>Result Lineage</h3><ol><li>UniverseVersion/demo-v12</li><li>StrategyDraft/demo-v8</li><li>ModelVersion/demo-lgbm-v4</li><li>PredictionSignalVersion/demo-alpha-v3</li><li>BacktestHandoffDraft/demo-v8</li><li>BT-DEMO-021</li></ol><button>比较 3 个 ResultVersion</button><button>查看 Provenance Manifest</button><div className="audit-box"><b>Truth classification</b><p>{DEMO_TRUTH.wave3}</p></div></aside></div></section>;
}

function ResultTable({tab}:{tab:string}) { const rows = tab.includes("持仓") ? [["600519.SH","3.8%","+1.28%","Momentum"],["300750.SZ","3.6%","+2.43%","Quality"],["601318.SH","3.4%","+0.74%","Value"]] : tab.includes("订单") ? [["ORD-1021","600519.SH","BUY 120","FILLED"],["ORD-1022","300750.SZ","SELL 80","PARTIAL"],["TRD-8821","601318.SH","BUY 300","FILLED"]] : [["Industry deviation","3.1%","≤5%","PASS"],["Single weight","3.8%","≤4%","PASS"],["Turnover","38.4%","≤35%","WARN"]]; return <div className="result-table"><div className="section-head"><h2>{tab}</h2><span className="truth-chip">DEMO</span></div>{rows.map((r)=><div key={r[0]}>{r.map((x)=><span key={x}>{x}</span>)}</div>)}</div> }
function Metric({ k, v }: { k:string; v:string }) { return <div><small>{k}</small><b>{v}</b></div>; }
