import React, { useState } from "react";
import { modelFamilies, runs } from "../demo";
import { useWorkbench } from "../store";
import { commandRegistry } from "../commandRegistry";

export function ModelRunsPanel() {
  const model = useWorkbench((s) => s.model); const family = useWorkbench((s) => s.setModelFamily); const toggle = useWorkbench((s) => s.toggleRun); const [split, setSplit] = useState(model.splitPlan);
  return <section className="panel-page model-page"><div className="model-config"><label>DatasetVersion<select defaultValue={model.datasetVersion}><option>{model.datasetVersion}</option><option>DatasetVersion/demo-cn-factor-v11</option></select></label><label>Label<select defaultValue={model.label}><option>{model.label}</option><option>next_5d_rank_return</option></select></label><label>SplitPlan<select value={split} onChange={(e) => setSplit(e.target.value as typeof split)}><option value="chronological">Chronological train / validation / test</option><option value="rolling">Rolling</option><option value="expanding">Expanding</option><option value="purge-embargo">Purge / Embargo</option><option value="walk-forward">Walk-forward</option></select></label><span className="truth-chip">DEMO DATASET</span></div><div className="leakage"><b>Leakage Audit</b><span className="ok">✓ 时序边界通过</span><span className="ok">✓ 标签延迟 20D</span><span>purge 5D · embargo 2D</span><button>查看审计证据</button></div><div className="model-body"><div className="family-rail"><h3>七个一等模型族</h3>{modelFamilies.map((x, i) => <button data-model-family={x} className={model.family === x ? "active" : ""} onClick={() => family(x)} key={x}><i>0{i + 1}</i><span><b>{x}</b><small>完整 Demo journey</small></span></button>)}</div><div className="run-table"><div className="section-head"><div><small>MLFLOW-STYLE RUNS</small><h2>Runs · Detail · Compare</h2></div><b>{model.selectedRunIds.length} selected</b></div><div className="grid-head run"><span></span><span>RUN</span><span>FAMILY</span><span>RANK IC</span><span>STATUS</span><span>DURATION</span></div>{runs.map((run) => <button className={`run-row ${model.selectedRunIds.includes(run.id) ? "selected" : ""}`} onClick={() => toggle(run.id)} key={run.id}><span>{model.selectedRunIds.includes(run.id) ? "☑" : "☐"}</span><b>{run.id}</b><span>{run.family}</span><span>{run.score}</span><span className={run.state === "BEST" ? "ok" : ""}>{run.state}</span><span>{run.duration}</span></button>)}<div className="run-detail"><b>Selected-run detail</b><span>Params: leaves=31 · lr=0.028 · depth=8</span><span>Artifacts: metrics.json · feature-importance</span><button>多 Run 对比</button></div></div></div></section>;
}

export function ModelStudyPanel() {
  const model = useWorkbench((s) => s.model); const setState = useWorkbench((s) => s.setModelState); const [view, setView] = useState("Trial History"); const [receipt, setReceipt] = useState("ready");
  const act = async (name: "study.resume"|"study.pause"|"study.cancel"|"study.checkpoint", next: typeof model.studyState) => { const id = `${name}-checkpoint-${model.checkpoint}`; const r = await commandRegistry.execute(name, id); setReceipt(`${r.id} · ${r.duplicate ? "DUPLICATE SUPPRESSED" : "EXECUTED ONCE"} · count=${r.executionCount}`); if (!r.duplicate) setState(next); };
  const views = ["Trial History", "Importance", "Relationships", "Parallel Coordinates", "Pareto"];
  return <section className="panel-page study-page" data-testid="model-study"><div className="study-head"><div><small>OPTUNA-STYLE STUDY / TRIAL / HPO</small><h2>Study S-014 · {model.family}</h2></div><span className={`state ${model.studyState}`}>{model.studyState.toUpperCase()}</span><span>checkpoint #{model.checkpoint}</span><button onClick={() => void act("study.resume", "running")}>▶ Resume</button><button onClick={() => void act("study.pause", "paused")}>Ⅱ Pause</button><button onClick={() => void act("study.checkpoint", "checkpointed")}>◆ Checkpoint</button><button className="danger" onClick={() => void act("study.cancel", "cancelled")}>× Cancel</button></div><div className="mini-tabs">{views.map((x) => <button className={x === view ? "active" : ""} onClick={() => setView(x)} key={x}>{x}</button>)}</div><div className="study-viz"><div className="trial-chart">{Array.from({length:24}, (_,i) => <i key={i} className={i > 17 ? "pending" : ""} style={{height: `${22 + ((i * 19) % 88)}%`}} title={`Trial ${i+1}`}/>)}</div><div><span className="truth-chip">DEMO HPO</span><h3>{view}</h3><p>24 Trials · 18 complete · 2 pruned · 1 checkpoint · 3 queued</p><dl><dt>Best Trial</dt><dd>T-018 / Rank IC 0.084</dd><dt>Primary importance</dt><dd>learning_rate · num_leaves</dd><dt>Pareto axes</dt><dd>Rank IC ↑ / latency ↓</dd></dl></div></div><div className="command-receipt"><b>CommandRegistry exactly-once</b><code>{receipt}</code></div></section>;
}

export function ModelVersionPanel() {
  const model = useWorkbench((s) => s.model); const [tab, setTab] = useState("ModelVersion");
  return <section className="panel-page version-page"><div className="mini-tabs"><button className={tab === "ModelVersion" ? "active" : ""} onClick={() => setTab("ModelVersion")}>Immutable ModelVersion</button><button className={tab === "Signal" ? "active" : ""} onClick={() => setTab("Signal")}>PredictionSignalVersion</button></div>{tab === "ModelVersion" ? <div className="version-card"><span className="lock">◆ IMMUTABLE</span><h2>{model.modelVersion}</h2><p>content-sha256: demo:8b32…7c91</p><div className="metric-strip"><Metric k="Rank IC" v="0.084"/><Metric k="Coverage" v="96.8%"/><Metric k="Leakage" v="PASS"/></div><dl><dt>Family</dt><dd>{model.family}</dd><dt>Dataset</dt><dd>{model.datasetVersion}</dd><dt>SplitPlan</dt><dd>{model.splitPlan}</dd></dl></div> : <div className="version-card signal"><span className="truth-chip">DEMO SIGNAL</span><h2>{model.predictionSignalVersion}</h2><p>由不可变 ModelVersion 派生的版本化信号交接。</p><div className="quality-grid"><span><b>0.91</b>完整性</span><span><b>0.87</b>稳定性</span><span><b>0.04</b>漂移</span><span><b>96.8%</b>覆盖</span></div><button className="primary">交接到 BacktestHandoffDraft</button></div>}</section>;
}
function Metric({ k, v }: { k: string; v: string }) { return <div><small>{k}</small><b>{v}</b></div>; }
