from enum import Enum


class ErrorCode(str, Enum):
    ARTIFACT_NOT_PUBLISHED = 'ARTIFACT_NOT_PUBLISHED'
    CAPABILITY_UNAVAILABLE = 'CAPABILITY_UNAVAILABLE'
    CONFLICT = 'CONFLICT'
    IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT'
    INFEASIBLE = 'INFEASIBLE'
    INTERNAL_ERROR = 'INTERNAL_ERROR'
    INVALID_ARGUMENT = 'INVALID_ARGUMENT'
    LEDGER_UNRECONCILED = 'LEDGER_UNRECONCILED'
    NOT_FOUND = 'NOT_FOUND'
    PIT_UNPROVABLE = 'PIT_UNPROVABLE'
    RESIDUAL_VALIDATION_FAILED = 'RESIDUAL_VALIDATION_FAILED'
    RESOURCE_REJECTED = 'RESOURCE_REJECTED'
    SESSION_PROJECT_BINDING_CONFLICT = 'SESSION_PROJECT_BINDING_CONFLICT'
    SOLVER_FAILED = 'SOLVER_FAILED'
    TRUTH_PRECONDITION_FAILED = 'TRUTH_PRECONDITION_FAILED'
    UNBOUNDED = 'UNBOUNDED'
    VERSION_MISMATCH = 'VERSION_MISMATCH'

FROZEN_ERROR_CODES = ('ARTIFACT_NOT_PUBLISHED',
 'CAPABILITY_UNAVAILABLE',
 'CONFLICT',
 'IDEMPOTENCY_CONFLICT',
 'INFEASIBLE',
 'INTERNAL_ERROR',
 'INVALID_ARGUMENT',
 'LEDGER_UNRECONCILED',
 'NOT_FOUND',
 'PIT_UNPROVABLE',
 'RESIDUAL_VALIDATION_FAILED',
 'RESOURCE_REJECTED',
 'SESSION_PROJECT_BINDING_CONFLICT',
 'SOLVER_FAILED',
 'TRUTH_PRECONDITION_FAILED',
 'UNBOUNDED',
 'VERSION_MISMATCH')


class CatalogStartupErrorCode(str, Enum):
    """Stable failures emitted before an ASL operation can be accepted."""

    CATALOG_MIGRATION_PREFIX_UNRECOGNIZED = 'CATALOG_MIGRATION_PREFIX_UNRECOGNIZED'
    CATALOG_UPGRADE_INTEGRITY_FAILED = 'CATALOG_UPGRADE_INTEGRITY_FAILED'
