import React, { useEffect, useRef, useState } from "react";
import type { JobEvent, JobSpec, JsonObject, ResearchConversation, ResearchObjectRef, StrategyConfig } from "../../../../../packages/contracts/src/research";
import { request, useResearch } from "./state";
import { useWorkspace, flushDrafts, changedSettings } from "./workspace";
import { Field, requestText } from "./ui";
import { object } from "./configuration";
interface Message { role: "user" | "assistant"; content: string; experimentRefs?: ResearchObjectRef[]; experimentIds?: string[]; }
interface Proposal { title: string; description: string; spec: JobSpec; }
interface Answer { message: string; phase: string; proposals: Proposal[]; experimentIds: string[]; }
interface Settings { ai: { baseUrl: string; model: string; apiKey: string; temperature: number }; defaultDataSource: string; }
export function ConversationPanel({settingsOpen,closeSettings}:{settingsOpen:boolean;closeSettings:()=>void}) {
 const s=useResearch(); const w=useWorkspace(); const [list,setList]=useState<ResearchConversation[]>([]);const [conversation,setConversation]=useState<ResearchConversation|null>(null);const current=useRef(conversation);current.current=conversation;
 const [search,setSearch]=useState("");const [input,setInput]=useState("");const [busy,setBusy]=useState(false);const [settings,setSettings]=useState<Settings|null>(null);const [showSettings,setShowSettings]=useState(false);const [serviceStatus,setServiceStatus]=useState("正在读取服务设置");
 const configurationStatus = (value: Settings) => !value.ai.baseUrl?.trim() || !value.ai.model?.trim() ? "未配置服务" : !/localhost|127\.0\.0\.1|\[::1\]/.test(value.ai.baseUrl) && !value.ai.apiKey?.trim() ? "未配置 API 密钥" : "已配置 · 尚未验证";
 const state=object(conversation?.state);const messages=Array.isArray(state.messages)?state.messages as unknown as Message[]:[];const proposals=Array.isArray(state.proposals)?state.proposals as unknown as Proposal[]:[];const mode=String(state.mode??"assist");const stageIds=Array.isArray(state.stageJobIds)?state.stageJobIds.filter((x):x is string=>typeof x==="string"):[];const terminal=stageIds.length>0&&stageIds.every(id=>s.jobs.some(j=>j.id===id&&["completed","failed","interrupted","cancelled"].includes(j.status)));
 const referenceName = (ref: ResearchObjectRef) => ref.title || (ref.experimentId ? s.experiments.find(e => e.id === ref.experimentId && e.projectId === ref.projectId)?.name : undefined) || (ref.strategyId ? w.strategies.find(st => st.id === ref.strategyId && st.projectId === ref.projectId)?.name : undefined) || ref.symbol || ({ today: "今日工作台", strategy: "策略研究", factors: "因子研究", model: "模型训练", experiment: "实验结果", compare: "实验比较", market: "市场概况", screener: "筛选与自选", stock: "个股全景", selection: "每日选股", positions: "实际持仓", data: "数据中心", universe: "股票池" }[ref.kind]);
 async function refreshList(){const items=await request<ResearchConversation[]>("ai.conversations.list");setList(items);return items;}
 async function select(id:string){if(busy)return;const next=await request<ResearchConversation>("ai.conversations.get",{conversationId:id});setConversation(next);setInput("");await w.savePreferences({activeConversationId:id});}
 useEffect(()=>{void s.act(async()=>{const config=await request<Settings>("settings.get");setSettings(config);setServiceStatus(configurationStatus(config));const items=await refreshList();const selected=items.find(c=>c.id===w.preferences.activeConversationId)??items[0];if(selected)setConversation(await request("ai.conversations.get",{conversationId:selected.id}));});},[]);
 useEffect(()=>{if(settingsOpen)setShowSettings(true);},[settingsOpen]);useEffect(()=>{if(showSettings)void s.act(async()=>setSettings(await request("settings.get")));},[showSettings]);
 async function save(patch:Partial<ResearchConversation>){if(!current.current)return;const next=await request<ResearchConversation>("ai.conversations.save",{conversation:{id:current.current.id,...patch}});setConversation(next);current.current=next;await refreshList();}
 async function create(){const name=await requestText("研究会话名称","新研究");if(!name?.trim())return;const next=await request<ResearchConversation>("ai.conversations.create",{name:name.trim(),context:[]});setConversation(next);await refreshList();await w.savePreferences({activeConversationId:next.id});}
 async function send(text=input){if(!conversation||busy||!text.trim())return;const id=conversation.id;setBusy(true);setServiceStatus("正在请求服务…");setInput("");await s.act(async()=>{try{await request<Answer>("ai.chat",{conversationId:id,mode,message:text,history:messages});setServiceStatus(`最近请求成功 · ${new Date().toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}`);}catch(error){setServiceStatus("最近请求失败");throw error;}finally{const next=await request<ResearchConversation>("ai.conversations.get",{conversationId:id});if(current.current?.id===id)setConversation(next);await refreshList();}});setBusy(false);}
 async function apply(proposal:Proposal){
  await flushDrafts();
  const ref=conversation?.context.find(r=>r.projectId===proposal.spec.projectId&&r.strategyId===proposal.spec.strategyId);
  if(!ref?.projectId||!ref.strategyId)throw new Error("请先把目标策略明确关联到当前研究会话。");
  const strategies=await request<StrategyConfig[]>("strategies.list",{projectId:ref.projectId});
  const strategy=strategies.find(st=>st.id===ref.strategyId);
  if(!strategy)throw new Error("关联策略已不存在。");
  const key=proposal.spec.kind==="backtest.run"?"backtest":proposal.spec.kind==="model.train"?"model":proposal.spec.kind==="factor.analyze"?"factorAnalysis":null;
  if(!key)throw new Error("此任务可在研究模式中查看参数后运行。");
  const {factorIds,factorProcessing:processing,customFactors}=proposal.spec.parameters;
  const configured:JsonObject={...object(strategy.settings[key]),...proposal.spec.parameters};
  if(configured.weights)configured.weights={...object(object(strategy.settings[key]).weights),...object(configured.weights)};
  const next:JsonObject={...strategy.settings,[key]:configured};
  if(factorIds!==undefined)next.selectedFactors=factorIds;
  if(processing!==undefined){
   const previous=object(strategy.settings.factorProcessing),supplied=object(processing);
   next.factorProcessing={...previous,...supplied,directions:{...object(previous.directions),...object(supplied.directions)}};
   configured.factorProcessing=next.factorProcessing;
  }
  if(Array.isArray(customFactors)){
   const supplied=new Set(customFactors.map(item=>object(item).id));
   const existing=Array.isArray(strategy.settings.customFactors)?strategy.settings.customFactors:[];
   next.customFactors=[...existing.filter(item=>!supplied.has(object(item).id)),...customFactors];
  }
  await request("strategies.save",{projectId:ref.projectId,strategy:{id:strategy.id},settingsPatch:changedSettings(strategy.settings,next)});
  await w.reload();
  w.open({kind:key==="backtest"?"strategy":key==="model"?"model":"factors",title:strategy.name,projectId:ref.projectId,strategyId:ref.strategyId});
  s.setNotice("AI 参数已保存为策略草稿，请核对后运行或应用到每日选股");
 }
 async function run(){if(!conversation||busy)return;setBusy(true);const submitted:string[]=[];await s.act(async()=>{for(let i=0;i<proposals.length;i++){const p=proposals[i];const event=await request<JobEvent>("jobs.submit",{spec:p.spec});submitted.push(event.id);await save({state:{...object(current.current?.state),proposals:proposals.slice(i+1) as unknown as JsonObject[],stageJobIds:[...submitted]}});}s.setNotice("当前研究阶段已提交；完成后可携结果继续讨论");});setBusy(false);}
 return <aside className="r-ai"><div className="r-toolbar"><h2>研究助手</h2><button disabled={busy} onClick={()=>void s.act(create)}>＋ 新会话</button></div><input aria-label="搜索研究会话" placeholder="搜索研究会话" value={search} onChange={e=>setSearch(e.target.value)}/><div className="r-toolbar"><select aria-label="当前研究会话" disabled={busy} value={conversation?.id??""} onChange={e=>void s.act(()=>select(e.target.value))}><option value="">选择研究会话</option>{list.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{conversation&&<button disabled={busy} aria-label="重命名会话" onClick={()=>void s.act(async()=>{const name=await requestText("研究会话名称",conversation.name);if(name?.trim())await save({name:name.trim()});})}>重命名</button>}</div>
 {showSettings?<div className="r-ai-settings"><h3>AI 服务设置</h3>{settings&&<><Field label="兼容 API 地址（在线或本地）"><input value={settings.ai.baseUrl} onChange={e=>setSettings({...settings,ai:{...settings.ai,baseUrl:e.target.value}})}/></Field><Field label="模型名称"><input value={settings.ai.model} onChange={e=>setSettings({...settings,ai:{...settings.ai,model:e.target.value}})}/></Field><Field label="API Key"><input type="password" autoComplete="off" value={settings.ai.apiKey} onChange={e=>setSettings({...settings,ai:{...settings.ai,apiKey:e.target.value}})}/></Field><Field label="Temperature"><input type="number" min={0} max={2} step={.1} value={settings.ai.temperature} onChange={e=>setSettings({...settings,ai:{...settings.ai,temperature:Number(e.target.value)}})}/></Field><button onClick={()=>setSettings({...settings,ai:{...settings.ai,baseUrl:"https://openrouter.ai/api/v1",model:"inclusionai/ling-3.0-flash-fin:free"}})}>填入 OpenRouter · Ling 默认值</button><button className="r-primary" onClick={()=>void s.act(async()=>{await request("settings.save",{settings});setServiceStatus(configurationStatus(settings));s.setNotice("设置已保存，服务连接情况以实际请求为准");setShowSettings(false);closeSettings();})}>保存设置</button><p className="r-note">本地服务需自行启动兼容接口。保存地址不会被标记为已连接。</p></>}<button onClick={()=>{setShowSettings(false);closeSettings();}}>返回研究会话</button></div>:<>
 {conversation&&<><div className="r-conversation-refs"><div className="r-toolbar"><strong>明确关联对象</strong><button disabled={!w.active||busy} onClick={()=>void s.act(async()=>{if(!w.active)return;const {kind,projectId,strategyId,experimentId,symbol,title}=w.active;const ref:ResearchObjectRef={kind,projectId,strategyId,experimentId,symbol,title};const refs = w.active.kind === "compare" && w.active.experimentRefs?.length ? w.active.experimentRefs : [ref]; const unique = [...conversation.context]; for (const item of refs) if (!unique.some(x => x.kind === item.kind && x.projectId === item.projectId && x.strategyId === item.strategyId && x.experimentId === item.experimentId && x.symbol === item.symbol)) unique.push(item); await save({context:unique});})}>＋ 关联当前对象</button></div>{conversation.context.length?conversation.context.map((ref,i)=><div className="r-ref" key={i}><button onClick={()=>w.open({...ref,title:referenceName(ref)})}>{referenceName(ref)}</button><button aria-label="解除关联" disabled={busy} onClick={()=>void s.act(()=>save({context:conversation.context.filter((_,j)=>j!==i)}))}>×</button></div>):<p className="r-note">尚未关联对象。切换标签不会改变这个会话。</p>}</div><nav className="r-subtabs">{[["ask","问答"],["assist","辅助配置"],["research","阶段研究"]].map(([id,title])=><button disabled={busy} key={id} className={mode===id?"active":""} onClick={()=>void s.act(()=>save({state:{...state,mode:id}}))}>{title}</button>)}</nav></>}
 <div className="r-chat-log" aria-live="polite">{!conversation?<p className="r-note">创建命名会话，关联策略、股票或多个实验，然后展开研究。</p>:!messages.length?<p className="r-note">围绕已关联对象讨论方案，运行真实实验后再解释结果。</p>:messages.map((m,i)=><div className={`r-message ${m.role}`} key={i}><small>{m.role==="user"?"你":"研究助手"}</small><p>{m.content}</p>{(m.experimentRefs ?? m.experimentIds?.flatMap(id => { const matches = s.experiments.filter(e => e.id === id && conversation.context.some(ref => ref.projectId === e.projectId)); return matches.length === 1 ? [{ kind: "experiment" as const, projectId: matches[0].projectId, experimentId: id, title: matches[0].name }] : []; }) ?? []).map((ref,index) => <button key={index} onClick={() => w.open({ ...ref, kind: "experiment", title: ref.title ?? s.experiments.find(e => e.id === ref.experimentId && e.projectId === ref.projectId)?.name ?? "实验结果" })}>查看关联实验 →</button>)}</div>)}{busy&&<p role="status">正在处理真实请求…</p>}{proposals.map((p,i)=><section className="r-proposal" key={i}><h3>{p.title}</h3><p>{p.description}</p><details><summary>查看运行参数</summary><pre>{JSON.stringify(p.spec,null,2)}</pre></details>{mode==="assist"&&<button disabled={busy} onClick={()=>void s.act(()=>apply(p))}>保存为关联策略草稿</button>}</section>)}{mode==="research"&&proposals.length>0&&<button className="r-primary" disabled={busy||stageIds.length>0&&!terminal} onClick={()=>void run()}>运行这一阶段（{proposals.length} 项）</button>}{stageIds.map(id=>{const job=s.jobs.find(j=>j.id===id);return <div key={id} className="r-note">{job?.name??id} · {job?.message??"等待任务状态"}{job?.experimentId&&<button onClick={()=>w.open({kind:'experiment',title:job.name||'阶段研究结果',projectId:job.projectId,strategyId:job.strategyId,experimentId:job.experimentId})}>查看阶段结果 →</button>}</div>;})}{terminal&&<button onClick={()=>void send(`本阶段任务已结束，请读取实际结果并讨论下一步，先不要执行：${stageIds.join(", ")}`)}>携阶段结果继续讨论</button>}</div><form className="r-chat-compose" onSubmit={e=>{e.preventDefault();void send();}}><textarea aria-label="研究问题" placeholder="描述问题，先讨论再运行…" disabled={!conversation} value={input} onChange={e=>setInput(e.target.value)}/><button className="r-send" disabled={!conversation||busy||!input.trim()} aria-label="发送">↑</button></form><div className="r-toolbar r-ai-footer"><button onClick={()=>setShowSettings(true)}>服务设置</button><span role="status">{serviceStatus}</span>{conversation&&<button disabled={busy} onClick={()=>void s.act(async()=>{if(!window.confirm(`删除会话“${conversation.name}”？`))return;await request("ai.conversations.delete",{conversationId:conversation.id});setConversation(null);await refreshList();})}>删除会话</button>}</div></>}
 </aside>;
}
