import React, { useEffect, useRef, useState } from 'react';
import type { DailyResearchPlan, JsonObject, ScreenerPlan, SelectionPositionsSource } from '../../../../../packages/contracts/src/research';
import { errorText, request, useResearch } from './state';
import { SelectionPositionsSourceEditor } from './SelectionPositionsSourceEditor';
import { PortfolioEditor, portfolioDefaults } from './configuration';
import { Empty } from './ui';

export function DailyResearchPanel({children}:{children:React.ReactNode}) {
  const s=useResearch(),saveRef=useRef<(()=>Promise<void>)|null>(null),edited=useRef(new Set<string>());
  const [positionsSource,setPositionsSource]=useState<SelectionPositionsSource>({kind:'none'});
  const [researchDate,setResearchDate]=useState('');
  const actionLock=useRef(false);
  const [plans,setPlans]=useState<DailyResearchPlan[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [portfolio,setPortfolio]=useState<JsonObject>({...portfolioDefaults}),[update,setUpdate]=useState(true),[comparison,setComparison]=useState<{plan:DailyResearchPlan;latest:ScreenerPlan}|null>(null);
  async function load(){setLoading(true);try{const values=await request<DailyResearchPlan[]>('dailyPlans.list');setPlans(previous=>values.map(value=>{const local=previous.find(plan=>plan.id===value.id);return local&&edited.current.has(value.id)?{...value,allocation:local.allocation,enabled:local.enabled}:value;}));}catch(e){setError(errorText(e));}finally{setLoading(false);}}
  useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener('v3-daily-plans-changed',refresh);return()=>window.removeEventListener('v3-daily-plans-changed',refresh);},[]);
  async function act(fn:()=>Promise<void>){if(actionLock.current)return;actionLock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(errorText(e));}finally{actionLock.current=false;setBusy(false);}}
  const usingSimulation=positionsSource.kind==='simulation';
  const enabled=plans.filter(plan=>plan.enabled),total=enabled.reduce((sum,plan)=>sum+plan.allocation,0);
  const invalid=enabled.some(plan=>!Number.isFinite(plan.allocation)||plan.allocation<0)||total<=0||total>1.000001;
  async function save(){for(const plan of plans)await request('dailyPlans.save',{id:plan.id,name:plan.name,allocation:plan.allocation,enabled:plan.enabled});edited.current.clear();}
  const patch=(id:string,values:Partial<DailyResearchPlan>)=>{edited.current.add(id);setPlans(rows=>rows.map(plan=>plan.id===id?{...plan,...values}:plan));};
  return <div className="r-page"><div className="r-toolbar"><h1>每日研究方案</h1><span className="r-spacer"/><button disabled={busy||loading||usingSimulation} onClick={()=>void load()}>刷新来源版本</button></div><p className="r-note">使用选股器中保存的固定版本。源方案更新不会自动替换每日配置；默认只研究候选；账户相关清单需明确选择持仓来源，读取模拟账户不会推进。</p>{error&&<p role="alert">{error}</p>}<fieldset disabled={busy||usingSimulation} className="simulation-source-options"><legend>自由每日方案（模拟账户研究不使用）</legend>{loading?<p role="status">正在读取固定方案…</p>:!plans.length?<Empty title="尚未引用选股方案">在选股器保存方案后，点击“应用到每日研究”。</Empty>:<><div className="r-table-scroll"><table><thead><tr><th>参与</th><th>方案与来源</th><th>版本</th><th>资金占比 %</th><th>更新</th></tr></thead><tbody>{plans.map(plan=><tr key={plan.id}><td><input aria-label={`参与每日研究${plan.name}`} type="checkbox" disabled={busy} checked={plan.enabled} onChange={e=>patch(plan.id,{enabled:e.target.checked})}/></td><td><strong>{plan.name}</strong><br/><small>{plan.planSnapshot.name}</small></td><td>固定 v{plan.planVersion}{plan.sourceUnavailable?<p className="r-note">源方案不可用，保留固定副本</p>:plan.sourceChanged?<p className="r-note">源方案已到 v{plan.latestVersion}</p>:null}</td><td><input aria-label={`${plan.name}每日资金占比`} type="number" min={0} max={100} disabled={busy} value={Math.round(plan.allocation*10000)/100} onChange={e=>patch(plan.id,{allocation:Number(e.target.value)/100})}/></td><td>{plan.sourceChanged&&!plan.sourceUnavailable&&<button disabled={busy} onClick={()=>void act(async()=>setComparison({plan,latest:await request<ScreenerPlan>('screeners.get',{id:plan.planId})}))}>查看版本差异</button>}<button disabled={busy} onClick={()=>void act(async()=>{await request('dailyPlans.delete',{id:plan.id});await load();})}>移除每日引用</button></td></tr>)}</tbody></table></div><p className="r-note">分配资金 {(total*100).toFixed(2)}% · 未分配 {(Math.max(0,1-total)*100).toFixed(2)}% 留作现金</p><button disabled={busy||plans.some(plan=>!Number.isFinite(plan.allocation)||plan.allocation<0||plan.allocation>1)} onClick={()=>void act(async()=>{await save();await load();s.setNotice('每日研究资金与参与状态已保存，固定版本保持不变。');})}>保存每日配置</button></>}
    {comparison&&<section><h2>{comparison.plan.name} · v{comparison.plan.planVersion} → v{comparison.latest.version}</h2><p className="r-note">核对变更后再采用。采用操作使用源方案当前已保存版本。</p><div className="r-table-scroll"><table><thead><tr><th>配置</th><th>当前固定版本</th><th>源方案版本</th></tr></thead><tbody>{(['universe','date','dataProjectId','conditions','preconditions','factors','assets','rankingReference','limit'] as const).filter(key=>JSON.stringify(comparison.plan.planSnapshot[key])!==JSON.stringify(comparison.latest[key])).map(key=><tr key={key}><td>{({universe:'股票范围',date:'数据日期',dataProjectId:'数据项目',conditions:'条件',preconditions:'预筛条件',factors:'因子权重',assets:'成果版本',rankingReference:'排名参照',limit:'数量上限'})[key]}</td><td style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(comparison.plan.planSnapshot[key]??null,null,2)}</td><td style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(comparison.latest[key]??null,null,2)}</td></tr>)}</tbody></table></div><div className="r-toolbar"><button disabled={busy} onClick={()=>void act(async()=>{const current=plans.find(plan=>plan.id===comparison.plan.id);if(!current)return;await request('dailyPlans.save',{id:current.id,name:current.name,allocation:current.allocation,enabled:current.enabled,adoptLatest:true});setComparison(null);await load();})}>采用源方案最新已保存版本</button><button onClick={()=>setComparison(null)}>保留当前固定版本</button></div></section>}
    </fieldset><label className='r-check'>研究日期（留空使用最近完整交易日）<input aria-label='每日研究日期' type='date' value={researchDate} onChange={e=>setResearchDate(e.target.value)}/></label><SelectionPositionsSourceEditor value={positionsSource} onChange={setPositionsSource} saveRef={saveRef} disabled={busy}/><details><summary>合并组合约束</summary><fieldset disabled={busy||usingSimulation}><PortfolioEditor value={portfolio} onChange={setPortfolio}/></fieldset></details><label className="r-check"><input type="checkbox" checked={update} onChange={e=>setUpdate(e.target.checked)}/>生成前更新数据</label><button className="r-primary" disabled={busy||(!usingSimulation&&(loading||!enabled.length||invalid))} onClick={()=>void act(async()=>{if(!saveRef.current)throw Error('持仓来源仍在读取，请稍后重试。');await saveRef.current();if(!usingSimulation)await save();await request('jobs.submit',{spec:{kind:'selection.run',name:usingSimulation?'账户固定版本研究':'固定方案每日研究',parameters:usingSimulation?{positionsSource,updateData:update,...(researchDate?{date:researchDate}:{})}:{dailyPlanIds:enabled.map(plan=>plan.id),portfolio,updateData:update,positionsSource,...(researchDate?{date:researchDate}:{})}}});s.setNotice('每日研究已进入任务队列，实际持仓保持不变。');})}>{usingSimulation?'按账户固定版本生成建议':positionsSource.kind==='none'?'生成固定方案候选':'生成固定方案调仓清单'}</button>{children}</div>;
}
