import React, { useEffect, useState } from 'react';
import type { JsonObject, MarketOverview, QuoteInstrument } from '../../../../../packages/contracts/src/research';
import { MarketBoardDetail } from './MarketBoardDetail';
import { Empty, fieldLabel, tableValue } from './ui';

const identity=(row:JsonObject)=>`${row.source??''}:${row.symbol??row.code??row.name}`;
const change=(row:JsonObject)=>{if('strengthChangeRatio' in row)return {key:'changeRatio',value:typeof row.strengthChangeRatio==='number'?row.strengthChangeRatio:null};for(const key of ['changeRatio','changePct','pctChange','meanChangeRatio'])if(typeof row[key]==='number')return {key,value:row[key] as number};return {key:'changeRatio',value:null};};
const tone=(value:number|null)=>value===null?'missing':value>0?'up':value<0?'down':'flat';
function dateOf(rows:JsonObject[]){return [...new Set(rows.map(row=>row.strengthEndDate??row.asOfDate??row.date).filter(Boolean))].join('、')||'来源未提供行情日期';}
export function MarketOverviewView({value,onOpen}:{value:MarketOverview;onOpen:(kind:'index'|'industry'|'concept',row:JsonObject)=>void}) {
  const [board,setBoard]=useState<QuoteInstrument|null>(null);
  const choose=(kind:'industry'|'concept',row:JsonObject)=>setBoard({kind,symbol:String(row.symbol??row.code),name:String(row.name??row.symbol),source:typeof row.source==='string'?row.source:undefined});
  const stockCoverage=value.coverage.find(item=>item.dataset==='stocks');
  const max=Math.max(1,...value.breadth.map(row=>typeof row.count==='number'?row.count:0));
  return <div className="r-market-overview">{value.strength&&<p className="r-note">{value.strength.days===1?'当日快照':`近 ${value.strength.days} 交易日`} · {value.strength.asOfDate??'来源未提供日期'} · 强弱覆盖 {value.strength.covered}/{value.strength.total} · {value.strength.message}</p>}<section><h2>主要指数</h2><p className="r-note">{dateOf(value.indices)} · {value.indices.length} 项实际覆盖</p>{value.indices.length?<div className="r-index-strip">{value.indices.map(row=>{const move=change(row);return <button key={identity(row)} onClick={()=>onOpen('index',row)}><span>{String(row.name??row.symbol??row.code)}</span><strong>{tableValue(row.close??row.price,'close','指数')}</strong><b className={`r-market-${tone(move.value)}`}>{tableValue(move.value,move.key,'指数')}</b><small>{String(row.source??'来源未提供')}</small></button>;})}</div>:<Empty title="尚无指数快照">更新后展示来源实际返回的指数。</Empty>}</section><div className="r-market-summary-grid"><section><h2>涨跌分布</h2><p className="r-note">{stockCoverage?.endDate??'来源未提供行情日期'} · 涨跌幅覆盖 {value.summary.changeCoveredStocks??'—'} 只</p><div className="r-breadth-bars">{value.breadth.map(row=><div key={String(row.name)}><span>{String(row.name)}</span><i><em className={String(row.name).includes('跌')?'r-market-bar-down':'r-market-bar-up'} style={{width:typeof row.count==='number'?`${row.count/max*100}%`:'0%'}}/></i><b>{row.count==null?'—':String(row.count)}</b></div>)}</div><p className="r-note">平盘 {value.summary.unchanged??'—'} 只；仅统计已返回涨跌幅的证券。</p></section><section><h2>成交与覆盖</h2><p className="r-note">{stockCoverage?.endDate??'来源未提供行情日期'} · {stockCoverage?.source??'来源未提供'}</p><div className="r-market-key-metrics">{['turnoverAmount','observedStocks','fundNetAmount','fundCoveredStocks'].map(key=><div key={key}><span>{fieldLabel(key)}</span><strong>{tableValue(value.summary[key],key,'市场概况')}</strong></div>)}</div><p className="r-note">{stockCoverage?.message??'实际覆盖不代表全市场完整。'}</p></section></div><BoardHeatmap title="行业" rows={value.industries} onOpen={row=>choose('industry',row)}/><BoardHeatmap title="概念" rows={value.concepts??[]} onOpen={row=>choose('concept',row)}/>{board&&<MarketBoardDetail key={`${board.source}:${board.symbol}`} instrument={board} onClose={()=>setBoard(null)}/>}</div>;
}
function BoardHeatmap({title,rows,onOpen}:{title:string;rows:JsonObject[];onOpen:(row:JsonObject)=>void}) {
  const [order,setOrder]=useState<string[]>([]),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[display,setDisplay]=useState<'heat'|'rank'>('heat');
  const lookup=new Map(rows.map(row=>[identity(row),row]));
  const keys=[...order.filter(id=>lookup.has(id)),...rows.map(identity).filter(id=>!order.includes(id))];
  useEffect(()=>setOrder(previous=>[...previous.filter(id=>lookup.has(id)),...rows.map(identity).filter(id=>!previous.includes(id))]),[rows]);
  const reorder=(descending:boolean)=>setOrder([...keys].sort((a,b)=>{const left=change(lookup.get(a)!).value,right=change(lookup.get(b)!).value;if(left===null)return right===null?0:1;if(right===null)return -1;return descending?right-left:left-right;}));
  const visible=keys.filter(id=>`${lookup.get(id)?.name??''} ${lookup.get(id)?.symbol??''}`.toLowerCase().includes(search.toLowerCase()));
  return <section><div className="r-toolbar"><h2>{title}强弱</h2><span className="r-note">{Number(rows[0]?.strengthDays??1)===1?'当日':`近 ${rows[0]?.strengthDays} 交易日`} · {rows.length} 项</span><span className="r-spacer"/><button aria-pressed={display==='heat'} onClick={()=>setDisplay('heat')}>热力</button><button aria-pressed={display==='rank'} onClick={()=>{setDisplay('rank');reorder(true);}}>排名</button></div><p className="r-note">{dateOf(rows)} · 刷新保留顺序。{title==='概念'?'概念成员可能重叠，不汇总为全市场。':'使用来源板块快照。'}</p><div className="r-toolbar"><input aria-label={`搜索${title}`} placeholder={`搜索${title}`} value={search} onChange={event=>setSearch(event.target.value)}/><button onClick={()=>reorder(true)}>按涨幅重排</button><button onClick={()=>reorder(false)}>按跌幅重排</button></div>{!rows.length?<Empty title={`尚无${title}快照`}>缺失数据保持为空。</Empty>:<div className={display==='heat'?'r-board-heatmap':'r-board-ranking'}>{visible.map((id,index)=>{const row=lookup.get(id)!,move=change(row);return <button key={id} aria-pressed={selected===id} className={`r-board-tile r-market-${tone(move.value)}`} onClick={()=>{setSelected(id);onOpen(row);}} title={`${String(row.name??'')} · ${String(row.strengthSource??row.source??'来源未提供')} · ${String(row.strengthMessage??'')}`}><span>{display==='rank'&&<small>{index+1} </small>}{String(row.name??row.symbol??row.code)}</span><strong>{tableValue(move.value,move.key,title)}</strong></button>;})}</div>}</section>;
}
