import React, { useEffect, useRef, useState } from 'react';
import type { QuoteInstrument, QuoteMembers, ScreenerPlan } from '../../../../../packages/contracts/src/research';
import { errorText, request, useResearch } from './state';
import { useWorkspace } from './workspace';
import { PriceChart } from './PriceChart';
import { MarketSnapshotTable } from './MarketSnapshotTable';
import { emptyGroup } from './ScreenerConditions';
export function MarketBoardDetail({instrument,onClose}:{instrument:QuoteInstrument;onClose:()=>void}) {
  const root=useRef<HTMLElement>(null),refreshMembers=useRef(false);const [revision,setRevision]=useState(0);
  useEffect(()=>{const frame=requestAnimationFrame(()=>root.current?.scrollIntoView({block:"start"}));return()=>cancelAnimationFrame(frame);},[instrument.symbol,instrument.source]);
  const w=useWorkspace(),s=useResearch(),[members,setMembers]=useState<QuoteMembers|null>(null),[offset,setOffset]=useState(0),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  useEffect(()=>{let active=true;setLoading(true);setError('');const refresh=refreshMembers.current;refreshMembers.current=false;void request<QuoteMembers>('market.members',{instrument,offset,limit:100,refresh}).then(value=>{if(active)setMembers(value);}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[instrument.symbol,instrument.source,offset,revision]);
  async function screen(){if(busy)return;setBusy(true);setError('');try{const symbols:string[]=[];let cursor=0,date:string|null=null,total:number|null=null;while(true){const page=await request<QuoteMembers>('market.members',{instrument,offset:cursor,limit:500,refresh:false});if(page.status==='source_error')throw Error(page.message??'成员来源不可用。');if(!page.asOfDate)throw Error('成员来源未提供日期，暂不能保存带日期的静态范围。');if(cursor&&(date!==page.asOfDate||total!==page.total))throw Error('读取期间成员日期或数量发生变化，请重新读取。');date=page.asOfDate;total=page.total;symbols.push(...page.rows.map(row=>String(row.symbol??row.code??'')).filter(Boolean));cursor+=page.rows.length;if(cursor>=page.total)break;if(!page.rows.length)throw Error('未读取完整成员名单。');}if(!symbols.length)throw Error('没有可用于选股的成员代码。');const plan:ScreenerPlan={id:'',name:`${instrument.name??instrument.symbol} · 当前成员 ${date}`,mode:'conditions',version:0,universe:{name:`当前成员静态范围 · ${date}`,source:'manual',symbols:[...new Set(symbols)],excludeST:true,minListingDays:60},conditions:emptyGroup(),factors:[],assets:[],rankingReference:'base',limit:30};const saved=await request<ScreenerPlan>('screeners.save',{plan});await request('screeners.workspace.save',{state:{activePlanId:saved.id,draft:saved,view:'screen',conditionsCollapsed:false}});window.dispatchEvent(new CustomEvent('v3-open-screener-plan',{detail:saved.id}));w.open({kind:'screener',title:'筛选与自选'});s.setNotice(`已复制 ${saved.universe.symbols.length} 只当前成员（${date}），未运行选股。`);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <section ref={root} className="r-market-board-detail"><div className="r-toolbar"><h2>{instrument.name??instrument.symbol}</h2><button onClick={()=>w.open({kind:'quote',title:`${instrument.name??instrument.symbol} · 行情`,instrument})}>完整行情</button><button disabled={busy||loading||!members?.total} onClick={()=>void screen()}>{busy?'正在复制完整范围…':'以当前成员进入选股'}</button><span className="r-spacer"/><button onClick={onClose}>收起板块</button></div><div style={{height:380,minHeight:260}}><PriceChart key={`${instrument.source}:${instrument.symbol}`} symbol={instrument.symbol} instrument={instrument} embedded priceBasis="raw"/></div><button disabled={loading||busy} onClick={()=>{refreshMembers.current=true;setRevision(value=>value+1);}}>更新当前成员</button><h3>当前成员 · {members?.asOfDate??'日期未提供'} · {members?.total??'—'} 只</h3><p className="r-note">当前成员不能代表历史成分。{members?.source} {members?.message}</p>{error&&<p role="alert">{error}</p>}{loading?<p role="status">正在读取当前成员…</p>:members?.rows.length?<MarketSnapshotTable name="当前成员" rows={members.rows} onRow={row=>w.open({kind:'quote',title:String(row.name??row.symbol),instrument:{kind:'stock',symbol:String(row.symbol??row.code),name:String(row.name??'')}})}/>:<p>暂无成员资料。</p>}<div className="r-toolbar"><button disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-100))}>上一页成员</button><span>{members?.total?`${offset+1}–${offset+members.rows.length} / ${members.total}`:'0'} 行</span><button disabled={loading||offset+(members?.rows.length??0)>=(members?.total??0)} onClick={()=>setOffset(offset+100)}>下一页成员</button></div></section>;
}
