import React,{useEffect,useState} from "react";
import type {JsonObject} from "../../../../../packages/contracts/src/research";
import {tableValue} from "./ui";
export function MarketSnapshotTable({ name, rows, onRow }: { name: string; rows: JsonObject[]; onRow: (row: JsonObject) => void }) {
 const key = (row: JsonObject) => `${row.source ?? ""}:${row.symbol ?? row.code ?? row.name}`;
 const [order, setOrder] = useState<string[]>([]), [selected, setSelected] = useState(""), [sort, setSort] = useState({ field: "", ascending: false });
 const lookup = new Map(rows.map(row => [key(row), row]));
 const keys = [...order.filter(id => lookup.has(id)), ...rows.map(key).filter(id => !order.includes(id))];
 useEffect(() => { setOrder(previous => [...previous.filter(id => lookup.has(id)), ...rows.map(key).filter(id => !previous.includes(id))]); }, [rows]);
 const candidates = ["name", "symbol", "code", "changeRatio", "changePct", "pctChange", "meanChangeRatio", "amount", "turnoverAmount", "turnover", "close", "price", "memberCount", "count"];
 const changeField=["changeRatio","pctChange","changePct","meanChangeRatio"].find(field=>rows.some(row=>row[field]!=null));
 const columns = candidates.filter(field=>!["changeRatio","pctChange","changePct","meanChangeRatio"].includes(field)||field===changeField).filter(field => rows.some(row => row[field] != null)).filter(field => !(field === "code" && rows.some(row => row.symbol)) && !(field === "meanChangeRatio" && rows.some(row => row.changeRatio != null)) && !(field === "price" && rows.some(row => row.close != null)) && !(field === "turnoverAmount" && rows.some(row => row.amount != null)) && !(field === "turnover" && rows.some(row => row.amount != null || row.turnoverAmount != null)));
 const labels: Record<string,string> = { name: "名称", symbol: "代码", code: "代码", changeRatio: "涨跌幅", changePct: "涨跌幅", pctChange: "涨跌幅", meanChangeRatio: "平均涨跌幅", amount: "成交额", turnoverAmount: "成交额", turnover: "成交额", close: rows.some(row => String(row.priceUnit).includes("均价")) ? "成分均价" : "当前价", price: "当前价", memberCount: "成员数", count: "成员数" };
 const sortBy = (field: string) => { const ascending = sort.field === field ? !sort.ascending : false; setSort({ field, ascending }); setOrder([...keys].sort((a,b) => { const left=lookup.get(a)?.[field], right=lookup.get(b)?.[field]; if(left==null)return right==null?0:1;if(right==null)return -1;const compared=typeof left==='number'&&typeof right==='number'?left-right:String(left).localeCompare(String(right),'zh-CN');return ascending?compared:-compared; })); };
 const sources = [...new Set(rows.map(row => [row.source, row.priceUnit].filter(Boolean).join(" · ")).filter(Boolean))];
 return <section className="r-table-section"><div className="r-toolbar"><strong>{name}</strong><span>{rows.length} 项</span><span className="r-note">点击列名重排；刷新保留顺序和选中项</span></div>{sources.length > 0 && <p className="r-note">{sources.join("；")}</p>}<div className="r-table-scroll"><table><thead><tr>{columns.map(field => <th key={field}><button onClick={() => sortBy(field)}>{labels[field]}{sort.field===field?(sort.ascending?" ↑":" ↓"):""}</button></th>)}</tr></thead><tbody>{keys.map(id => { const row=lookup.get(id)!;return <tr key={id} className={selected===id?"selected":""} onClick={() => {setSelected(id);onRow(row);}}>{columns.map((field,index) => <td key={field} className={typeof row[field]==='number'?"r-number":undefined}>{index===0?<button className="r-link" onClick={event=>{event.stopPropagation();setSelected(id);onRow(row);}}>{tableValue(row[field],field,name)}</button>:tableValue(row[field],field,name)}</td>)}</tr>;})}</tbody></table></div></section>;
}
