import React, { useEffect, useRef, useState } from "react";
import type { ProjectSummary, ResearchConversation } from "../../../../../packages/contracts/src/research";
import { request, errorText } from "./state";
import { useWorkspace } from "./workspace";
import { Field } from "./ui";

export function ProjectSummaryPanel({ projectId, refreshVersion = 0, onOpenConversation, conversationBusy = false }: { projectId: string; refreshVersion?: number; onOpenConversation: (id: string) => Promise<void>; conversationBusy?: boolean }) {
  const w = useWorkspace();
  const [summary, setSummary] = useState<ProjectSummary | null>(null);
  const [editing, setEditing] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const editBase=useRef<ProjectSummary|null>(null);
  const [sources,setSources]=useState<ResearchConversation[]>([]);
  useEffect(() => { let alive = true;if(editing)return; void request<ProjectSummary>("ai.projectSummary.get", { projectId }).then(value => { if (alive) setSummary(value); }).catch(e => { if (alive) setError(errorText(e)); }); return () => { alive = false; }; }, [projectId,refreshVersion,editing]);
  useEffect(()=>{let alive=true;void request<ResearchConversation[]>("ai.conversations.list",{projectId}).then(items=>{if(alive)setSources(items.filter(item=>item.projectId===projectId));}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[projectId,summary?.revision]);
  const openSource=async(id:string)=>{setError("");try{const source=await request<ResearchConversation>("ai.conversations.get",{conversationId:id});if(source.projectId!==projectId)throw new Error("该来源会话不属于当前项目，未打开。");await onOpenConversation(id);}catch(e){setError(errorText(e));}};
  const act = async (method: string) => { setBusy(true); setError(""); try { setSummary(await request<ProjectSummary>(method, { projectId, ...(method.endsWith("save") ? { summary, expectedRevision: summary?.revision } : {}) })); setEditing(false); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } };
  const sections = [["goals", "研究目标"], ["userDecisions", "已确认决定"], ["hypotheses", "待验证假设"], ["unresolved", "未解决问题"]] as const;
  return <details className="r-project-summary"><summary>项目摘要 <small>{summary?.updatedAt ? `更新于 ${summary.updatedAt.slice(0, 10)}` : "尚未整理"}</small></summary><div className="r-summary-body">{error && <p role="alert">{error}</p>}{summary && <>{sections.map(([key, label]) => <section key={key}><h4>{label}</h4>{editing ? <textarea aria-label={label} disabled={busy} rows={3} value={summary[key].join("\n")} onChange={e => setSummary({ ...summary, [key]: e.target.value.split("\n").filter(line => line.trim()) })} /> : summary[key].length ? <ul>{summary[key].map((text, i) => <li key={i}>{text}</li>)}</ul> : <p className="r-note">暂无记录</p>}</section>)}<section><h4>实验结论与来源</h4>{summary.experimentFindings.map((finding, index) => <div key={index}>{editing ? <><Field label="结论"><textarea value={finding.conclusion} onChange={e => setSummary({ ...summary, experimentFindings: summary.experimentFindings.map((item, i) => i === index ? { ...item, conclusion: e.target.value } : item) })} /></Field><button onClick={() => setSummary({ ...summary, experimentFindings: summary.experimentFindings.filter((_, i) => i !== index) })}>移除此结论</button></> : <p>{finding.conclusion}</p>}<button onClick={() => w.open({ kind: "experiment", projectId, experimentId: finding.experimentId, title: `来源实验 · ${finding.date}` })}>{finding.date} · 查看实验</button></div>)}{!summary.experimentFindings.length && <p className="r-note">暂无实验结论</p>}</section>{!!summary.sourceConversationIds?.length&&<section><h4>来源会话</h4>{summary.sourceConversationIds.map(id=>{const source=sources.find(item=>item.id===id);return <button key={id} disabled={conversationBusy} onClick={()=>void openSource(id)}>{source?.name??`来源会话 ${id}`} {source?.updatedAt.slice(0,10)} →</button>;})}</section>}{editing ? <Field label="补充笔记"><textarea rows={3} value={summary.notes} onChange={e => setSummary({ ...summary, notes: e.target.value })} /></Field> : summary.notes && <p>{summary.notes}</p>}<div className="r-toolbar">{editing ? <button disabled={busy} onClick={() => void act("ai.projectSummary.save")}>保存摘要</button> : <button disabled={busy} onClick={() => {editBase.current=summary;setEditing(true);}}>编辑</button>}{editing&&<button disabled={busy} onClick={()=>{setSummary(editBase.current);setError("");setEditing(false);}}>取消编辑</button>}<button disabled={busy} onClick={() => void act("ai.projectSummary.refresh")}>{busy ? "处理中…" : "整理项目摘要"}</button><button disabled={busy} onClick={() => { if (window.confirm("清除项目摘要？会话和实验记录会保留。")) void act("ai.projectSummary.clear"); }}>清除摘要</button></div><p className="r-note">摘要独立于会话。新对话会带入项目摘要；假设尚待验证，实验结论可回看来源。</p></>}</div></details>;
}
