import React, { useEffect, useRef, useState } from 'react';
import type { ReminderRule, ReminderScopeSnapshot, ReminderHistoryPage, ReminderPriceMode, ReminderRuntime, Watchlist } from '../../../../../packages/contracts/src/research';
import { request, errorText } from './state';
import './reminders.css';
const names: Record<string,string> = { draft:'草稿', paused:'已暂停', enabled:'已启用', deleted:'已删除', mode_pending:'尚未选择价格模式', source_unavailable:'真实行情来源尚未接入', unknown:'无法判断', triggered:'触发', not_triggered:'未触发' };
const reasonNames:Record<string,string>={source_unavailable:'行情来源暂不可用',invalid_price:'价格数据无效',stale_observation:'行情时间已过期',missing_data:'缺少行情数据',unsupported_symbol:'证券范围不支持'};
const reasonName=(code:string)=>reasonNames[code]??names[code]??('未知原因（代码：'+code+'）');
const modeName = (v: string | null) => v === 'intraday' ? '盘中' : v === 'daily_close' ? '每日收盘' : '尚未选择';
type Draft = { name:string; threshold:string; operator:'gte'|'lte'; priceMode:ReminderPriceMode };
const fresh = ():Draft => ({name:'价格提醒',threshold:'',operator:'gte',priceMode:'intraday'});
const ofRule = (r:ReminderRule):Draft => ({name:r.name,threshold:String(r.condition.threshold),operator:r.condition.operator,priceMode:r.priceMode || 'intraday'});
function Fields({value,onChange,disabled}:{value:Draft;onChange:(v:Draft)=>void;disabled:boolean}) {
  return <div className="reminder-fields"><label>提醒名称<input value={value.name} disabled={disabled} onChange={e=>onChange({...value,name:e.target.value})}/></label><label>价格模式<select value={value.priceMode} disabled={disabled} onChange={e=>onChange({...value,priceMode:e.target.value as ReminderPriceMode})}><option value="intraday">盘中</option><option value="daily_close">每日收盘</option></select></label><label>触发条件<select value={value.operator} disabled={disabled} onChange={e=>onChange({...value,operator:e.target.value as Draft['operator']})}><option value="gte">价格大于等于</option><option value="lte">价格小于等于</option></select></label><label>价格阈值（元）<input type="number" min="0" step="any" value={value.threshold} disabled={disabled} onChange={e=>onChange({...value,threshold:e.target.value})}/></label></div>;
}
function condition(d:Draft) { const threshold=Number(d.threshold); if(!d.name.trim()||!Number.isFinite(threshold)||threshold<=0) throw new Error('请填写名称和大于零的价格阈值'); return {operator:d.operator,threshold}; }
export function RemindersManagement({open,onClose,watchlists}:{open:boolean;onClose:()=>void;watchlists:Watchlist[]}) {
  const dialog=useRef<HTMLDialogElement>(null);
  const [rules,setRules]=useState<ReminderRule[]>([]),[deleted,setDeleted]=useState(false),[selected,setSelected]=useState<ReminderRule|null>(null);
  const [draft,setDraft]=useState<Draft>(fresh),[editing,setEditing]=useState<Draft>(fresh);
  const [source,setSource]=useState('single'),[symbol,setSymbol]=useState(''),[scope,setScope]=useState<ReminderScopeSnapshot|null>(null),[confirmed,setConfirmed]=useState(false);
  const [history,setHistory]=useState<ReminderHistoryPage|null>(null),[offset,setOffset]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[remove,setRemove]=useState(false);
  const [runtime,setRuntime]=useState<ReminderRuntime|null>(null),[runtimeError,setRuntimeError]=useState(''),[conflict,setConflict]=useState<{ruleId:string;local:Draft;latest:ReminderRule|null}|null>(null),[createReceipt,setCreateReceipt]=useState<Pick<ReminderRule,'id'|'name'>|null>(null);
  const lock=useRef(false),generation=useRef(0),createIntent=useRef<{key:string;id:string}|null>(null),checkIntent=useRef<{ruleId:string;version:number;id:string}|null>(null),drafts=useRef<Map<string,Draft>>(new Map());
  const loaded=useRef(false);
  useEffect(()=>{ if(open&&!dialog.current?.open)dialog.current?.showModal(); if(!open&&dialog.current?.open)dialog.current?.close(); },[open]);
  useEffect(()=>{if(open&&!loaded.current){loaded.current=true;void action(refreshRules);}},[open]);
  useEffect(()=>()=>{generation.current++;},[]);
  async function action(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(errorText(e));}finally{lock.current=false;setBusy(false);}}
  async function refreshRules(){setRules(await request<ReminderRule[]>('reminders.list',{includeDeleted:true}));try{setRuntime(await request<ReminderRuntime>('reminders.runtime'));setRuntimeError('');}catch(e){setRuntimeError(errorText(e));}}
  async function loadHistory(r:ReminderRule,page=0){const seq=++generation.current;const result=await request<ReminderHistoryPage>('reminders.history',{ruleId:r.id,offset:page,limit:10});if(seq===generation.current){setHistory(result);setOffset(page);}}
  function accept(r:ReminderRule,replaceDraft=false){if(selected&&selected.id!==r.id)drafts.current.set(selected.id,editing);const next=replaceDraft?ofRule(r):(selected?.id===r.id?editing:(drafts.current.get(r.id)??ofRule(r)));drafts.current.set(r.id,next);setSelected(r);setEditing(next);setRemove(false);setRules(prev=>[r,...prev.filter(x=>x.id!==r.id)]);if(replaceDraft)setConflict(null);}
  function editCurrent(next:Draft){setEditing(next);if(selected)drafts.current.set(selected.id,next);}
  async function choose(r:ReminderRule){accept(r);setHistory(null);await loadHistory(r);}
  function invalidate(){setScope(null);setConfirmed(false);createIntent.current=null;}
  async function preview(){const result=await request<ReminderScopeSnapshot>('reminders.scope.preview',source==='single'?{symbol}:{watchlistId:source});setScope(result);setConfirmed(false);createIntent.current=null;}
  async function acceptCurrentRule(ruleId:string){const current=await request<ReminderRule>('reminders.get',{ruleId});accept(current,true);setHistory(null);if(current.status==='deleted')setDeleted(true);return current;}
  async function create(){if(createReceipt)throw new Error('此提醒已创建，请读取当前规则或选择新建下一条。');if(!scope||!confirmed)throw new Error('请先预览并确认固定名单');const intent={name:draft.name.trim(),snapshotId:scope.id,condition:condition(draft),priceMode:draft.priceMode};const key=JSON.stringify(intent);if(createIntent.current?.key!==key)createIntent.current={key,id:crypto.randomUUID()};const receipt=await request<ReminderRule>('reminders.create',{...intent,requestId:createIntent.current.id});setCreateReceipt({id:receipt.id,name:receipt.name});setNotice('提醒“'+receipt.name+'”已收到创建成功回执，正在读取服务器当前状态。');try{const current=await acceptCurrentRule(receipt.id);setNotice('提醒已创建；当前规则为'+names[current.status]+' · v'+current.version+'。');try{await loadHistory(current);}catch(e){setError('当前规则已读取，但检查历史读取失败：'+errorText(e)+'。可单独重试。');}}catch(e){setError('提醒已创建，但读取当前规则失败：'+errorText(e));setNotice('提醒“'+receipt.name+'”创建成功；当前状态尚未读取，可单独重试读取当前规则。');}}
  function startNextCreate(){setCreateReceipt(null);createIntent.current=null;setDraft(fresh());setSource('single');setSymbol('');setScope(null);setConfirmed(false);setError('');setNotice('请重新预览固定名单后创建下一条提醒。');}
  async function readCreatedRule(){if(!createReceipt)return;const current=await acceptCurrentRule(createReceipt.id);try{await loadHistory(current);}catch(e){setError('当前规则已读取，但检查历史读取失败：'+errorText(e)+'。可单独重试。');}setNotice('已读取服务器中的当前规则版本：'+names[current.status]+' · v'+current.version+'。');}
  async function reloadSelected(){if(!selected)return;const latest=await request<ReminderRule>('reminders.get',{ruleId:selected.id});accept(latest,true);setHistory(null);try{await loadHistory(latest);}catch(e){setError('规则已重新读取，但检查历史读取失败：'+errorText(e)+'。可单独重试。');}setNotice('已读取服务器最新版；本地未保存编辑已丢弃。');}
  function isVersionConflict(e:unknown){const message=errorText(e).toLowerCase();return message.includes('version_conflict')||message.includes('version conflict')||message.includes('expectedversion')||message.includes('版本冲突')||message.includes('版本已更新');}
  async function update(status?:'draft'|'paused'){if(!selected)return;drafts.current.set(selected.id,editing);try{const r=await request<ReminderRule>('reminders.update',{ruleId:selected.id,expectedVersion:selected.version,name:editing.name.trim(),condition:condition(editing),priceMode:editing.priceMode,...(status?{status}:{})});accept(r,true);setNotice('已保存。');}catch(e){if(isVersionConflict(e))setConflict({ruleId:selected.id,local:editing,latest:null});throw e;}}
  async function readLatestConflict(){if(!conflict)return;const latest=await request<ReminderRule>('reminders.get',{ruleId:conflict.ruleId});setConflict({...conflict,latest});}
  async function deleteRule(){if(!selected)return;const current=selected;try{const r=await request<ReminderRule>('reminders.delete',{ruleId:current.id,expectedVersion:current.version});accept(r);setDeleted(true);setNotice('规则已删除，检查历史保留。');try{await loadHistory(r);}catch(e){setError('规则已删除，但检查历史读取失败：'+errorText(e)+'。可单独重试读取历史。');}}catch(e){if(isVersionConflict(e))setConflict({ruleId:current.id,local:editing,latest:null});throw e;}}
  function keepLocalConflict(){if(!conflict?.latest)return;drafts.current.set(conflict.latest.id,conflict.local);setSelected(conflict.latest);setEditing(conflict.local);setRules(prev=>[conflict.latest!,...prev.filter(x=>x.id!==conflict.latest!.id)]);setConflict(null);setNotice('已读取服务器最新版并保留本地草稿；请再次保存以提交。');}
  function useLatestConflict(){if(!conflict?.latest||!window.confirm('丢弃本条未保存的编辑并采用服务器最新版？'))return;accept(conflict.latest,true);setConflict(null);setNotice('已采用服务器最新版。');}
  async function check(){if(!selected)return;if(checkIntent.current?.ruleId!==selected.id)checkIntent.current={ruleId:selected.id,version:selected.version,id:crypto.randomUUID()};await request('reminders.check',{ruleId:selected.id,requestId:checkIntent.current.id});const r=await request<ReminderRule>('reminders.get',{ruleId:selected.id});accept(r);await loadHistory(r);checkIntent.current=null;setNotice('检查已记录；无法判断不等于未达到阈值。');}
  const inactive=selected?.status==='deleted';
  return <dialog ref={dialog} className="reminders-dialog" aria-labelledby="reminders-title" onCancel={e=>{e.preventDefault();onClose();}}>
    <header><h2 id="reminders-title">价格提醒</h2><button onClick={onClose} aria-label="关闭提醒管理">关闭</button></header>
    <div className="reminders-body"><p className="r-note">支持盘中和每日收盘两种模式。当前可保存规则和检查记录，真实行情、自动检查与通知尚未接通；程序关闭期间不监控。</p>{runtime&&<p className="r-note" role="status">{runtime.message} · <span>{runtime.running?"监控进程运行中":"监控进程未运行"}</span></p>}{runtimeError&&<p className="r-note" role="status">运行状态暂不可用：{runtimeError}</p>}
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <details><summary>创建提醒</summary><fieldset disabled={busy||!!createReceipt}><Fields value={draft} onChange={setDraft} disabled={busy}/><div className="reminder-fields"><label>提醒范围<select value={source} onChange={e=>{setSource(e.target.value);invalidate();}}><option value="single">单只沪深股票</option>{watchlists.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>{source==='single'&&<label>证券代码<input placeholder="例如 600000" value={symbol} onChange={e=>{setSymbol(e.target.value);invalidate();}}/></label>}</div><button onClick={()=>void action(preview)}>预览固定名单</button>{scope&&<section className="reminder-scope"><p>{scope.sourceWatchlist?.name||(scope.kind==='single'?'单只股票':'自选组')} · 固定名单 {scope.symbols.length} 只 · 快照生成 {scope.createdAt}</p>{scope.sourceWatchlist?.updatedAt&&<p>自选组更新时间：{scope.sourceWatchlist.updatedAt}</p>}<div>{scope.symbols.join('、')}</div><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>确认此固定名单，原自选组变化不自动修改提醒范围</label></section>}</fieldset>{createReceipt?<section className="reminder-scope" role="status"><p>提醒“{createReceipt.name}”已创建。此表单已锁定，避免重放旧创建回执。</p><div className="r-toolbar"><button disabled={busy} onClick={()=>void action(readCreatedRule)}>读取当前规则</button><button disabled={busy} onClick={startNextCreate}>新建下一条提醒</button></div></section>:scope&&<button disabled={!confirmed||busy} onClick={()=>void action(create)}>确认创建草稿</button>}</details>
    <div className="r-toolbar"><label><input type="checkbox" checked={deleted} onChange={e=>setDeleted(e.target.checked)}/>显示已删除</label><button disabled={busy} onClick={()=>void action(refreshRules)}>刷新列表</button><span>{rules.filter(r=>deleted||r.status!=='deleted').length} 条</span></div>
    <div className="reminders-columns"><nav aria-label="提醒列表">{rules.filter(r=>deleted||r.status!=='deleted').map(r=><button key={r.id} className={selected?.id===r.id?'active':''} disabled={busy} onClick={()=>void action(()=>choose(r))}><strong>{r.name}</strong><small>{names[r.status]} · {modeName(r.priceMode)} · {r.scope.symbols.length} 只</small></button>)}{!rules.length&&<p>尚无提醒，请先创建。</p>}</nav>
    <section>{selected?<><h3>{selected.name} · v{selected.version}</h3><p>{names[selected.status]} · {modeName(selected.priceMode)} · {selected.scope.sourceWatchlist?.name||(selected.scope.kind==='single'?'单只股票':'自选组')}</p><details><summary>查看固定名单（{selected.scope.symbols.length} 只）</summary><p className="reminder-scope">{selected.scope.symbols.join('、')}</p><small>快照创建：{selected.scope.createdAt} · 名单确认：{selected.scope.confirmedAt||'未提供'}{selected.scope.sourceWatchlist?.updatedAt&&' · 自选组更新时间：'+selected.scope.sourceWatchlist.updatedAt}</small></details><Fields value={editing} onChange={editCurrent} disabled={busy||inactive}/>{conflict&&conflict.ruleId===selected.id&&<aside className="reminder-conflict" role="alert"><p>服务器提示规则版本已变化。本地未保存草稿已保留，请读取最新版后选择如何继续。</p>{!conflict.latest?<button disabled={busy} onClick={()=>void action(readLatestConflict)}>读取服务器最新版</button>:<><button disabled={busy} onClick={useLatestConflict}>采用最新版并丢弃本地编辑</button><button disabled={busy} onClick={keepLocalConflict}>保留本地草稿并基于最新版重新保存</button></>}</aside>}{!inactive&&<div className="r-toolbar"><button disabled={busy} onClick={()=>void action(()=>update())}>保存修改</button><button disabled={busy} onClick={()=>void action(()=>update(selected.status==='paused'?'draft':'paused'))}>{selected.status==='paused'?'返回草稿':selected.status==='draft'?'暂停草稿':'暂停规则'}</button><button disabled={busy} onClick={()=>void action(check)}>检查可用性</button><button disabled={busy} onClick={()=>setRemove(!remove)}>删除规则</button></div>}
    <button disabled={busy} onClick={()=>{if(window.confirm('重新读取将丢弃此提醒尚未保存的编辑，继续？'))void action(reloadSelected);}}>重新读取此规则</button>
    {remove&&!inactive&&<p>删除后停止检查，历史保留。<button disabled={busy} onClick={()=>void action(deleteRule)}>确认删除</button><button onClick={()=>setRemove(false)}>取消删除</button></p>}
    <div className="r-toolbar"><h3>检查历史</h3><button disabled={busy} onClick={()=>void action(()=>loadHistory(selected,offset))}>刷新检查历史</button></div>{!history&&<p>历史尚未加载，请刷新重试。</p>}{history?.items.map(h=><details key={h.id}><summary>{h.checkedAt} · {h.origin==='manual'?'人工检查':'定时检查'} · 规则 v{h.ruleVersion} · {h.rows.length} 只</summary>{h.rows.map(row=><p key={row.symbol}><strong>{row.symbol} · {names[row.result]||'无法判断'}</strong><br/>{row.reasonCodes.length?row.reasonCodes.map(reasonName).join('；'):row.result==='unknown'?'未提供原因说明':''}{row.observation.price!==null&&' · '+row.observation.price+' 元 · 未复权原始价'}<br/><small>观察类型：{row.observation.kind==='last_trade'?'最新成交价':row.observation.kind==='minute_close'?'分钟收盘价':row.observation.kind==='daily_close'?'日收盘价':row.observation.kind||'未提供'} · 来源：{row.observation.source?.provider||'未提供'} / {row.observation.source?.endpoint||'未提供'} · 来源时间：{row.observation.sourceTime||'未提供'} · 交易日：{row.observation.sourceTradeDate||'未提供'} · 获取时间：{row.observation.fetchedAt||'未提供'} · {row.observation.validity==='valid'?'有效':'无法验证'} · {row.notified?'记录标记已通知':'没有通知记录'}</small></p>)}</details>)}{history&&!history.total&&<p>暂无检查记录。</p>}{history&&<div className="r-toolbar"><button disabled={busy||!offset} onClick={()=>void action(()=>loadHistory(selected,Math.max(0,offset-10)))}>上一页记录</button><span>{history.total?`${offset+1}–${offset+history.items.length} / ${history.total}`:'0 条'}</span><button disabled={busy||offset+history.items.length>=history.total} onClick={()=>void action(()=>loadHistory(selected,offset+10))}>下一页记录</button></div>}</>:<p>选择一条提醒查看规则与历史。</p>}</section></div></div>
  </dialog>;
}
