import React, { useEffect, useRef, useState } from 'react';
import type { ReminderRule, ReminderScopeSnapshot, ReminderHistoryPage, ReminderCheck, ReminderPriceMode, ReminderRuntime, Watchlist } from '../../../../../packages/contracts/src/research';
import { request, errorText } from './state';
import './reminders.css';
const names: Record<string,string> = { draft:'草稿', paused:'已暂停', enabled:'已启用', deleted:'已删除', mode_pending:'尚未选择价格模式', source_unavailable:'真实行情来源尚未接入', unknown:'无法判断', triggered:'触发', not_triggered:'未触发' };
const reasonNames:Record<string,string>={source_unavailable:'行情来源不可用或仍为离线文件配置',missing_price:'来源未返回价格',invalid_observation:'观察数据无效',invalid_price:'价格无效或非正数',missing_provenance:'缺少原始行情来源凭据',missing_source_time:'缺少行情来源时间',calendar_missing:'交易日历缺失或日期未覆盖',market_closed:'当前休市或不在交易时段',period_incomplete:'当前分钟/收盘周期尚未完成',source_not_published:'行情来源尚未发布该时段数据',source_timeout:'单证券行情查询超时',check_budget_exhausted:'本轮查询预算用尽，范围尾部留待后续轮次',source_error:'行情来源查询失败',identity_mismatch:'行情证券代码与请求不匹配',trading_status_unknown:'交易状态无法确认',suspended:'证券停牌',stale:'行情过期或不属于目标交易日',future_time:'行情来源时间晚于检查时间',cancelled:'检查因服务停止而取消',mode_pending:'尚未选择价格模式',rule_changed:'检查期间规则版本或状态已变化',startup_baseline:'服务启动基线观察，不作为触发',duplicate_observation:'重复观察记录，未重复触发',duplicate_observation_time:'观察时间重复，未重复触发',out_of_order:'观察时间早于已处理记录'};
const reasonName=(code:string)=>code==='请选择价格提醒口径'?'尚未选择价格模式':reasonNames[code]??names[code]??('未知原因（代码：'+code+'）');
const modeName = (v: string | null) => v === 'intraday' ? '盘中' : v === 'daily_close' ? '每日收盘' : '尚未选择';function mergeRulesMonotonic(current:ReminderRule[],incoming:ReminderRule[]){const byId=new Map(current.map(rule=>[rule.id,rule] as const));const order:string[]=[];for(const rule of incoming){if(!order.includes(rule.id))order.push(rule.id);const prior=byId.get(rule.id);const priorTime=Date.parse(prior?.lastCheckAt??'')||0;const nextTime=Date.parse(rule.lastCheckAt??'')||0;if(!prior||rule.version>prior.version||(rule.version===prior.version&&nextTime>=priorTime))byId.set(rule.id,rule);}for(const rule of current)if(!order.includes(rule.id))order.push(rule.id);return order.map(id=>byId.get(id)!);}
function latestConflictDraft(conflict:{ruleId:string;local:Draft},selectedId:string|undefined,editing:Draft,drafts:Map<string,Draft>){return selectedId===conflict.ruleId?editing:(drafts.get(conflict.ruleId)??conflict.local);}
function historyContainsCheck(page:ReminderHistoryPage,id:string){return page.items.some(item=>item.id===id);}
function newerRuleSnapshot(a:ReminderRule,b:ReminderRule){return mergeRulesMonotonic([a],[b])[0];}
type Draft = { name:string; threshold:string; operator:'gte'|'lte'; priceMode:ReminderPriceMode|'' };
const fresh = ():Draft => ({name:'价格提醒',threshold:'',operator:'gte',priceMode:''});
const ofRule = (r:ReminderRule):Draft => ({name:r.name,threshold:String(r.condition.threshold),operator:r.condition.operator,priceMode:r.priceMode || ''});
function Fields({value,onChange,disabled}:{value:Draft;onChange:(v:Draft)=>void;disabled:boolean}) {
  return <div className="reminder-fields"><label>提醒名称<input value={value.name} disabled={disabled} onChange={e=>onChange({...value,name:e.target.value})}/></label><label>价格模式<select value={value.priceMode} disabled={disabled} onChange={e=>onChange({...value,priceMode:e.target.value as Draft['priceMode']})}><option value="">请选择</option><option value="intraday">盘中（已完成分钟收盘）</option><option value="daily_close">每日收盘</option></select></label><label>触发条件<select value={value.operator} disabled={disabled} onChange={e=>onChange({...value,operator:e.target.value as Draft['operator']})}><option value="gte">价格大于等于</option><option value="lte">价格小于等于</option></select></label><label>价格阈值（元）<input type="number" min="0" step="any" value={value.threshold} disabled={disabled} onChange={e=>onChange({...value,threshold:e.target.value})}/></label></div>;
}
function condition(d:Draft) { const threshold=Number(d.threshold); if(!d.name.trim()||!Number.isFinite(threshold)||threshold<=0) throw new Error('请填写名称和大于零的价格阈值'); return {operator:d.operator,threshold}; }
function CheckRows({rows}:{rows:ReminderCheck['rows']}){return <>{rows.map(row=><p key={row.symbol}><strong>{row.symbol} · {names[row.result]||'无法判断'}</strong><br/>{row.reasonCodes.length?row.reasonCodes.map(reasonName).join('；'):row.result==='unknown'?'未提供原因说明':''}{row.observation.price!==null&&' · '+row.observation.price+' 元 · 未复权原始价'}<br/><small>观察类型：{row.observation.kind==='last_trade'?'最新成交价':row.observation.kind==='minute_close'?'分钟收盘价':row.observation.kind==='daily_close'?'日收盘价':row.observation.kind||'未提供'} · 来源：{row.observation.source?.provider||'未提供'} / {row.observation.source?.endpoint||'未提供'} · 来源时间：{row.observation.sourceTime||'未提供'} · 交易日：{row.observation.sourceTradeDate||'未提供'} · 获取时间：{row.observation.fetchedAt||'未提供'} · {row.observation.validity==='valid'?'有效':'无法验证'} · 通知尚未接入（后端通知标志：{row.notified?'已标记':'未标记'}，不代表实际送达）</small></p>)}</>;}export function RemindersManagement({open,onClose,watchlists}:{open:boolean;onClose:()=>void;watchlists:Watchlist[]}) {
  const dialog=useRef<HTMLDialogElement>(null);
  const [rules,setRules]=useState<ReminderRule[]>([]),[deleted,setDeleted]=useState(false),[selected,setSelected]=useState<ReminderRule|null>(null);
  const [draft,setDraft]=useState<Draft>(fresh),[editing,setEditing]=useState<Draft>(fresh);
  const [source,setSource]=useState('single'),[symbol,setSymbol]=useState(''),[scope,setScope]=useState<ReminderScopeSnapshot|null>(null),[confirmed,setConfirmed]=useState(false);
  const [history,setHistory]=useState<ReminderHistoryPage|null>(null),[checkResult,setCheckResult]=useState<ReminderCheck|null>(null),[checkHistoryFresh,setCheckHistoryFresh]=useState(false),[offset,setOffset]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[remove,setRemove]=useState(false),[checking,setChecking]=useState(false),[checkMessage,setCheckMessage]=useState('');
  const [runtime,setRuntime]=useState<ReminderRuntime|null>(null),[runtimeError,setRuntimeError]=useState(''),[conflict,setConflict]=useState<{ruleId:string;local:Draft;latest:ReminderRule|null}|null>(null),[createReceipt,setCreateReceipt]=useState<Pick<ReminderRule,'id'|'name'>|null>(null);
  const lock=useRef(false),generation=useRef(0),rulesRevision=useRef(0),selectionGeneration=useRef(0),checkLock=useRef(false),pollLock=useRef(false),selectedRef=useRef<ReminderRule|null>(null),editingRef=useRef<Draft>(editing),historyRef=useRef<ReminderHistoryPage|null>(null),openRef=useRef(open),offsetRef=useRef(offset),rulesRef=useRef(rules),conflictRef=useRef(conflict),createIntent=useRef<{key:string;id:string}|null>(null),checkIntent=useRef<{ruleId:string;version:number;id:string}|null>(null),drafts=useRef<Map<string,Draft>>(new Map());
  selectedRef.current=selected;editingRef.current=editing;historyRef.current=history;openRef.current=open;offsetRef.current=offset;rulesRef.current=rules;conflictRef.current=conflict;
  useEffect(()=>{ if(open&&!dialog.current?.open)dialog.current?.showModal(); if(!open&&dialog.current?.open)dialog.current?.close(); },[open]);
  useEffect(()=>()=>{generation.current++;},[]);
  useEffect(()=>{if(!open)return;let alive=true;let timer:number|undefined;const poll=async()=>{if(!alive)return;if(pollLock.current){timer=window.setTimeout(()=>void poll(),6000);return;}pollLock.current=true;const revisionAtStart=rulesRevision.current;try{const incoming=await request<ReminderRule[]>('reminders.list',{includeDeleted:true});if(!alive)return;setRules(previous=>mergeRulesMonotonic(previous,incoming));const currentRuntime=await request<ReminderRuntime>('reminders.runtime');if(!alive)return;setRuntime(currentRuntime);setRuntimeError('');const current=selectedRef.current;if(current){let historyRule=current;const candidate=incoming.find(rule=>rule.id===current.id);if(candidate&&revisionAtStart===rulesRevision.current){const knownConflict=conflictRef.current?.ruleId===current.id?conflictRef.current.latest:null;const knownList=rulesRef.current.find(rule=>rule.id===current.id);let base=knownList?newerRuleSnapshot(current,knownList):current;if(knownConflict)base=newerRuleSnapshot(base,knownConflict);const latest=newerRuleSnapshot(base,candidate);historyRule=latest;setRules(previous=>mergeRulesMonotonic(previous,[latest]));if(latest.version===current.version){if(latest.lastCheckAt!==current.lastCheckAt)setSelected(latest);}else if(latest.version>current.version){const local=latestConflictDraft({ruleId:latest.id,local:editingRef.current},current.id,editingRef.current,drafts.current);const dirty=JSON.stringify(local)!==JSON.stringify(ofRule(current));if(!dirty){rulesRevision.current++;selectionGeneration.current++;setSelected(latest);setEditing(ofRule(latest));drafts.current.set(latest.id,ofRule(latest));if(latest.status==='deleted')setDeleted(true);setConflict(previous=>previous?.ruleId===latest.id?null:previous);}else setConflict(previous=>previous?.ruleId===latest.id?{...previous,local,latest:previous.latest&&previous.latest.version>latest.version?previous.latest:latest}:{ruleId:latest.id,local,latest});}}await loadHistory(historyRule,offsetRef.current);}}catch(e){if(alive)setRuntimeError('提醒列表、运行状态或历史刷新失败：'+errorText(e));}finally{pollLock.current=false;if(alive)timer=window.setTimeout(()=>void poll(),6000);}};void poll();return()=>{alive=false;if(timer!==undefined)window.clearTimeout(timer);generation.current++;};},[open]);
  async function action(fn:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await fn();}catch(e){setError(errorText(e));}finally{lock.current=false;setBusy(false);}}
  async function refreshRules(){if(pollLock.current)return;pollLock.current=true;try{const incoming=await request<ReminderRule[]>('reminders.list',{includeDeleted:true});setRules(previous=>mergeRulesMonotonic(previous,incoming));try{setRuntime(await request<ReminderRuntime>('reminders.runtime'));setRuntimeError('');}catch(e){setRuntimeError(errorText(e));}}finally{pollLock.current=false;}}
  async function loadHistory(r:ReminderRule,page=0){const seq=++generation.current;const result=await request<ReminderHistoryPage>('reminders.history',{ruleId:r.id,offset:page,limit:10});if(seq===generation.current&&openRef.current){setHistory(result);setOffset(page);setCheckHistoryFresh(true);setCheckResult(previous=>previous&&historyContainsCheck(result,previous.id)?null:previous);}}
  function accept(r:ReminderRule,replaceDraft=false,preserveSelection=false){const previousSelected=selectedRef.current;const listRule=rulesRef.current.find(rule=>rule.id===r.id);const known=previousSelected?.id===r.id?newerRuleSnapshot(previousSelected,listRule??previousSelected):(listRule??r);const chosen=newerRuleSnapshot(known,r);if(previousSelected&&previousSelected.id!==chosen.id)drafts.current.set(previousSelected.id,editingRef.current);const next=replaceDraft?ofRule(chosen):(previousSelected?.id===chosen.id?editingRef.current:(drafts.current.get(chosen.id)??ofRule(chosen)));drafts.current.set(chosen.id,next);rulesRevision.current++;if(!preserveSelection)selectionGeneration.current++;setSelected(chosen);setEditing(next);setRemove(false);setRules(prev=>mergeRulesMonotonic(prev,[chosen]));if(replaceDraft&&chosen.version===r.version)setConflict(null);}
  function editCurrent(next:Draft){setEditing(next);rulesRevision.current++;if(selected){drafts.current.set(selected.id,next);setConflict(previous=>previous?.ruleId===selected.id?{...previous,local:next}:previous);}}
  async function choose(r:ReminderRule){accept(r);setHistory(null);setCheckResult(null);setCheckHistoryFresh(false);setCheckMessage('');const current=selectedRef.current;await loadHistory(current?.id===r.id&&current.version>r.version?current:r);}
  function invalidate(){setScope(null);setConfirmed(false);createIntent.current=null;}
  async function preview(){const result=await request<ReminderScopeSnapshot>('reminders.scope.preview',source==='single'?{symbol}:{watchlistId:source});setScope(result);setConfirmed(false);createIntent.current=null;}
  async function acceptCurrentRule(ruleId:string){setCheckMessage('');setCheckResult(null);setCheckHistoryFresh(false);const current=await request<ReminderRule>('reminders.get',{ruleId});accept(current,true);setHistory(null);if(current.status==='deleted')setDeleted(true);return current;}
  async function create(){if(createReceipt)throw new Error('此提醒已创建，请读取当前规则或选择新建下一条。');if(!scope||!confirmed)throw new Error('请先预览并确认固定名单');if(!draft.priceMode)throw new Error('请选择价格模式后再创建。');const intent={name:draft.name.trim(),snapshotId:scope.id,condition:condition(draft),priceMode:draft.priceMode};const key=JSON.stringify(intent);if(createIntent.current?.key!==key)createIntent.current={key,id:crypto.randomUUID()};const receipt=await request<ReminderRule>('reminders.create',{...intent,requestId:createIntent.current.id});setCreateReceipt({id:receipt.id,name:receipt.name});setNotice('提醒“'+receipt.name+'”已收到创建成功回执，正在读取服务器当前状态。');try{const current=await acceptCurrentRule(receipt.id);setNotice('提醒已创建；当前规则为'+names[current.status]+' · v'+current.version+'。');try{await loadHistory(current);}catch(e){setError('当前规则已读取，但检查历史读取失败：'+errorText(e)+'。可单独重试。');}}catch(e){setError('提醒已创建，但读取当前规则失败：'+errorText(e));setNotice('提醒“'+receipt.name+'”创建成功；当前状态尚未读取，可单独重试读取当前规则。');}}
  function startNextCreate(){setCreateReceipt(null);createIntent.current=null;setDraft(fresh());setSource('single');setSymbol('');setScope(null);setConfirmed(false);setError('');setNotice('请重新预览固定名单后创建下一条提醒。');}
  async function readCreatedRule(){if(!createReceipt)return;const current=await acceptCurrentRule(createReceipt.id);try{await loadHistory(current);}catch(e){setError('当前规则已读取，但检查历史读取失败：'+errorText(e)+'。可单独重试。');}setNotice('已读取服务器中的当前规则版本：'+names[current.status]+' · v'+current.version+'。');}
  async function reloadSelected(){if(!selected)return;const latest=await request<ReminderRule>('reminders.get',{ruleId:selected.id});accept(latest,true);setHistory(null);try{await loadHistory(latest);}catch(e){setError('规则已重新读取，但检查历史读取失败：'+errorText(e)+'。可单独重试。');}setNotice('已读取服务器最新版；本地未保存编辑已丢弃。');}
  function isVersionConflict(e:unknown){const message=errorText(e).toLowerCase();return message.includes('version_conflict')||message.includes('version conflict')||message.includes('expectedversion')||message.includes('版本冲突')||message.includes('版本已更新');}
  async function update(){if(!selected)return;if(!editing.priceMode)throw new Error('请先选择盘中或每日收盘价格模式，再保存。');drafts.current.set(selected.id,editing);try{const r=await request<ReminderRule>('reminders.update',{ruleId:selected.id,expectedVersion:selected.version,name:editing.name.trim(),condition:condition(editing),priceMode:editing.priceMode});accept(r,true);setNotice('已保存；规则仍为'+names[r.status]+'，保存不会启用监控。');}catch(e){if(isVersionConflict(e))recordConflict(selected.id,editing);throw e;}}
  function recordConflict(ruleId:string,fallback:Draft){const local=latestConflictDraft({ruleId,local:fallback},selectedRef.current?.id,editingRef.current,drafts.current);setConflict(previous=>previous?.ruleId===ruleId?{...previous,local,latest:previous.latest}:{ruleId,local,latest:null});}
  async function readLatestConflict(){if(!conflict)return;const ruleId=conflict.ruleId;const latest=await request<ReminderRule>('reminders.get',{ruleId});rulesRevision.current++;setRules(previous=>mergeRulesMonotonic(previous,[latest]));setConflict(previous=>{if(previous?.ruleId!==ruleId)return previous;const local=latestConflictDraft(previous,selectedRef.current?.id,editingRef.current,drafts.current);const currentLatest=previous.latest&&previous.latest.version>latest.version?previous.latest:latest;return {...previous,local,latest:currentLatest};});}  async function changeStatus(status:'enabled'|'paused'){const rule=selectedRef.current;if(!rule)return;if(status==='enabled'){if(!rule.priceMode)throw new Error('请先选择价格模式并保存，再启用规则。');const scopeName=rule.scope.sourceWatchlist?.name??(rule.scope.kind==='single'?'单只股票':'固定自选快照');const explanation=`启用“${rule.name}”的已保存规则？价格模式：${modeName(rule.priceMode)}；固定名单：${scopeName}，${rule.scope.symbols.length}只（明细见页面固定名单）。仅本程序运行期间，由单个串行worker约每分钟启动检查。盘中使用已完成分钟K线收盘价，不是逐笔；每轮最多60秒内开始查询，大名单会分轮继续。通知尚未实现。`;if(!window.confirm(explanation))return;}const local=editingRef.current;try{const next=await request<ReminderRule>('reminders.update',{ruleId:rule.id,expectedVersion:rule.version,status});accept(next);setConflict(previous=>previous?.ruleId===rule.id?null:previous);setNotice(status==='enabled'?'规则已明确启用；这只改变已保存规则的运行状态，不提交编辑器中未保存的条件。':'规则已暂停；这只改变运行状态，未保存的条件草稿仍保留。');}catch(e){if(isVersionConflict(e))recordConflict(rule.id,local);throw e;}}
  async function deleteRule(){if(!selected)return;const current=selected;try{const r=await request<ReminderRule>('reminders.delete',{ruleId:current.id,expectedVersion:current.version});accept(r);setDeleted(true);setNotice('规则已删除，检查历史保留。');try{await loadHistory(r);}catch(e){setError('规则已删除，但检查历史读取失败：'+errorText(e)+'。可单独重试读取历史。');}}catch(e){if(isVersionConflict(e))recordConflict(current.id,editing);throw e;}}
  function keepLocalConflict(){const current=conflictRef.current;if(!current?.latest)return;const local=latestConflictDraft(current,selectedRef.current?.id,editingRef.current,drafts.current);const listed=rulesRef.current.find(rule=>rule.id===current.ruleId);const selectedNow=selectedRef.current?.id===current.ruleId?selectedRef.current:null;let latest=current.latest;if(listed)latest=newerRuleSnapshot(latest,listed);if(selectedNow)latest=newerRuleSnapshot(latest,selectedNow);drafts.current.set(latest.id,local);rulesRevision.current++;selectionGeneration.current++;setSelected(latest);setEditing(local);if(latest.status==='deleted')setDeleted(true);setRules(prev=>mergeRulesMonotonic(prev,[latest]));setConflict(null);setNotice('已读取服务器最新版并保留本地最新草稿；请再次保存以提交。');}
  function useLatestConflict(){if(!conflict?.latest||!window.confirm('丢弃本条未保存的编辑并采用服务器最新版？'))return;accept(conflict.latest,true);if(conflict.latest.status==='deleted')setDeleted(true);setConflict(null);setNotice('已采用服务器最新版。');}
  async function check(){
    const rule=selectedRef.current;if(!rule||checkLock.current||lock.current)return;
    if(checkIntent.current?.ruleId!==rule.id)checkIntent.current={ruleId:rule.id,version:rule.version,id:crypto.randomUUID()};
    const requestId=checkIntent.current.id,epoch=selectionGeneration.current;checkLock.current=true;setChecking(true);
    setCheckMessage(`正在提交固定名单 ${rule.scope.symbols.length} 只证券的人工检查；worker串行查询，服务端不提供逐股实时进度。`);setError('');
    const sameSelection=()=>openRef.current&&selectedRef.current?.id===rule.id;
    try{
      const record=await request<ReminderCheck>('reminders.check',{ruleId:rule.id,requestId});checkIntent.current=null;
      if(sameSelection()){generation.current++;setCheckResult(record);setCheckHistoryFresh(false);setCheckMessage(`检查完成：${record.rows.length} 只；触发 ${record.rows.filter(row=>row.result==='triggered').length} 只，未触发 ${record.rows.filter(row=>row.result==='not_triggered').length} 只，无法判断 ${record.rows.filter(row=>row.result==='unknown').length} 只。触发记录不代表通知已发送。`);}
      try{
        const received=await request<ReminderRule>('reminders.get',{ruleId:rule.id});
        const knownConflict=conflictRef.current?.ruleId===rule.id?conflictRef.current.latest:null;
        const latest=knownConflict?newerRuleSnapshot(received,knownConflict):received;
        if(sameSelection()&&selectedRef.current?.version===rule.version){
          if(selectionGeneration.current===epoch&&latest.version===rule.version&&latest.status===rule.status){rulesRevision.current++;setSelected(newerRuleSnapshot(selectedRef.current,latest));setRules(previous=>mergeRulesMonotonic(previous,[latest]));}
          else if(latest.version!==rule.version){
            const local=latestConflictDraft({ruleId:rule.id,local:editingRef.current},selectedRef.current?.id,editingRef.current,drafts.current);
            const dirty=JSON.stringify(local)!==JSON.stringify(ofRule(rule));rulesRevision.current++;
            if(dirty)setConflict(previous=>previous?.ruleId===latest.id?{...previous,local,latest:previous.latest&&previous.latest.version>latest.version?previous.latest:latest}:{ruleId:latest.id,local,latest});
            else{selectionGeneration.current++;setSelected(latest);setEditing(ofRule(latest));drafts.current.set(latest.id,ofRule(latest));setRules(previous=>mergeRulesMonotonic(previous,[latest]));if(latest.status==='deleted')setDeleted(true);}
          }
        }
        if(sameSelection())try{await loadHistory(latest,0);}catch(e){setError('检查结果已返回；历史列表刷新失败：'+errorText(e)+'。本次结果暂存展示，分页总数尚未据此更新。');}
      }catch(e){setCheckMessage('检查结果已保存；读取规则当前状态失败：'+errorText(e));}
    }catch(e){setError(errorText(e));setCheckMessage('人工检查未能确认成功，可重试；重试会沿用同一请求标识。');}
    finally{checkLock.current=false;setChecking(false);}
  }  const inactive=selected?.status==='deleted';const editorDirty=!!selected&&JSON.stringify(editing)!==JSON.stringify(ofRule(selected));
  return <dialog ref={dialog} className="reminders-dialog" aria-labelledby="reminders-title" onCancel={e=>{e.preventDefault();onClose();}}>
    <header><h2 id="reminders-title">价格提醒</h2><button onClick={onClose} aria-label="关闭提醒管理">关闭</button></header>
    <div className="reminders-body"><p className="r-note">自动检查只对明确启用的规则运行，且仅在本程序运行期间。检查由单个串行worker调度，约每分钟尝试启动；单轮最多60秒开始查询，大名单跨轮继续，不能保证每只股票每分钟都检查。盘中口径为已完成分钟K线收盘价，不是逐笔。通知尚未实现。</p>{runtime&&<p className="r-note" role="status">{runtime.message} · 调度服务状态：{runtime.running?'运行中':'暂停或未运行'} · 最近一次检查：{runtime.lastCheckAt||'尚未检查'}</p>}{runtimeError&&<p className="r-note" role="status">刷新提示：{runtimeError}</p>}
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <details><summary>创建提醒</summary><fieldset disabled={busy||checking||!!createReceipt}><Fields value={draft} onChange={setDraft} disabled={busy}/><div className="reminder-fields"><label>提醒范围<select value={source} onChange={e=>{setSource(e.target.value);invalidate();}}><option value="single">单只沪深股票</option>{watchlists.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label>{source==='single'&&<label>证券代码<input placeholder="例如 600000" value={symbol} onChange={e=>{setSymbol(e.target.value);invalidate();}}/></label>}</div><button onClick={()=>void action(preview)}>预览固定名单</button>{scope&&<section className="reminder-scope"><p>{scope.sourceWatchlist?.name||(scope.kind==='single'?'单只股票':'自选组')} · 固定名单 {scope.symbols.length} 只 · 快照生成 {scope.createdAt}</p>{scope.sourceWatchlist?.updatedAt&&<p>自选组更新时间：{scope.sourceWatchlist.updatedAt}</p>}<div>{scope.symbols.join('、')}</div><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>确认此固定名单，原自选组变化不自动修改提醒范围</label></section>}</fieldset>{createReceipt?<section className="reminder-scope" role="status"><p>提醒“{createReceipt.name}”已创建。此表单已锁定，避免重放旧创建回执。</p><div className="r-toolbar"><button disabled={busy||checking} onClick={()=>void action(readCreatedRule)}>读取当前规则</button><button disabled={busy} onClick={startNextCreate}>新建下一条提醒</button></div></section>:scope&&<button disabled={!confirmed||busy||checking||!draft.priceMode} onClick={()=>void action(create)}>确认创建草稿</button>}</details>
    <div className="r-toolbar"><label><input type="checkbox" checked={deleted} onChange={e=>setDeleted(e.target.checked)}/>显示已删除</label><button disabled={busy} onClick={()=>void action(refreshRules)}>刷新列表</button><span>{rules.filter(r=>deleted||r.status!=='deleted').length} 条</span></div>
    <div className="reminders-columns"><nav aria-label="提醒列表">{rules.filter(r=>deleted||r.status!=='deleted').map(r=><button key={r.id} className={selected?.id===r.id?'active':''} disabled={busy||checking} onClick={()=>void action(()=>choose(r))}><strong>{r.name}</strong><small>{names[r.status]} · {modeName(r.priceMode)} · {r.scope.symbols.length} 只</small></button>)}{!rules.filter(r=>deleted||r.status!=='deleted').length&&<p>{deleted?'尚无提醒记录。':'当前无可见提醒；可勾选“显示已删除”查看历史规则。'}</p>}</nav>
    <section>{selected?<><h3>{selected.name} · v{selected.version}</h3><p>规则状态：{names[selected.status]} · 已保存口径：{modeName(selected.priceMode)} · {selected.scope.sourceWatchlist?.name||(selected.scope.kind==='single'?'单只股票':'自选组')}</p>{selected.unavailableReason&&<p className="r-note">最近不可用原因：{selected.unavailableReason.split('；').map(reasonName).join('；')}</p>}<details><summary>查看固定名单（{selected.scope.symbols.length} 只）</summary><p className="reminder-scope">{selected.scope.symbols.join('、')}</p><small>快照创建：{selected.scope.createdAt} · 名单确认：{selected.scope.confirmedAt||'未提供'}{selected.scope.sourceWatchlist?.updatedAt&&' · 自选组更新时间：'+selected.scope.sourceWatchlist.updatedAt}</small></details><Fields value={editing} onChange={editCurrent} disabled={busy||inactive}/>{editorDirty&&!inactive&&<p className="r-note">有未保存修改。保存只写入编辑内容且不会启用；启用或暂停只切换当前已保存规则，不提交这些修改。</p>}{conflict&&conflict.ruleId===selected.id&&<aside className="reminder-conflict" role="alert"><p>服务器提示规则版本已变化。本地未保存草稿已保留，请读取最新版后选择如何继续。</p>{!conflict.latest?<button disabled={busy} onClick={()=>void action(readLatestConflict)}>读取服务器最新版</button>:<><button disabled={busy} onClick={useLatestConflict}>采用最新版并丢弃本地编辑</button><button disabled={busy} onClick={keepLocalConflict}>保留本地草稿并基于最新版重新保存</button></>}</aside>}{!inactive&&<div className="r-toolbar"><button disabled={busy||checking} onClick={()=>void action(update)}>保存修改</button>{selected.status==='enabled'?<button disabled={busy} onClick={()=>void action(()=>changeStatus('paused'))}>暂停规则</button>:<button disabled={busy||checking||!selected.priceMode} title={!selected.priceMode?'先选择价格模式并保存':'明确启用已保存规则'} onClick={()=>void action(()=>changeStatus('enabled'))}>{selected.status==='paused'?'恢复并启用':'明确启用规则'}</button>}<button disabled={busy||checking} onClick={()=>void check()}>{checking?'正在检查…':'立即人工检查'}</button><button disabled={busy||checking} onClick={()=>setRemove(!remove)}>删除规则</button></div>}
{selected.priceMode===null&&!inactive&&<p className="r-note">此旧规则尚无价格模式。先选择盘中或每日收盘并保存，之后才能启用。</p>}{checking&&<p className="r-check-progress" role="status" aria-live="polite" aria-busy="true">{checkMessage}</p>}{!checking&&checkMessage&&<p className="r-note" role="status" aria-live="polite">{checkMessage}</p>}
    <button disabled={busy} onClick={()=>{if(window.confirm('重新读取将丢弃此提醒尚未保存的编辑，继续？'))void action(reloadSelected);}}>重新读取此规则</button>
    {remove&&!inactive&&<p>删除后停止检查，历史保留。<button disabled={busy||checking} onClick={()=>void action(deleteRule)}>确认删除</button><button onClick={()=>setRemove(false)}>取消删除</button></p>}
    {checkResult&&checkResult.ruleId===selected.id&&<section className="reminder-scope"><h4>本次人工检查结果 · {checkResult.checkedAt}</h4><p>{checkHistoryFresh?'历史已从服务端读取，分页总数为服务端返回值；如果本条不在当前页，可在最近记录页查看。':'本次结果暂存展示，历史未刷新；分页总数仍是上次成功读取值，尚未确认本次是否计入。'}</p><CheckRows rows={checkResult.rows}/></section>}<div className="r-toolbar"><h3>检查历史</h3><button disabled={busy} onClick={()=>void action(()=>loadHistory(selected,offset))}>刷新检查历史</button></div>{!history&&<p>历史尚未加载，请刷新重试。</p>}{history?.items.map(h=><details key={h.id}><summary>{h.checkedAt} · {h.origin==='manual'?'人工检查':'定时检查'} · 规则 v{h.ruleVersion} · {h.rows.length} 只</summary><CheckRows rows={h.rows}/></details>)}{history&&!history.total&&<p>暂无检查记录。</p>}{history&&<div className="r-toolbar"><button disabled={busy||!offset} onClick={()=>void action(()=>loadHistory(selected,Math.max(0,offset-10)))}>上一页记录</button><span>{history.total?`${offset+1}–${offset+history.items.length} / ${history.total}`:'0 条'}</span><button disabled={busy||offset+history.items.length>=history.total} onClick={()=>void action(()=>loadHistory(selected,offset+10))}>下一页记录</button></div>}</>:<p>选择一条提醒查看规则与历史。</p>}</section></div></div>
  </dialog>;
}
