import React, { useEffect, useState } from "react";
import type { JsonObject, UniverseConfig } from "../../../../../packages/contracts/src/research";
import { request, useResearch } from "./state";
import { CodeEditor, DataTable, Empty, Field, Heading } from "./ui";

import { object, factorProcessing, FactorProcessingEditor, NumberSetting, ChoiceSetting } from "./configuration";

export function Overview() {
  const s = useResearch(); const p = s.project!;
  const [objective, setObjective] = useState(p.objective);
  const [editing, setEditing] = useState(false);
  return <div className="r-page"><Heading title={p.name} description={p.objective || "为这个项目写下一个可检验的研究问题。"}><span className="r-tag">A 股 · 日线</span></Heading>
    <section className="r-objective"><h3>研究目标</h3>{editing ? <><textarea aria-label="研究目标" value={objective} onChange={e => setObjective(e.target.value)} /><div className="r-toolbar"><button className="r-primary" onClick={() => void s.act(async () => { await s.save({ objective }); setEditing(false); })}>保存目标</button><button onClick={() => setEditing(false)}>取消</button></div></> : <><p>{p.objective || "尚未设置研究目标"}</p><div className="r-meta"><span>股票池：{p.universe.name}</span><span>{p.startDate || "未设置开始日期"} — {p.endDate || "未设置结束日期"}</span></div><div className="r-toolbar"><button className="r-primary" onClick={() => s.setPage("factors")}>继续因子研究 →</button><button onClick={() => { setObjective(p.objective); setEditing(true); }}>编辑研究目标</button><button onClick={() => s.setPage("results")}>查看实验</button></div></>}</section>
    <section><h2>研究入口</h2><div className="r-entry-row">{([ ["data", "数据准备"], ["universe", "股票池"], ["factors", "因子分析"], ["backtest", "策略回测"], ["model", "模型训练"], ["selection", "每日选股"] ] as const).map(([page, label], i) => <button key={page} onClick={() => s.setPage(page)}><span className="r-entry-number">0{i + 1}</span>{label}<span>→</span></button>)}</div></section>
    <section><div className="r-toolbar"><h2>最近实验</h2><span>{s.experiments.length} 个实验</span></div>{!s.experiments.length ? <Empty title="让第一个实验回答你的问题">准备数据、选择股票池与因子后，运行一次分析。结果会保存在这个项目中。</Empty> : <div className="r-experiment-list">{s.experiments.slice(0, 6).map(e => <button key={e.id} onClick={() => { s.setSelectedExperiment(e.id); s.setPage("results"); }}><strong>{e.starred ? "★ " : ""}{e.name}</strong><span>{e.summary}</span><time>{new Date(e.createdAt).toLocaleString("zh-CN")}</time><span>查看 →</span></button>)}</div>}</section>
  </div>;
}
interface Preview { datasets: { name: string; rows: number; symbols: number; startDate: string; endDate: string; columns: string[]; missingValues?: number }[]; rows: JsonObject[]; warnings?: string[] }
export function DataPanel() {
  const s = useResearch(); const p = s.project!;
  const [preview, setPreview] = useState<Preview | null>(null);
  const [source, setSource] = useState("baostock"); const [kind, setKind] = useState("auto");
  const [start, setStart] = useState(p.startDate); const [end, setEnd] = useState(p.endDate);
  const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; void s.act(async () => { const data = await request<Preview>("data.preview", { projectId: p.id }); if (active) setPreview(data); }); return () => { active = false; }; }, [p.id, s.revision]);
  const run = (work: () => Promise<unknown>) => { setBusy(true); void s.act(work).finally(() => setBusy(false)); };
  return <div className="r-page"><Heading title="数据" description="导入本地文件，或手动更新免费数据源。覆盖范围以实际读取结果为准。" /><div className="r-form-grid"><Field label="开始日期"><input type="date" value={start} onChange={e => setStart(e.target.value)} /></Field><Field label="结束日期"><input type="date" value={end} onChange={e => setEnd(e.target.value)} /></Field><Field label="数据源"><select value={source} onChange={e => setSource(e.target.value)}><option value="baostock">BaoStock</option><option value="akshare">AKShare</option></select></Field><Field label="导入类型"><select value={kind} onChange={e => setKind(e.target.value)}><option value="auto">自动识别</option><option value="prices">量价数据</option><option value="financials">财务数据</option></select></Field></div><div className="r-toolbar"><button className="r-primary" disabled={busy} onClick={() => run(async () => { const files = await window.v3Research!.chooseFiles(); if (files.length) await s.submit("data.import", { files, kind }); })}>导入 CSV / Parquet</button><button disabled={busy || !start || !end || start > end} onClick={() => run(async () => { await s.save({ startDate: start, endDate: end }); await s.submit("data.update", { source, financials: true, startDate: start, endDate: end }); })}>手动更新</button><button disabled={busy || !start || !end || start > end} onClick={() => run(async () => { await s.save({ startDate: start, endDate: end }); s.setNotice("研究区间已保存"); })}>保存研究区间</button><button onClick={() => void s.act(() => s.refresh())}>刷新预览</button></div>
    <p className="r-note">财务数据按公告日期进入研究；历史修订与覆盖缺失请查看任务消息。免费源可用性以本次更新结果为准。</p>
    {!!preview?.warnings?.length && <details><summary>数据说明（{preview.warnings.length}）</summary>{preview.warnings.map((warning, i) => <p key={i} className="r-note">{warning}</p>)}</details>}{preview?.datasets.length ? <><DataTable table={{ name: "数据覆盖", columns: ["name", "rows", "symbols", "startDate", "endDate", "missingValues"], rows: preview.datasets.map(d => ({ name: d.name, rows: d.rows, symbols: d.symbols, startDate: d.startDate, endDate: d.endDate, missingValues: d.missingValues ?? null })) }} /><DataTable table={{ name: "数据预览", columns: Object.keys(preview.rows[0] ?? {}), rows: preview.rows }} /></> : <Empty title="项目中还没有可预览的数据">导入文件或完成一次手动更新后，查看日期、字段与证券覆盖。</Empty>}</div>;
}
interface UniverseTemplate { id: string; name: string; universe: UniverseConfig }
export function UniversePanel() {
  const s = useResearch(); const p = s.project!;
  const [draft, setDraft] = useState(p.universe); const [symbols, setSymbols] = useState(p.universe.symbols.join("\n"));
  const [templates, setTemplates] = useState<UniverseTemplate[]>([]);
  const config = () => ({ ...draft, symbols: [...new Set(symbols.split(/[\s,，;；]+/).map(v => v.trim()).filter(Boolean))] });
  const load = async () => setTemplates(await request<UniverseTemplate[]>("universe.templates"));
  useEffect(() => { void s.act(load); }, []);
  return <div className="r-page"><Heading title="股票池" description="从个人模板复制到项目，再独立调整；修改项目不会改变个人模板。" /><div className="r-form-grid"><Field label="股票池名称"><input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} /></Field><Field label="选股范围"><select value={draft.source} onChange={e => setDraft({ ...draft, source: e.target.value as UniverseConfig["source"] })}><option value="manual">自选证券</option><option value="csi300">沪深 300</option><option value="csi500">中证 500</option><option value="all">全市场</option></select></Field><Field label="最短上市天数"><input type="number" min={0} value={draft.minListingDays} onChange={e => setDraft({ ...draft, minListingDays: Number(e.target.value) })} /></Field><label className="r-check"><input type="checkbox" checked={draft.excludeST} onChange={e => setDraft({ ...draft, excludeST: e.target.checked })} />排除 ST</label></div><Field label="证券代码（空格、逗号或换行分隔）"><textarea rows={6} value={symbols} onChange={e => setSymbols(e.target.value)} placeholder="输入需要研究的证券代码" /></Field><div className="r-toolbar"><button className="r-primary" onClick={() => void s.act(async () => { await s.save({ universe: config() }); s.setNotice("项目股票池已保存"); })}>保存项目副本</button><button disabled={!draft.name.trim()} onClick={() => void s.act(async () => { await request("universe.saveTemplate", { name: draft.name, universe: config() }); await load(); s.setNotice("已保存到个人模板库"); })}>另存为个人模板</button></div><h2>个人模板</h2>{templates.length ? <div className="r-template-list">{templates.map(t => <button key={t.id} onClick={() => { setDraft(structuredClone(t.universe)); setSymbols(t.universe.symbols.join("\n")); }}><strong>{t.name}</strong><span>{t.universe.symbols.length} 个自选代码 · 复制到编辑区 →</span></button>)}</div> : <Empty title="还没有个人模板">保存常用股票池，在不同项目中复用。</Empty>}</div>;
}
export function FactorPanel() {
  const s = useResearch(); const [search, setSearch] = useState(""); const [family, setFamily] = useState("");
  const [processing, setProcessing] = useState(() => factorProcessing(s.project!.settings));
  const [analysis, setAnalysis] = useState<JsonObject>({ periods: [1, 5, 10, 20], quantiles: 5, labelMode: "next_open", ...object(s.project!.settings.factorAnalysis) });
  const [periods, setPeriods] = useState(String((analysis.periods as number[]).join(",")));
  const [formula, setFormula] = useState(""); const [name, setName] = useState("");
  const [custom, setCustom] = useState<{ id: string; name: string; expression: string }[]>(() => (s.project?.settings.customFactors as unknown as { id: string; name: string; expression: string }[]) ?? []);
  const all = [...s.factors, ...custom.map(c => ({ ...c, family: "自定义", description: c.expression }))];
  const list = all.filter(f => (!family || f.family === family) && `${f.id} ${f.name} ${f.description}`.toLowerCase().includes(search.toLowerCase()));
  const toggle = (id: string) => s.setSelectedFactors(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]);
  return <div className="r-page"><Heading title="因子研究" description="选择一组量价或财务因子，检查 IC、分组表现、换手与相关性。" /><div className="r-toolbar"><input aria-label="搜索因子" placeholder="搜索名称、表达式…" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="因子分类" value={family} onChange={e => setFamily(e.target.value)}><option value="">所有分类</option>{[...new Set(all.map(f => f.family))].map(f => <option key={f}>{f}</option>)}</select><button onClick={() => s.setSelectedFactors([...new Set([...s.selectedFactors, ...list.map(f => f.id)])])}>选择筛选结果</button><button onClick={() => s.setSelectedFactors([])}>清空</button></div><div className="r-factor-list">{list.map(f => <label key={f.id} className={s.selectedFactors.includes(f.id) ? "selected" : ""}><input type="checkbox" checked={s.selectedFactors.includes(f.id)} onChange={() => toggle(f.id)} /><div><strong>{f.name}</strong><code>{f.id}</code><p>{f.description}</p></div><span className="r-tag">{f.family}</span></label>)}</div>{!list.length && <Empty title="没有匹配的因子">调整筛选条件，或检查研究服务是否返回因子库。</Empty>}
    <FactorProcessingEditor value={processing} onChange={setProcessing} /><div className="r-form-grid"><Field label="分析周期（交易日，逗号分隔）"><input value={periods} onChange={e => setPeriods(e.target.value)} /></Field><NumberSetting label="分组数" name="quantiles" value={analysis} onChange={setAnalysis} min={2} step={1} /><ChoiceSetting label="标签口径" name="labelMode" value={analysis} onChange={setAnalysis} choices={{ next_open: "下一开盘起算", close: "收盘到收盘（研究）" }} /></div>
    <div className="r-toolbar"><span>已选 {s.selectedFactors.length} 个</span><button className="r-primary" disabled={!s.selectedFactors.length} onClick={() => void s.act(async () => { const days = [...new Set(periods.split(/[,，\s]+/).filter(Boolean).map(Number))]; if (!days.length || days.some(n => !Number.isInteger(n) || n < 1)) throw new Error("分析周期必须为正整数。"); const config = { ...analysis, periods: days }; await s.save({ settings: { ...s.project!.settings, factorAnalysis: config, factorProcessing: processing, selectedFactors: s.selectedFactors } }); await s.submit("factor.analyze", { ...config, factorIds: s.selectedFactors, factorProcessing: processing, customFactors: custom.filter(c => s.selectedFactors.includes(c.id)) }); })}>运行批量分析</button><button onClick={() => s.setPage("results")}>查看分析结果 →</button></div>
    <details><summary>公式编辑 · 自定义因子</summary><Field label="因子名称"><input value={name} onChange={e => setName(e.target.value)} /></Field><CodeEditor label="因子表达式" language="plaintext" value={formula} onChange={setFormula} /><button disabled={!name.trim() || !formula.trim()} onClick={() => void s.act(async () => { const next = [...custom, { id: `custom_${crypto.randomUUID().replace(/-/g, "")}`, name: name.trim(), expression: formula.trim() }]; await s.save({ settings: { ...s.project!.settings, customFactors: next } }); setCustom(next); setName(""); setFormula(""); })}>保存自定义因子</button><p className="r-note">表达式由后端验证与计算。保存公式不代表已通过分析。</p></details></div>;
}
