import React, { useEffect, useState } from "react";
import type { JsonObject, UniverseConfig, MembershipVersion, StrategyConfig, ProjectConfig } from "../../../../../packages/contracts/src/research";
import { QuoteDirectory } from "./QuotePanel";
import { request, useResearch } from "./state";
import { useDraftAutosave, useObjectPanel, useWorkspace, flushDrafts } from "./workspace";
import { CodeEditor, DataTable, Empty, Field, Heading, Plot, fieldLabel, tableValue } from "./ui";

import { object, factorProcessing, FactorProcessingEditor, NumberSetting, ChoiceSetting } from "./configuration";

export function Overview() {
  const s = useResearch(); const p = s.project!;
  const [objective, setObjective] = useState(p.objective);
  const [editing, setEditing] = useState(false);
  return <div className="r-page"><Heading title={p.name} description={p.objective || "为这个项目写下一个可检验的研究问题。"}><span className="r-tag">A 股 · 日线</span></Heading>
    <section className="r-objective"><h3>研究目标</h3>{editing ? <><textarea aria-label="研究目标" value={objective} onChange={e => setObjective(e.target.value)} /><div className="r-toolbar"><button className="r-primary" onClick={() => void s.act(async () => { await s.save({ objective }); setEditing(false); })}>保存目标</button><button onClick={() => setEditing(false)}>取消</button></div></> : <><p>{p.objective || "尚未设置研究目标"}</p><div className="r-meta"><span>股票池：{p.universe.name}</span><span>{p.startDate || "未设置开始日期"} — {p.endDate || "未设置结束日期"}</span></div><div className="r-toolbar"><button className="r-primary" onClick={() => s.setPage("factors")}>继续因子研究 →</button><button onClick={() => { setObjective(p.objective); setEditing(true); }}>编辑研究目标</button><button onClick={() => s.setPage("results")}>查看实验</button></div></>}</section>
    <section><h2>研究入口</h2><div className="r-entry-row">{([ ["data", "数据准备"], ["universe", "股票池"], ["factors", "因子分析"], ["backtest", "策略回测"], ["model", "模型训练"], ["selection", "每日选股"] ] as const).map(([page, label], i) => <button key={page} onClick={() => s.setPage(page)}><span className="r-entry-number">0{i + 1}</span>{label}<span>→</span></button>)}</div></section>
    <section><div className="r-toolbar"><h2>最近实验</h2><span>{s.experiments.length} 个实验</span></div>{!s.experiments.length ? <Empty title="让第一个实验回答你的问题">准备数据、选择股票池与因子后，运行一次分析。结果会保存在这个项目中。</Empty> : <div className="r-experiment-list">{s.experiments.slice(0, 6).map(e => <button key={e.id} onClick={() => { s.setSelectedExperiment(e.id); s.setPage("results"); }}><strong>{e.starred ? "★ " : ""}{e.name}</strong><span>{e.summary}</span><time>{new Date(e.createdAt).toLocaleString("zh-CN")}</time><span>查看 →</span></button>)}</div>}</section>
  </div>;
}
interface Preview { datasets: { name: string; rows: number; symbols: number; startDate: string; endDate: string; columns: string[]; missingValues?: number }[]; rows: JsonObject[]; warnings?: string[]; history?: JsonObject[]; diagnostics?: {summary:JsonObject[];daily:JsonObject[];fields:JsonObject[];message?:string} }
export function DataPanel() {
  const panel=useObjectPanel(),w=useWorkspace();
  const s = useResearch(); const p = s.project!;
  const [preview, setPreview] = useState<Preview | null>(null);
  const [corporateActions,setCorporateActions]=useState(true);
  const [source, setSource] = useState("baostock"); const [kind, setKind] = useState("auto");
  const [start, setStart] = useState(p.startDate); const [end, setEnd] = useState(p.endDate);
  const [busy, setBusy] = useState(false);
  const [dataView,setDataView]=useState("catalog");
  useEffect(() => { let active = true; void s.act(async () => { const data = await request<Preview>("data.preview", { projectId: p.id, strategyId:panel?.strategyId }); if (active) setPreview(data); }); return () => { active = false; }; }, [p.id, panel?.strategyId, s.revision]);
  const run = (work: () => Promise<unknown>) => { setBusy(true); void s.act(work).finally(() => setBusy(false)); };
  return <div className="r-page"><Heading title="数据" description="导入本地文件，或手动更新免费数据源。覆盖范围以实际读取结果为准。" /><div className="r-form-grid"><Field label="开始日期"><input type="date" value={start} onChange={e => setStart(e.target.value)} /></Field><Field label="结束日期"><input type="date" value={end} onChange={e => setEnd(e.target.value)} /></Field><Field label="数据源"><select value={source} onChange={e => setSource(e.target.value)}><option value="baostock">BaoStock</option><option value="akshare">AKShare</option></select></Field><Field label="导入类型"><select value={kind} onChange={e => setKind(e.target.value)}><option value="auto">自动识别</option><option value="prices">量价数据</option><option value="financials">财务数据</option></select></Field></div>{source==="baostock"&&<><label className="r-check"><input type="checkbox" checked={corporateActions} onChange={e=>setCorporateActions(e.target.checked)}/>补齐分红送转记录</label><p className="r-note">按来源实际覆盖补齐；回测缺少记录时，无法准确处理分红送转。</p></>}<div className="r-toolbar"><button className="r-primary" disabled={busy} onClick={() => run(async () => { const files = await window.v3Research!.chooseFiles(); if (files.length) await s.submit("data.import", { files, kind }); })}>导入 CSV / Parquet</button><button disabled={busy || !start || !end || start > end} onClick={() => run(async () => { await s.save({ startDate: start, endDate: end }); await s.submit("data.update", { source, corporateActions:source==="baostock"&&corporateActions, financials: true, startDate: start, endDate: end }); })}>手动更新</button><button disabled={busy || !start || !end || start > end} onClick={() => run(async () => { await s.save({ startDate: start, endDate: end }); s.setNotice(panel?.strategyId?"当前策略研究区间已保存":"项目研究区间已保存"); })}>保存研究区间</button><button onClick={() => void s.act(() => s.refresh())}>刷新预览</button></div>
    <p className="r-note">历史成员导入完成后，请到股票池选择本项目成员版本并点击“用于当前研究”；导入不会自动改变研究范围。<button onClick={()=>w.open({kind:"universe",title:"股票池",projectId:p.id,strategyId:panel?.strategyId})}>选择成员版本 →</button></p>
    <p className="r-note">财务数据按公告日期进入研究；历史修订与覆盖缺失请查看任务消息。免费源可用性以本次更新结果为准。</p>
    {!!preview?.warnings?.length && <details><summary>数据说明（{preview.warnings.length}）</summary>{preview.warnings.map((warning, i) => <p key={i} className="r-note">{warning}</p>)}</details>}{preview?.datasets.length ? <><nav className="r-subtabs" aria-label="数据分析视图">{[["catalog","数据目录"],["coverage","股票池逐日覆盖"],["fields","字段与缺失"],["history","历史成分与行业"],["preview","行情预览"]].map(([key,label])=><button key={key} className={dataView===key?"active":""} onClick={()=>setDataView(key)}>{label}</button>)}</nav>
      {dataView==="catalog"&&<><QuoteDirectory/><DataTable table={{ name: "数据覆盖", columns: ["name", "rows", "symbols", "startDate", "endDate", "missingValues"], rows: preview.datasets.map(d => ({ name: d.name, rows: d.rows, symbols: d.symbols, startDate: d.startDate, endDate: d.endDate, missingValues: d.missingValues ?? null })) }} /><p className="r-note">以上是实际缓存范围；最新日期不表示每只股票均已更新。股票池分母与逐日可用数请查看“股票池逐日覆盖”。</p></>}
      {dataView==="coverage"&&<DataCoverageAnalysis diagnostics={preview.diagnostics}/>}
      {dataView==="fields"&&<>{preview.diagnostics?.fields.length?<><p className="r-note">逐字段统计按诊断返回的股票池行分母计算；basis 为 partial_observed_pool_rows 时仅覆盖已观察池，不能称为全池完整率。</p><DataTable table={{name:"逐字段缺失",columns:["field","denominator","available","missing","basis"],rows:preview.diagnostics.fields}}/></>:null}{preview.datasets.map(dataset=><section key={dataset.name}><h3>{dataset.name==="prices"?"日线行情":"公告财务"} · {dataset.columns.length} 个字段</h3><p className="r-note">已记录缺失单元格合计：{dataset.missingValues??"未提供"}。此合计来自缓存全表，与上方按研究池计算的逐字段统计分母不同。</p><DataTable table={{name:"字段目录",columns:["field"],rows:dataset.columns.map(field=>({field}))}}/></section>)}</>}
      {dataView==="history"&&<><p className="r-note">以下日期是实际历史快照的生效日期范围；证券数不能代表连续历史覆盖。历史行业与指数成分缺失时，不用最新名单替代。</p>{preview.history?.length?<DataTable table={{name:"历史成分与行业",columns:["source","rows","symbols","startDate","endDate"],rows:preview.history}}/>:<Empty title="尚无历史成分与行业覆盖记录"/>}</>}
      {dataView==="preview"&&<><p className="r-note">当前只显示接口返回的最近 {preview.rows.length} 行，用于检查字段和值，不代表完整股票池或区间。</p><DataTable table={{ name: "数据预览", columns: Object.keys(preview.rows[0] ?? {}), rows: preview.rows }} /></>}</> : <Empty title="项目中还没有可预览的数据">导入文件或完成一次手动更新后，查看日期、字段与证券覆盖。</Empty>}</div>;
}
function DataCoverageAnalysis({diagnostics}:{diagnostics:Preview['diagnostics']}) {
 const [focus,setFocus]=useState<JsonObject|null>(null);
 if(!diagnostics)return <Empty title="当前接口未提供股票池分母">不能从行情预览或已下载证券数倒推完整率。</Empty>;
 const rows=diagnostics.daily;
 return <section><p className="r-note">{diagnostics.message}</p><DataTable table={{name:"数据诊断摘要",columns:['dataset','startDate','endDate','sessions','expected','available','missing','denominatorStatus','calendarBasis','universeSource'],rows:diagnostics.summary}}/>
 <Plot title="逐日预期股票池覆盖" option={{tooltip:{trigger:'item',formatter:params=>{const item=Array.isArray(params)?params[0]:params;const row=rows[item.dataIndex];return row?`${String(row.date).slice(0,10)}<br/>可用 ${row.available} / 预期 ${row.expected??'未知'}<br/>资格资料未知 ${row.eligibilityUnknown??'未提供'}`:'';}},grid:{left:65,right:25,bottom:85,top:20},xAxis:{type:'category',data:rows.map(row=>String(row.date).slice(0,10))},yAxis:{type:'category',data:['覆盖率']},visualMap:{min:0,max:1,orient:'horizontal',bottom:0,inRange:{color:['#e4b1a6','#e9ece8','#287a73']}},dataZoom:[{type:'inside'},{type:'slider',bottom:40,height:18}],series:[{type:'heatmap',data:rows.map((row,i)=>[i,0,row.denominatorStatus==='known'&&typeof row.expected==='number'&&row.expected>0&&typeof row.available==='number'?row.available/row.expected:null])}]}} onPoint={i=>rows[i]&&setFocus(rows[i])}/>
 <p className="r-note">未知分母或预期数为0的日期不着色。资格资料未知数单列，覆盖率不代表该日股票均满足选股条件。</p>{focus&&<div className="r-strategy-summary"><dl>{Object.entries(focus).map(([key,value])=><div key={key}><dt>{fieldLabel(key)}</dt><dd>{tableValue(value,key)}</dd></div>)}</dl></div>}<details><summary>全部逐日计数</summary><DataTable table={{name:"逐日股票池覆盖",columns:['date','expected','available','missing','observedPool','eligibilityUnknown','denominatorStatus','denominator'],rows}} onRow={setFocus}/></details></section>;
}

interface UniverseTemplate { id: string; name: string; universe: UniverseConfig }
const membershipKey=(ref:UniverseConfig["membershipRef"])=>ref?JSON.stringify([ref.poolId,ref.version,ref.source]):"";
const membershipLabel=(value:MembershipVersion)=>`${value.observedAt?new Date(value.observedAt).toLocaleString("zh-CN"):"导入时间未记录"} · ${value.membershipRef.source==="import"?"本地导入":value.membershipRef.source} · ${value.symbols} 只证券 · ${value.membershipRef.version.slice(0,8)}`;
export function UniversePanel() {
  const s=useResearch(),w=useWorkspace(),panel=useObjectPanel(),p=s.project!;
  const [draft,setDraft]=useState(p.universe),[symbols,setSymbols]=useState(p.universe.symbols.join("\n"));
  const [templates,setTemplates]=useState<UniverseTemplate[]>([]),[memberships,setMemberships]=useState<MembershipVersion[]>([]);
  const [selected,setSelected]=useState(membershipKey(p.universe.membershipRef)),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false);
  const config=()=>({...draft,symbols:[...new Set(symbols.split(/[\s,，;；]+/).map(value=>value.trim()).filter(Boolean))]});
  const autosave=useDraftAutosave(()=>({universe:config()}));
  function sync(value:UniverseConfig){autosave.acceptSaved({universe:value});setDraft(value);setSymbols(value.symbols.join("\n"));setSelected(membershipKey(value.membershipRef));}
  useEffect(()=>{if(!autosave.isDirty())sync(p.universe);},[p.universe]);
  useEffect(()=>{const applied=(event:Event)=>{const value=(event as CustomEvent<{projectId:string;strategyId?:string;universe:UniverseConfig}>).detail;if(value.projectId===p.id&&value.strategyId===panel?.strategyId)sync(value.universe);};window.addEventListener("v3-membership-applied",applied);return()=>window.removeEventListener("v3-membership-applied",applied);},[p.id,panel?.strategyId]);
  useEffect(()=>{let alive=true;const off=window.v3Research?.workspace?.onChanged(change=>{if(change.method!=="history.memberships.apply"||change.params?.projectId!==p.id||(change.params?.strategyId||undefined)!==panel?.strategyId)return;void s.act(async()=>{const universe=panel?.strategyId?(await request<StrategyConfig[]>("strategies.list",{projectId:p.id})).find(value=>value.id===panel.strategyId)?.universe:(await request<ProjectConfig[]>("projects.list")).find(value=>value.id===p.id)?.universe;if(!alive||!universe)return;if(autosave.isDirty()){setDraft(previous=>{const {membershipRef,...ordinary}=previous;return {...ordinary,...(universe.membershipRef?{membershipRef:universe.membershipRef}:{})};});setSelected(membershipKey(universe.membershipRef));}else sync(universe);});});return()=>{alive=false;off?.();};},[p.id,panel?.strategyId]);
  const load=async()=>{const [versions,templates]=await Promise.all([request<MembershipVersion[]>("history.memberships.list",{projectId:p.id}),request<UniverseTemplate[]>("universe.templates")]);setMemberships(versions);setTemplates(templates);setLoaded(true);};
  useEffect(()=>{void s.act(load);},[p.id,s.revision]);
  async function apply(){if(busy)return;setBusy(true);try{await s.act(async()=>{await flushDrafts();const version=memberships.find(value=>membershipKey(value.membershipRef)===selected);if(selected&&!version)throw new Error("成员版本不在本项目中，请刷新后重新选择。");const universe=await request<UniverseConfig>("history.memberships.apply",{projectId:p.id,strategyId:panel?.strategyId,membershipRef:version?.membershipRef??null});window.dispatchEvent(new CustomEvent("v3-membership-applied",{detail:{projectId:p.id,strategyId:panel?.strategyId,universe}}));await w.reload();s.setNotice(version?"已将成员版本用于当前研究，其他项目与策略保持原范围。":"已移除当前研究的成员引用，恢复普通股票池范围。");});}finally{setBusy(false);}}
  const current=membershipKey(draft.membershipRef),version=memberships.find(value=>membershipKey(value.membershipRef)===selected);
  const copy=(universe:UniverseConfig)=>{setDraft(structuredClone(universe));setSymbols(universe.symbols.join("\n"));setSelected(membershipKey(universe.membershipRef));};
  return <div className="r-page"><Heading title="股票池" description={panel?.strategyId?"只修改当前策略股票池，不修改项目默认范围或其他策略。":"只修改当前项目默认股票池，其他项目与策略保持原配置。"}/>
    <fieldset disabled={busy} className="r-universe-editor"><section className="r-membership-picker"><h3>历史成员版本</h3><p className="r-note">导入记录不自动生效。明确应用后，后续研究按该版本的成员日期范围读取；已有实验输入保持固定。</p><div className="r-toolbar"><select aria-label="本项目成员版本" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">普通股票池范围（不引用历史成员版本）</option>{current&&!memberships.some(value=>membershipKey(value.membershipRef)===current)&&<option value={current} disabled>当前引用未在本项目找到 · {draft.membershipRef?.version}</option>}{memberships.map(value=><option key={membershipKey(value.membershipRef)} value={membershipKey(value.membershipRef)} title={`${value.membershipRef.poolId} / ${value.membershipRef.version}`}>{membershipLabel(value)}</option>)}</select><button disabled={!loaded} onClick={()=>void s.act(load)}>刷新版本</button><button className="r-primary" disabled={!loaded||selected===current||!!selected&&!version} onClick={()=>void apply()}>{selected?"用于当前研究":"移除引用，恢复普通范围"}</button></div>{version&&<p className="r-note">{version.startDate??"未提供开始日期"} — {version.endDate??"持续有效（未设结束）"} · {version.symbols} 只证券 · {version.rows} 条成员记录 · 记录时间 {version.observedAt}</p>}<p className="r-note">当前已用：{draft.membershipRef?(memberships.find(value=>membershipKey(value.membershipRef)===current)?membershipLabel(memberships.find(value=>membershipKey(value.membershipRef)===current)!):`未找到本地版本 · ${draft.membershipRef.version.slice(0,8)}`):"普通股票池范围"}{busy?" · 正在应用…":""}</p></section>
    <div className="r-form-grid"><Field label="股票池名称"><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></Field><Field label="选股范围"><select value={draft.source} onChange={e=>setDraft({...draft,source:e.target.value as UniverseConfig["source"]})}><option value="manual">自选证券</option><option value="csi300">沪深 300</option><option value="csi500">中证 500</option><option value="all">全市场</option></select></Field><Field label="最短上市天数"><input type="number" min={0} value={draft.minListingDays} onChange={e=>setDraft({...draft,minListingDays:Number(e.target.value)})}/></Field><label className="r-check"><input type="checkbox" checked={draft.excludeST} onChange={e=>setDraft({...draft,excludeST:e.target.checked})}/>排除 ST</label></div><Field label="证券代码（空格、逗号或换行分隔）"><textarea rows={6} value={symbols} onChange={e=>setSymbols(e.target.value)} placeholder="输入需要研究的证券代码"/></Field><div className="r-toolbar"><button className="r-primary" onClick={()=>void s.act(async()=>{await flushDrafts();s.setNotice("当前研究股票池已保存");})}>保存当前研究股票池</button><button disabled={!draft.name.trim()||!!draft.membershipRef} onClick={()=>void s.act(async()=>{await request("universe.saveTemplate",{name:draft.name,universe:config()});await load();s.setNotice("已保存到个人模板库");})}>另存为个人模板</button></div>{draft.membershipRef&&<p className="r-note">成员版本属于本项目。移除引用后才可另存普通个人模板，避免跨项目引用错误来源。</p>}
    <h2>个人模板</h2>{templates.length?<div className="r-template-list">{templates.map(template=>{const local=!template.universe.membershipRef||memberships.some(value=>membershipKey(value.membershipRef)===membershipKey(template.universe.membershipRef));return <section key={template.id}><button disabled={!local||!loaded} onClick={()=>copy(template.universe)}><strong>{template.name}</strong><span>{template.universe.symbols.length} 个自选代码 · 复制到编辑区 →</span></button>{!local&&<><p role="status">此模板的成员版本不在本项目，不能直接使用。请导入本项目版本，或只复制普通范围。</p><button onClick={()=>{const {membershipRef,...ordinary}=template.universe;copy(ordinary);}}>仅复制普通范围（不带成员引用）</button></>}</section>;})}</div>:<Empty title="还没有个人模板">保存普通股票池范围，在不同项目中复用。</Empty>}
    </fieldset></div>;
}
export function FactorPanel() {
  const s = useResearch(); const [search, setSearch] = useState(""); const [family, setFamily] = useState("");
  const [processing, setProcessing] = useState(() => factorProcessing(s.project!.settings));
  const [analysis, setAnalysis] = useState<JsonObject>({ periods: [1, 5, 10, 20], quantiles: 5, labelMode: "next_open", ...object(s.project!.settings.factorAnalysis) });
  const [periods, setPeriods] = useState(String((analysis.periods as number[]).join(",")));
  const [formula, setFormula] = useState(""); const [name, setName] = useState("");
  const [custom, setCustom] = useState<{ id: string; name: string; expression: string }[]>(() => (s.project?.settings.customFactors as unknown as { id: string; name: string; expression: string }[]) ?? []);
  const all = [...s.factors, ...custom.map(c => ({ ...c, family: "自定义", description: object(c).source === "parquet" ? `Python 生成因子 · 数据：${String(object(c).dataPath ?? "未记录")} · 源码：${String(object(c).codePath ?? "未记录")}` : c.expression }))];
  const list = all.filter(f => (!family || f.family === family) && `${f.id} ${f.name} ${f.description}`.toLowerCase().includes(search.toLowerCase()));
  useDraftAutosave(() => ({ settings: { selectedFactors: s.selectedFactors, factorProcessing: processing, factorAnalysis: { ...analysis, periods: periods.split(/[,，\s]+/).filter(Boolean).map(Number) } } }));
  const toggle = (id: string) => s.setSelectedFactors(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]);
  return <div className="r-page"><Heading title="因子研究" description="选择一组量价或财务因子，检查 IC、分组表现、换手与相关性。" /><div className="r-toolbar"><input aria-label="搜索因子" placeholder="搜索名称、表达式…" value={search} onChange={e => setSearch(e.target.value)} /><select aria-label="因子分类" value={family} onChange={e => setFamily(e.target.value)}><option value="">所有分类</option>{[...new Set(all.map(f => f.family))].map(f => <option key={f}>{f}</option>)}</select><button onClick={() => s.setSelectedFactors([...new Set([...s.selectedFactors, ...list.map(f => f.id)])])}>选择筛选结果</button><button onClick={() => s.setSelectedFactors([])}>清空</button></div><div className="r-factor-list">{list.map(f => <label key={f.id} className={s.selectedFactors.includes(f.id) ? "selected" : ""}><input type="checkbox" checked={s.selectedFactors.includes(f.id)} onChange={() => toggle(f.id)} /><div><strong>{f.name}</strong><code>{f.id}</code><p>{f.description}</p></div><span className="r-tag">{f.family}</span></label>)}</div>{!list.length && <Empty title="没有匹配的因子">调整筛选条件，或检查研究服务是否返回因子库。</Empty>}
    <FactorProcessingEditor value={processing} onChange={setProcessing} /><div className="r-form-grid"><Field label="分析周期（交易日，逗号分隔）"><input value={periods} onChange={e => setPeriods(e.target.value)} /></Field><NumberSetting label="分组数" name="quantiles" value={analysis} onChange={setAnalysis} min={2} step={1} /><ChoiceSetting label="标签口径" name="labelMode" value={analysis} onChange={setAnalysis} choices={{ next_open: "下一开盘起算", close: "收盘到收盘（研究）" }} /></div>
    <div className="r-toolbar"><span>已选 {s.selectedFactors.length} 个</span><button className="r-primary" disabled={!s.selectedFactors.length} onClick={() => void s.act(async () => { const days = [...new Set(periods.split(/[,，\s]+/).filter(Boolean).map(Number))]; if (!days.length || days.some(n => !Number.isInteger(n) || n < 1)) throw new Error("分析周期必须为正整数。"); const config = { ...analysis, periods: days }; await flushDrafts(); await s.save({ settings: { factorAnalysis: config, factorProcessing: processing, selectedFactors: s.selectedFactors } }); await s.submit("factor.analyze", { ...config, factorIds: s.selectedFactors, factorProcessing: processing, customFactors: custom.filter(c => s.selectedFactors.includes(c.id)) }); })}>运行批量分析</button><button onClick={() => s.setPage("results")}>查看分析结果 →</button></div>
    <details><summary>公式编辑 · 自定义因子</summary><Field label="因子名称"><input value={name} onChange={e => setName(e.target.value)} /></Field><CodeEditor label="因子表达式" language="plaintext" value={formula} onChange={setFormula} /><button disabled={!name.trim() || !formula.trim()} onClick={() => void s.act(async () => { const next = [...custom, { id: `custom_${crypto.randomUUID().replace(/-/g, "")}`, name: name.trim(), expression: formula.trim() }]; await s.save({ settings: { ...s.project!.settings, customFactors: next } }); setCustom(next); setName(""); setFormula(""); })}>保存自定义因子</button><p className="r-note">表达式由后端验证与计算。保存公式不代表已通过分析。</p></details></div>;
}
