import React, { useEffect, useState } from "react";
import type { JsonObject, StrategyConfig, WorkspacePanel, DataCoverage } from "../../../../../packages/contracts/src/research";
import { request, useResearch } from "./state";
import { useDraftAutosave, useWorkspace, flushDrafts } from "./workspace";
import { CodeEditor, Field, Heading, Empty, valueText } from "./ui";
import { completeStrategy, completeModel, object, factorProcessing, PortfolioEditor, CostsEditor, ValidationEditor, validateDates, NumberSetting, ChoiceSetting, validationDefaults } from "./configuration";

function datesValid(dates: JsonObject) { try { validateDates(dates); return true; } catch { return false; } }
function objectText(text: string): JsonObject { const v: unknown = JSON.parse(text); if (!v || typeof v !== "object" || Array.isArray(v)) throw new Error("参数必须是 JSON 对象。"); return v as JsonObject; }
function savedCustomFactors(settings: JsonObject): { id: string; name: string; expression: string }[] {
  if (!Array.isArray(settings.customFactors)) return [];
  return settings.customFactors.flatMap(factor => {
    if (!factor || typeof factor !== "object" || Array.isArray(factor)) return [];
    return typeof factor.id === "string" && typeof factor.name === "string" && typeof factor.expression === "string"
      ? [{ id: factor.id, name: factor.name, expression: factor.expression }] : [];
  });
}
export function FactorSelection() {
  const s = useResearch(); const [search, setSearch] = useState("");
  const factors = [...s.factors, ...savedCustomFactors(s.project!.settings)];
  const names = new Map(factors.map(f=>[f.id,f.name]));
  const matches = factors.filter(f=>`${f.id} ${f.name}`.toLowerCase().includes(search.toLowerCase()));
  const toggle=(id:string)=>s.setSelectedFactors(ids=>ids.includes(id)?ids.filter(x=>x!==id):[...ids,id]);
  return <section><div className="r-toolbar"><h3>参与因子</h3><span>已选 {s.selectedFactors.length} 个</span><button onClick={()=>s.setPage("factors")}>分析因子 →</button></div><div className="r-chips">{s.selectedFactors.map(id=><button key={id} onClick={()=>toggle(id)} aria-label={`移除${names.get(id)??id}`}>{names.get(id)??id} ×</button>)}</div>{!s.selectedFactors.length&&<p className="r-note">尚未选择因子。展开下方因子库，搜索并添加。</p>}<details className="r-factor-picker"><summary>添加因子 / 选择因子库</summary><input aria-label="搜索参与因子" placeholder="按名称或因子代码搜索" value={search} onChange={e=>setSearch(e.target.value)}/><div className="r-factor-picker-list">{matches.map(f=><label key={f.id}><input type="checkbox" checked={s.selectedFactors.includes(f.id)} onChange={()=>toggle(f.id)}/><span>{f.name}</span><small>{f.id}</small></label>)}</div>{!matches.length&&<p className="r-note">没有匹配的因子。</p>}</details></section>;
}
export function StrategyHome({panel}:{panel:WorkspacePanel}) {
  const s=useResearch(); const w=useWorkspace(); const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [coverage,setCoverage]=useState<DataCoverage[]>([]);
  useEffect(()=>{let active=true;void s.act(async()=>{const rows=await request<DataCoverage[]>("data.catalog",{projectId:panel.projectId});if(active)setCoverage(rows);});return()=>{active=false;};},[panel.projectId,s.revision]);
  const project=s.project!; const strategy=w.strategies.find(st=>st.id===panel.strategyId&&st.projectId===panel.projectId);
  const config=completeStrategy(project.settings), portfolio=object(config.portfolio);
  const names=new Map([...s.factors,...savedCustomFactors(project.settings)].map(f=>[f.id,f.name]));
  const template=({single_factor:"单因子排序",multi_factor:"多因子加权",model_score:"模型评分"} as Record<string,string>)[String(config.template)]??"待设置";
  const method=({equal:"等权",score:"评分加权",risk_parity:"风险平价",mean_variance:"均值方差"} as Record<string,string>)[String(portfolio.method)]??"待设置";
  const frequency=({daily:"每日",weekly:"每周",monthly:"每月"} as Record<string,string>)[String(config.rebalance)]??"待设置";
  const changes:string[]=[]; if(strategy?.active){for(const [key,label] of [["backtest","策略参数"],["model","模型"],["selectedFactors","参与因子"],["factorProcessing","因子处理"],["factorAnalysis","分析设置"],["customFactors","自定义因子"]])if(JSON.stringify(strategy.active.settings[key])!==JSON.stringify(project.settings[key]))changes.push(label);if(JSON.stringify(strategy.active.universe)!==JSON.stringify(project.universe))changes.push("股票池");}
  const canRun=Number(config.topN)>0&&Number(config.capital)>0&&(config.template==="model_score"?!!config.modelExperimentId:s.selectedFactors.length>0);
  async function run(){setBusy(true);await s.act(async()=>{await flushDrafts();const live=panel.strategyId?(await request<StrategyConfig[]>("strategies.list",{projectId:panel.projectId})).find(st=>st.id===panel.strategyId):undefined;const settings=live?.settings??project.settings;const parameters=completeStrategy(settings);parameters.factorIds=settings.selectedFactors??parameters.factorIds;parameters.customFactors=savedCustomFactors(settings).filter(f=>Array.isArray(parameters.factorIds)&&parameters.factorIds.includes(f.id));parameters.factorProcessing=factorProcessing(settings);await s.submit("backtest.run",parameters,`${strategy?.name??project.name} · 回测`);});setBusy(false);}
  if(editing)return <div className="r-strategy-edit"><div className="r-toolbar r-edit-toolbar"><button onClick={()=>void s.act(async()=>{await flushDrafts();setEditing(false);})}>← 返回策略摘要</button><span>编辑草稿 · 自动保存</span></div><StrategyPanel key={s.configurationVersions.strategy??0}/></div>;
  return <div className="r-page"><Heading title={strategy?.name??"策略研究"} description={project.objective||"检查配置与最近结果，再决定下一次实验。"}/><div className="r-strategy-summary"><dl><div><dt>策略模板</dt><dd>{template}</dd></div><div><dt>组合方式</dt><dd>{method}</dd></div><div><dt>持仓数量</dt><dd>{valueText(config.topN)} 只</dd></div><div><dt>调仓频率</dt><dd>{frequency}</dd></div><div><dt>研究股票池</dt><dd>{project.universe.name||"待设置"}{project.universe.source==="manual"?` · ${project.universe.symbols.length}只`:""}</dd></div><div><dt>研究日期</dt><dd>{project.startDate||"未设置"} — {project.endDate||"未设置"}</dd></div><div><dt>已存行情日期</dt><dd>{(()=>{const row=coverage.find(c=>/price|行情|daily/i.test(c.dataset));return row?.endDate?`${row.startDate??"—"} — ${row.endDate}`:"暂无行情覆盖";})()}</dd></div></dl><div className="r-summary-factors"><span>参与因子 · {s.selectedFactors.length} 个</span><div className="r-chips">{s.selectedFactors.length?s.selectedFactors.map(id=><span className="r-tag" key={id}>{names.get(id)??id}</span>):<span className="r-muted">尚未选择</span>}</div></div><p className="r-note">{!strategy?.active?"尚未应用到每日选股。编辑并验证策略后，可在上方明确启用。":`${strategy.enabled?"每日选股已启用":"每日选股已停用"} · ${changes.length?`当前草稿与启用快照不同：${changes.join("、")}`:"当前草稿与启用快照一致"}`}</p></div><div className="r-toolbar"><button className="r-primary" onClick={()=>setEditing(true)}>编辑参数</button><button disabled={busy||!canRun} onClick={()=>void run()}>{busy?"正在提交…":"运行回测"}</button><button onClick={()=>s.setPage("factors")}>因子研究</button><button onClick={()=>s.setPage("model")}>模型训练</button><button onClick={()=>s.setPage("universe")}>编辑股票池</button></div>{!canRun&&<p className="r-note">{config.template==="model_score"?"选择已训练模型后可运行回测。":"选择参与因子并检查参数后可运行回测。"}</p>}<div className="r-toolbar"><h2>最近实验</h2><button onClick={()=>s.setPage("results")}>全部结果 →</button></div>{s.experiments.length?<div className="r-experiment-list">{s.experiments.slice(0,6).map(experiment=><button key={experiment.id} onClick={()=>w.open({kind:"experiment",title:experiment.name,projectId:experiment.projectId,strategyId:experiment.strategyId,experimentId:experiment.id})}><strong>{experiment.name}</strong><span>{({"backtest.run":"策略回测","model.train":"模型训练","factor.analyze":"因子分析","optimize.run":"参数寻优","selection.run":"每日选股","data.update":"数据更新","data.import":"数据导入"})[experiment.kind]}</span><time>{new Date(experiment.createdAt).toLocaleString("zh-CN")}</time></button>)}</div>:<Empty title="这项策略还没有实验">完成配置后运行一次回测，结果会保存在这里。</Empty>}</div>;
}
export function StrategyPanel({ run = false }: { run?: boolean }) {
  const s = useResearch();
  const saved = completeStrategy(s.project!.settings);
  const [template, setTemplate] = useState(String(saved.template ?? "multi_factor"));
  const [topN, setTopN] = useState(Number(saved.topN ?? 30)); const [rebalance, setRebalance] = useState(String(saved.rebalance ?? "weekly"));
  const [capital, setCapital] = useState(Number(saved.capital ?? 1000000));
  const [portfolio, setPortfolio] = useState(object(saved.portfolio)); const [costs, setCosts] = useState(object(saved.costs));
  const [benchmark, setBenchmark] = useState(String(object(s.project!.settings.backtest).benchmark ?? (s.project!.universe.source === "csi500" ? "csi500" : "csi300")));
  const [weights, setWeights] = useState<JsonObject>(object(saved.weights));
  const [code, setCode] = useState(String(saved.code ?? "")); const [model, setModel] = useState(String(saved.modelExperimentId ?? ""));
  const parameters = (): JsonObject => ({ template, factorIds: s.selectedFactors, customFactors: savedCustomFactors(s.project!.settings).filter(f => s.selectedFactors.includes(f.id)), weights, topN, rebalance, capital, portfolio, costs, benchmark, factorProcessing: factorProcessing(s.project!.settings), ...(model ? { modelExperimentId: model } : {}), ...(code.trim() ? { code } : {}) });
  const save = async () => { const p = parameters(); await s.save({ settings: { ...s.project!.settings, selectedFactors: s.selectedFactors, backtest: p } }); return p; };
  useDraftAutosave(() => ({ settings: { ...s.project!.settings, selectedFactors: s.selectedFactors, backtest: parameters() } }));
  return <div className="r-page"><Heading title={run ? "策略回测" : "策略模板"} description="多头组合 · 参数可调整。每次运行保存独立实验及输入参数。" /><div className="r-form-grid"><Field label="组合模板"><select value={template} onChange={e => setTemplate(e.target.value)}><option value="single_factor">单因子排序</option><option value="multi_factor">多因子加权</option><option value="model_score">模型评分</option></select></Field><Field label="持仓数量"><input type="number" min={1} value={topN} onChange={e => setTopN(Number(e.target.value))} /></Field><Field label="调仓频率"><select value={rebalance} onChange={e => setRebalance(e.target.value)}><option value="daily">每日</option><option value="weekly">每周</option><option value="monthly">每月</option></select></Field><Field label="初始资金（元）"><input type="number" min={1} value={capital} onChange={e => setCapital(Number(e.target.value))} /></Field></div>
    {template === "model_score" ? <Field label="模型实验"><select value={model} onChange={e => setModel(e.target.value)}><option value="">选择已完成的模型实验</option>{s.experiments.filter(e => e.kind === "model.train").map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></Field> : <FactorSelection />}
    <Field label="比较基准"><select value={benchmark} onChange={e => setBenchmark(e.target.value)}><option value="csi300">沪深300</option><option value="csi500">中证500</option></select></Field>
    {template === "multi_factor" && <section><h3>因子权重</h3><div className="r-form-grid">{s.selectedFactors.map(id => <Field key={id} label={s.factors.find(f => f.id === id)?.name ?? savedCustomFactors(s.project!.settings).find(f => f.id === id)?.name ?? id}><input type="number" step="any" value={weights[id] == null ? "" : Number(weights[id])} placeholder="默认权重" onChange={e => { const next = { ...weights }; if (e.target.value === "") delete next[id]; else next[id] = Number(e.target.value); setWeights(next); }} /></Field>)}</div></section>}
    <PortfolioEditor value={portfolio} onChange={setPortfolio} /><details open={run}><summary>交易成本与成交限制</summary><CostsEditor value={costs} onChange={setCosts} /></details>
    <details><summary>Python 策略编辑</summary><p className="r-note">代码提交到后端执行；后端不支持的代码接口会返回明确错误。</p><CodeEditor value={code} onChange={setCode} /></details><div className="r-toolbar"><button onClick={() => void s.act(async () => { await save(); s.setNotice("策略参数已保存"); })}>保存参数</button><button className="r-primary" disabled={topN < 1 || capital <= 0 || (template === "model_score" ? !model : !s.selectedFactors.length)} onClick={() => void s.act(async () => { await s.submit("backtest.run", await save()); })}>运行回测</button></div><Optimization target="backtest" getParameters={parameters} disabled={topN < 1 || capital <= 0 || (template === "model_score" ? !model : !s.selectedFactors.length)} /></div>;
}
export function ModelPanel() {
  const s = useResearch(); const saved = completeModel(s.project!.settings);
  const [model, setModel] = useState(String(saved.model ?? "lightgbm"));
  const dateKeys = ["trainStart", "trainEnd", "validStart", "validEnd", "testStart", "testEnd"] as const;
  const labels = ["训练开始", "训练结束", "验证开始", "验证结束", "测试开始", "测试结束"];
  const [dates, setDates] = useState<Record<string, string>>(() => Object.fromEntries(dateKeys.map(k => [k, String(saved[k] ?? "")])));
  const [horizon, setHorizon] = useState(Number(saved.labelHorizon ?? 5));
  const [validation, setValidation] = useState(object(saved.validation)); const [labelMode, setLabelMode] = useState(String(saved.labelMode));
  const [hyper, setHyper] = useState(JSON.stringify(saved.hyperparameters ?? {}, null, 2));
  const parameters = (): JsonObject => ({ model, factorIds: s.selectedFactors, customFactors: savedCustomFactors(s.project!.settings).filter(f => s.selectedFactors.includes(f.id)), ...dates, validation, labelMode, factorProcessing: factorProcessing(s.project!.settings), labelHorizon: horizon, hyperparameters: { ...(model === "ridge" ? { alpha: 1 } : { learning_rate: .1, num_leaves: 31, n_estimators: 100 }), ...objectText(hyper) } });
  useDraftAutosave(() => ({ settings: { ...s.project!.settings, selectedFactors: s.selectedFactors, model: parameters() } }));
  const ordered = datesValid(dates);
  return <div className="r-page"><Heading title="模型训练" description="按时间分离训练、验证与测试；寻优只使用验证区间。" /><div className="r-form-grid"><Field label="模型"><select value={model} onChange={e => { setModel(e.target.value); setHyper(JSON.stringify(e.target.value === "ridge" ? { alpha: 1 } : { learning_rate: .1, num_leaves: 31, n_estimators: 100 }, null, 2)); }}><option value="lightgbm">LightGBM</option><option value="ridge">Ridge</option></select></Field><Field label="预测周期（交易日）"><input type="number" min={1} value={horizon} onChange={e => setHorizon(Number(e.target.value))} /></Field><Field label="收益标签"><select value={labelMode} onChange={e => setLabelMode(e.target.value)}><option value="next_open">下一开盘起算（交易标签）</option><option value="close">收盘到收盘（研究标签）</option></select></Field></div><ValidationEditor value={validation} onChange={setValidation} dates={dates} onDates={v => setDates(Object.fromEntries(Object.entries(v).map(([k, x]) => [k, String(x ?? "")])))} />{!ordered && <p className="r-note">日期可全部留空，或填写完整且依次分离的三个区间。</p>}<div className="r-form-grid">{(model === "ridge" ? [["alpha", "正则强度", 1]] : [["learning_rate", "学习率", .1], ["num_leaves", "叶子数", 31], ["n_estimators", "迭代轮数", 100]]).map(([key, label, fallback]) => <Field key={String(key)} label={String(label)}><input type="number" min={0} step="any" value={(() => { try { return Number(objectText(hyper)[String(key)] ?? fallback); } catch { return ""; } })()} onChange={e => { try { setHyper(JSON.stringify({ ...objectText(hyper), [String(key)]: Number(e.target.value) }, null, 2)); } catch { s.setError("请先修正高级参数 JSON。"); } }} /></Field>)}</div><FactorSelection /><details><summary>高级模型参数</summary><Field label="超参数 JSON"><textarea rows={7} value={hyper} onChange={e => setHyper(e.target.value)} /></Field></details><div className="r-toolbar"><button onClick={() => void s.act(async () => { await s.save({ settings: { ...s.project!.settings, selectedFactors: s.selectedFactors, model: parameters() } }); s.setNotice("模型设置已保存"); })}>保存设置</button><button className="r-primary" disabled={!ordered || !s.selectedFactors.length || horizon < 1} onClick={() => void s.act(async () => { const p = parameters(); await s.save({ settings: { ...s.project!.settings, selectedFactors: s.selectedFactors, model: p } }); await s.submit("model.train", p); })}>训练模型</button></div><Optimization key={model} target="model" getParameters={parameters} disabled={!ordered || !s.selectedFactors.length} /></div>;
}
interface SearchRow { key: string; type: "choices" | "int" | "float"; choices: string; low: number; high: number; step: string; log: boolean }
function Optimization({ target, getParameters, disabled = false }: { target: "backtest" | "model"; getParameters: () => JsonObject; disabled?: boolean }) {
  const s = useResearch(); const [validation, setValidation] = useState<JsonObject>({ ...validationDefaults }); const [dates, setDates] = useState<Record<string, string>>({ trainStart: "", trainEnd: "", validStart: "", validEnd: "", testStart: "", testEnd: "" }); const [objective, setObjective] = useState(target === "model" ? "valid:mse" : "valid:information_ratio"); const [sampler, setSampler] = useState("grid"); const [trials, setTrials] = useState(20);
  const [rows, setRows] = useState<SearchRow[]>([{ key: target === "backtest" ? "topN" : getParameters().model === "ridge" ? "hyperparameters.alpha" : "hyperparameters.learning_rate", type: "choices", choices: "", low: 0, high: 1, step: "", log: false }]);
  const update = (index: number, patch: Partial<SearchRow>) => setRows(items => items.map((r, i) => i === index ? { ...r, ...patch } : r));
  const searchSpace = (): JsonObject => {
    const result: JsonObject = {};
    for (const row of rows) {
      const key = row.key.trim(); if (!key || key in result) throw new Error("搜索参数名不能为空或重复。");
      if (sampler === "grid" || row.type === "choices") {
        const choices = row.choices.split(/[,，]/).map(v => v.trim()).filter(Boolean).map(v => { try { return JSON.parse(v); } catch { return v; } });
        if (!choices.length) throw new Error(`请填写 ${key} 的候选值。`); result[key] = choices;
      } else {
        if (row.low >= row.high || row.log && row.low <= 0) throw new Error(`${key} 的范围无效。`);
        if (row.step && Number(row.step) <= 0) throw new Error(`${key} 的步长必须大于零。`);
        result[key] = { type: row.type, low: row.low, high: row.high, ...(row.step ? { step: Number(row.step) } : {}), log: row.log };
      }
    }
    return result;
  };
  return <details><summary>参数寻优 · 网格 / TPE</summary><Field label="验证集目标"><select value={objective} onChange={e => setObjective(e.target.value)}>{(target === "model" ? [["valid:mse", "验证集 MSE"], ["valid:ic", "验证集 IC"]] : [["valid:information_ratio", "验证集信息比率"], ["valid:annualized_return", "验证集年化收益"], ["valid:sharpe", "验证集夏普比率"]]).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field><p className="r-note">寻优使用下方独立验证窗口；测试集不参与选参。完成后在实验结果中明确应用最佳参数，再运行独立测试。</p><ValidationEditor value={validation} onChange={setValidation} dates={dates} onDates={v => setDates(Object.fromEntries(Object.entries(v).map(([k, x]) => [k, String(x ?? "")])))} /><div className="r-form-grid"><Field label="搜索方法"><select value={sampler} onChange={e => setSampler(e.target.value)}><option value="grid">网格搜索</option><option value="tpe">TPE 自动优化</option></select></Field><Field label="试验次数"><input type="number" min={1} value={trials} onChange={e => setTrials(Number(e.target.value))} /></Field></div>{rows.map((row, i) => <div className="r-search-row" key={i}><div className="r-form-grid"><Field label="参数名称"><input value={row.key} onChange={e => update(i, { key: e.target.value })} /></Field>{sampler === "tpe" && <Field label="搜索类型"><select value={row.type} onChange={e => update(i, { type: e.target.value as SearchRow["type"] })}><option value="choices">候选值</option><option value="int">整数范围</option><option value="float">连续范围</option></select></Field>}</div>{sampler === "grid" || row.type === "choices" ? <Field label="候选值（逗号分隔）"><input value={row.choices} onChange={e => update(i, { choices: e.target.value })} placeholder={target === "backtest" ? "例如：10,20,30" : "例如：0.01,0.05,0.1"} /></Field> : <div className="r-form-grid"><Field label="下限"><input type="number" value={row.low} onChange={e => update(i, { low: Number(e.target.value) })} /></Field><Field label="上限"><input type="number" value={row.high} onChange={e => update(i, { high: Number(e.target.value) })} /></Field><Field label="步长（可选）"><input type="number" min={0} value={row.step} onChange={e => update(i, { step: e.target.value })} /></Field><label className="r-check"><input type="checkbox" checked={row.log} onChange={e => update(i, { log: e.target.checked })} />对数搜索</label></div>}<button disabled={rows.length === 1} onClick={() => setRows(items => items.filter((_, n) => n !== i))}>移除此参数</button></div>)}<div className="r-toolbar"><button onClick={() => setRows(items => [...items, { key: "", type: "choices", choices: "", low: 0, high: 1, step: "", log: false }])}>添加搜索参数</button><button className="r-primary" disabled={disabled || trials < 1 || !datesValid(dates)} onClick={() => void s.act(() => s.submit("optimize.run", { target, sampler, trials, objective, validation: { ...validation, ...dates }, baseParameters: getParameters(), searchSpace: searchSpace() }))}>开始寻优</button></div></details>;
}
