import React from "react";
import type { ScreenerCondition, ScreenerConditionGroup } from "../../../../../packages/contracts/src/research";
import { fieldLabel } from "./ui";

export const emptyGroup=():ScreenerConditionGroup=>({id:crypto.randomUUID(),match:"all",children:[]});
const operators:Record<ScreenerCondition["operator"],string>={gt:"大于",gte:"至少",lt:"小于",lte:"至多",eq:"等于",ne:"不等于",between:"区间",rank_top:"排名前 N",rank_bottom:"排名后 N",cross_up:"上穿",cross_down:"下穿",contains:"包含文字",in:"属于列表"};
export function ScreenerConditions({value,onChange,fields,depth=0}:{value:ScreenerConditionGroup;onChange:(value:ScreenerConditionGroup)=>void;fields:string[];depth?:number}) {
  const update=(index:number,next:ScreenerCondition|ScreenerConditionGroup)=>onChange({...value,children:value.children.map((item,i)=>i===index?next:item)});
  const remove=(index:number)=>onChange({...value,children:value.children.filter((_,i)=>i!==index)});
  return <div className="r-screener-group"><div className="r-toolbar"><select aria-label="条件组关系" value={value.match} onChange={event=>onChange({...value,match:event.target.value as "all"|"any"})}><option value="all">满足全部条件</option><option value="any">满足任一条件</option></select><button onClick={()=>onChange({...value,children:[...value.children,{id:crypto.randomUUID(),field:"close",operator:"gte",value:0,occurrence:"current"}]})}>＋ 条件</button>{depth<3&&<button onClick={()=>onChange({...value,children:[...value.children,emptyGroup()]})}>＋ 条件组</button>}</div>{value.children.map((item,index)=>"children" in item?<div key={item.id}><ScreenerConditions value={item} onChange={next=>update(index,next)} fields={fields} depth={depth+1}/><button onClick={()=>remove(index)}>移除此条件组</button></div>:<ConditionRow key={item.id} value={item} fields={fields} onChange={next=>update(index,next)} onRemove={()=>remove(index)}/>)}</div>;
}
function ConditionRow({value,onChange,onRemove,fields}:{value:ScreenerCondition;onChange:(value:ScreenerCondition)=>void;onRemove:()=>void;fields:string[]}) {
  const patch=(next:Partial<ScreenerCondition>)=>onChange({...value,...next});
  const isText=value.operator==='contains'||value.operator==='in';
  const fieldOptions=[...new Set([...fields,value.field,...(value.compareField?[value.compareField]:[])])];
  return <div className="r-screener-condition"><select aria-label="条件字段" value={value.field} onChange={event=>patch({field:event.target.value})}>{fieldOptions.map(field=><option key={field} value={field}>{fieldLabel(field)}</option>)}</select><select aria-label="条件运算" value={value.operator} onChange={event=>patch({operator:event.target.value as ScreenerCondition['operator'],compareField:undefined})}>{Object.entries(operators).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select>{!isText&&!['rank_top','rank_bottom','between'].includes(value.operator)&&<select aria-label="比较对象" value={value.compareField?'field':'value'} onChange={event=>patch({compareField:event.target.value==='field'?fieldOptions[0]:undefined})}><option value="value">数值</option><option value="field">另一指标</option></select>}{value.compareField?<select aria-label="比较指标" value={value.compareField} onChange={event=>patch({compareField:event.target.value})}>{fieldOptions.map(field=><option key={field} value={field}>{fieldLabel(field)}</option>)}</select>:<input aria-label="条件数值" type={isText?'text':'number'} value={Array.isArray(value.value)?value.value.join(','):String(value.value??'')} onChange={event=>patch({value:isText?(value.operator==='in'?event.target.value.split(/[,，]/).map(item=>item.trim()).filter(Boolean).map(item=>Number.isFinite(Number(item))?Number(item):item):event.target.value):event.target.value===''?null:Number(event.target.value)})}/ >}{value.operator==='between'&&<><span>至</span><input aria-label="区间上限" type="number" value={value.upper??''} onChange={event=>patch({upper:event.target.value===''?undefined:Number(event.target.value)})}/></>}<select aria-label="条件出现方式" value={value.occurrence??'current'} onChange={event=>patch({occurrence:event.target.value as ScreenerCondition['occurrence'],window:event.target.value==='current'?undefined:value.window??3})}><option value="current">当日</option><option value="all">连续 N 交易日</option><option value="any">近 N 交易日出现</option></select>{value.occurrence&&value.occurrence!=='current'&&<input aria-label="条件交易日数" type="number" min={1} max={250} value={value.window??3} onChange={event=>patch({window:Number(event.target.value)})}/>}<button aria-label="移除条件" onClick={onRemove}>×</button></div>;
}
