import React, { useEffect, useRef, useState } from "react";
import type { JobEvent, JsonObject, MarketQuery, MarketTable, ResearchAssetRef, ScreenerPlan, ScreenerResult, ScreenerWorkspace, Watchlist } from "../../../../../packages/contracts/src/research";
import { errorText, request, useResearch } from "./state";
import { useWorkspace, useObjectPanel } from "./workspace";
import { registerAssistantEditor } from './localAssistantDraft';
import { DataTable, Empty, requestText, valueText, fieldLabel } from "./ui";
import { MarketGrid } from "./WorkspacePanels";
import { ScreenerAssetPicker, ScreenerDetail } from "./ScreenerParts";
import { emptyGroup, ScreenerConditions } from "./ScreenerConditions";

const symbolOf=(row:JsonObject)=>String(row.symbol??row.code??"");
const statusNames:Record<string,string>={included:"入选",excluded:"未入选",missing:"数据不足",outside:"范围外"};
const freshPlan=(mode:ScreenerPlan['mode']):ScreenerPlan=>({id:"",name:({conditions:"条件选股",factors:"多因子选股",strategy:"策略候选"})[mode],mode,version:0,universe:{name:"全部覆盖证券",source:"all",symbols:[],excludeST:true,minListingDays:60},conditions:emptyGroup(),factors:[],assets:[],rankingReference:"base",limit:30});
const configKey=(plan:ScreenerPlan)=>{const {id,name,version,favorite,archived,updatedAt,lastUsedAt,...config}=plan;return JSON.stringify(config);};
const busyJob=(job:JobEvent|null)=>!!job&&['queued','running'].includes(job.status);

export function ScreenerPanel() {
  const s=useResearch(),w=useWorkspace(),panel=useObjectPanel();
  const [workspace,setWorkspace]=useState<ScreenerWorkspace>({view:'screen',detailHeight:300});
  const [assistantUndo,setAssistantUndo]=useState<{before:ScreenerPlan;after:ScreenerPlan}|null>(null);
  const [ready,setReady]=useState(false),[error,setError]=useState(''),[plans,setPlans]=useState<ScreenerPlan[]>([]),[watchlists,setWatchlists]=useState<Watchlist[]>([]);
  const [planSearch,setPlanSearch]=useState(''),[planFilter,setPlanFilter]=useState('recent');
  const [assets,setAssets]=useState<ResearchAssetRef[]>([]),[assetsOpen,setAssetsOpen]=useState(false),[assetsLoading,setAssetsLoading]=useState(false),[assetError,setAssetError]=useState('');
  const [result,setResult]=useState<ScreenerResult|null>(null),[watchTable,setWatchTable]=useState<MarketTable|null>(null),[loading,setLoading]=useState(false),[resultRevision,setResultRevision]=useState(0);
  const [query,setQuery]=useState<MarketQuery>({offset:0,limit:100}),[resultStatus,setResultStatus]=useState('included'),[search,setSearch]=useState(''),[watchlistId,setWatchlistId]=useState('');
  const [selection,setSelection]=useState<JsonObject|null>(null),[detailOpen,setDetailOpen]=useState(false),[detailMode,setDetailMode]=useState<'chart'|'explanation'>('explanation');
  const [explanation,setExplanation]=useState<JsonObject|null>(null),[explainError,setExplainError]=useState(''),[explainLoading,setExplainLoading]=useState(false),[symbolSearch,setSymbolSearch]=useState('');
  const [job,setJob]=useState<JobEvent|null>(null),[saving,setSaving]=useState(false),[adding,setAdding]=useState(false);
  const runningPlanId=useRef(''),loadGeneration=useRef(0);
  const saveBusy=useRef(false),workspaceRef=useRef(workspace),workspaceQueue=useRef(Promise.resolve()),planRef=useRef<ScreenerPlan|undefined>(undefined),jobRef=useRef<JobEvent|null>(null);
  workspaceRef.current=workspace;planRef.current=workspace.draft;jobRef.current=job;
  useEffect(()=>panel?registerAssistantEditor(panel.id,{read:()=>planRef.current,replace:next=>{if(planRef.current)setAssistantUndo({before:planRef.current,after:next});planRef.current=next;setWorkspace(value=>({...value,draft:next}));}}):undefined,[panel?.id]);
  const draft=workspace.draft,view=workspace.view??'screen',planId=workspace.activePlanId??draft?.id??'';
  const saved=plans.find(plan=>plan.id===planId),dirty=!!draft&&(!saved||configKey(draft)!==configKey(saved));
  const patchWorkspace=(patch:Partial<ScreenerWorkspace>)=>setWorkspace(value=>({...value,...patch}));
  const edit=(patch:Partial<ScreenerPlan>)=>setWorkspace(value=>value.draft?{...value,draft:{...value.draft,...patch}}:value);
  const persistWorkspace=(state:ScreenerWorkspace)=>{workspaceQueue.current=workspaceQueue.current.catch(()=>{}).then(async()=>{await request('screeners.workspace.save',{state});});return workspaceQueue.current;};
  async function load() {const generation=++loadGeneration.current;setError('');try{const [state,list,groups]=await Promise.all([request<ScreenerWorkspace>('screeners.workspace.get'),request<ScreenerPlan[]>('screeners.list'),request<Watchlist[]>('watchlists.list')]);if(generation!==loadGeneration.current)return;setWorkspace(state);setPlans(list);setWatchlists(groups);setWatchlistId(groups[0]?.id??'');setReady(true);}catch(e){setError(errorText(e));}}
  useEffect(()=>{void load();const open=(event:Event)=>{const id=(event as CustomEvent<string>).detail;if(id)void choosePlan(id);};window.addEventListener('v3-open-screener-plan',open);return()=>window.removeEventListener('v3-open-screener-plan',open);},[]);
  useEffect(()=>{if(!ready)return;const timer=setTimeout(()=>{void persistWorkspace(workspace).catch(e=>setError(errorText(e)));},500);return()=>clearTimeout(timer);},[workspace,ready]);
  useEffect(()=>{if(!ready)return;return()=>{void persistWorkspace(workspaceRef.current).catch(()=>{});};},[ready]);
  useEffect(()=>{const timer=setTimeout(()=>setQuery(value=>({...value,search:search.trim(),offset:0})),180);return()=>clearTimeout(timer);},[search]);
  useEffect(()=>{let active=true;setError('');if(!ready)return;setLoading(true);const fetch=view==='screen'?(planId?request<ScreenerResult|null>('screeners.result',{planId,experimentId:workspace.lastExperimentId,...query,status:resultStatus||undefined}):Promise.resolve(null)):watchlistId?request<MarketTable>('market.screen',{...query,watchlistId}):Promise.resolve(null);void fetch.then(value=>{if(!active)return;if(view==='screen')setResult(value as ScreenerResult|null);else setWatchTable(value as MarketTable|null);}).catch(e=>{if(active)setError(errorText(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[ready,view,planId,workspace.lastExperimentId,JSON.stringify(query),resultStatus,watchlistId,resultRevision]);
  useEffect(()=>{const active=s.jobs.find(value=>value.kind==='screener.run'&&busyJob(value)&&value.spec.parameters.plan&&typeof value.spec.parameters.plan==='object'&&!Array.isArray(value.spec.parameters.plan)&&value.spec.parameters.plan.id===planId);if(active){runningPlanId.current=planId;jobRef.current=active;setJob(active);}},[planId,s.jobs]);
  useEffect(()=>window.v3Research?.onEvent(event=>{if(event.id!==jobRef.current?.id)return;setJob(event);if(['completed','failed','cancelled','interrupted'].includes(event.status)){if(event.status==='completed'){setWorkspace(value=>value.activePlanId===runningPlanId.current?{...value,lastExperimentId:event.experimentId}:value);setResultRevision(value=>value+1);}else setError(event.message);}}),[]);
  useEffect(()=>{let alive=true;setExplanation(null);setExplainError('');setExplainLoading(false);if(!detailOpen||detailMode!=='explanation'||!selection||!result?.experimentId||view!=='screen')return;setExplainLoading(true);void request<JsonObject>('screeners.explain',{experimentId:result.experimentId,symbol:symbolOf(selection)}).then(value=>{if(alive)setExplanation(value);}).catch(e=>{if(alive)setExplainError(errorText(e));}).finally(()=>{if(alive)setExplainLoading(false);});return()=>{alive=false;};},[detailOpen,detailMode,symbolOf(selection??{}),result?.experimentId,view]);
  async function savePlan(plan=draft) {const startedDraft=workspaceRef.current.draft;if(!plan)throw new Error('请先选择选股起点。');const next=await request<ScreenerPlan>('screeners.save',{plan});setPlans(await request<ScreenerPlan[]>('screeners.list'));window.dispatchEvent(new Event('v3-daily-plans-changed'));setWorkspace(value=>({...value,activePlanId:next.id,draft:value.draft===startedDraft?next:{...value.draft!,id:next.id,version:next.version}}));return next;}
  async function saveOnly(){if(saveBusy.current)return;saveBusy.current=true;setSaving(true);try{await savePlan();s.setNotice('方案已保存；尚未重新计算。');}catch(e){setError(errorText(e));}finally{saveBusy.current=false;setSaving(false);}}
  async function applyDaily(){if(saveBusy.current||!draft||dirty||!draft.id)return;saveBusy.current=true;setSaving(true);setError('');try{await request('dailyPlans.save',{planId:draft.id,name:draft.name,allocation:1,enabled:false});window.dispatchEvent(new Event('v3-daily-plans-changed'));s.setNotice(`已将 ${draft.name} v${draft.version} 复制到每日研究，请在那里配置资金并启用。`);}catch(e){setError(errorText(e));}finally{saveBusy.current=false;setSaving(false);}}
  async function run(allowPartial:boolean){if(saveBusy.current||busyJob(job))return;saveBusy.current=true;setSaving(true);setError('');try{const next=await savePlan();runningPlanId.current=next.id;const submitted=await request<JobEvent>('screeners.run',{planId:next.id,allowPartial});jobRef.current=submitted;setJob(submitted);s.setNotice(allowPartial?'已提交局部预览，数据不足证券会单独列出。':'已提交选股，等待真实计算结果。');if(submitted.status==='completed'){patchWorkspace({lastExperimentId:submitted.experimentId});setResultRevision(value=>value+1);}}catch(e){setError(errorText(e));}finally{saveBusy.current=false;setSaving(false);}}
  function start(mode:ScreenerPlan['mode']){setWorkspace(value=>({...value,activePlanId:undefined,draft:freshPlan(mode),lastExperimentId:undefined,view:'screen',conditionsCollapsed:false}));setResult(null);setSelection(null);setDetailOpen(false);setQuery({offset:0,limit:100});setSearch('');}
  async function choosePlan(id:string){setError('');try{const plan=await request<ScreenerPlan>('screeners.get',{id});setWorkspace(value=>({...value,activePlanId:id,draft:plan,lastExperimentId:undefined,view:'screen'}));setResult(null);setSelection(null);setDetailOpen(false);setQuery({offset:0,limit:100});setSearch('');}catch(e){setError(errorText(e));}}
  async function metadata(action:'copy'|'rename'|'favorite'|'archive'){if(!draft)return;try{let plan={...draft};if(action==='copy'){const name=await requestText('复制方案名称',`${draft.name} · 副本`);if(!name?.trim())return;plan={...plan,id:'',version:0,name:name.trim(),archived:false};}if(action==='rename'){const name=await requestText('方案名称',draft.name);if(!name?.trim())return;plan.name=name.trim();}if(action==='favorite')plan.favorite=!plan.favorite;if(action==='archive')plan.archived=!plan.archived;await savePlan(plan);if(action==='copy')patchWorkspace({lastExperimentId:undefined});}catch(e){setError(errorText(e));}}
  async function openAssets(){setAssetsOpen(true);setAssetsLoading(true);setAssetError('');try{setAssets(await request<ResearchAssetRef[]>('screeners.assets',{}));}catch(e){setAssetError(errorText(e));}finally{setAssetsLoading(false);}}
  function chooseAsset(id:string){const asset=assets.find(value=>value.id===id);if(!asset||!draft)return;const retained=draft.assets.filter(value=>asset.kind==='factor'?value.id!==asset.id&&!(value.kind==='factor'&&value.snapshot.factorId===asset.snapshot.factorId):value.kind!==asset.kind);const factors=[...draft.factors];if(asset.kind==='factor'){const factorId=String(asset.snapshot.factorId??'');if(!factorId){setAssetError('此成果没有有效因子标识，无法加入评分。');return;}if(!factors.some(value=>value.id===factorId))factors.push({id:factorId,direction:1,weight:1});}edit({assets:[...retained,asset],factors,mode:asset.kind==='factor'?'factors':'strategy'});setAssetsOpen(false);}
  async function addWatchlist(mode:'append'|'replace',onlySelected=false){if(adding||!watchlistId)return;setAdding(true);setError('');try{await request<Watchlist>('watchlists.add',{id:watchlistId,mode,...(onlySelected&&selection?{symbols:[symbolOf(selection)]}:{experimentId:result?.experimentId})});setWatchlists(await request<Watchlist[]>('watchlists.list'));s.setNotice(mode==='append'?'已追加到自选，重复证券和原备注保留。':'已用本次入选名单替换该自选组。');setResultRevision(value=>value+1);}catch(e){setError(errorText(e));}finally{setAdding(false);}}
  async function createWatchlist(){const name=await requestText('新自选组名称','我的自选');if(!name?.trim())return;try{const id=crypto.randomUUID();await request('watchlists.save',{watchlist:{id,name:name.trim(),symbols:[]}});setWatchlists(await request<Watchlist[]>('watchlists.list'));setWatchlistId(id);}catch(e){setError(errorText(e));}}
  const table:MarketTable|null=view==='watchlist'?watchTable:result?{...result,coverage:[],fieldLabels:{status:'判断结果',score:'综合评分',rank:'排名',reason:'入选／未入选原因'}}:null;
  const rows=table?.rows.map(row=>({...row,...(typeof row.status==='string'?{status:statusNames[row.status]??row.status}:{})}))??[];
  const displayedTable=table?{...table,rows}:null;
  const selectedIndex=rows.findIndex(row=>symbolOf(row)===symbolOf(selection??{}));
  const fields=[...new Set(['close','open','high','low','volume','amount','changeRatio','rawTurn','peTTM','pbMRQ',...(table?.columns??[])])].filter(field=>!['symbol','name','status','reason'].includes(field));
  const filteredPlans=plans.filter(plan=>(planFilter==='archived'?plan.archived:!plan.archived)&&(planFilter!=='favorite'||plan.favorite)&&plan.name.toLowerCase().includes(planSearch.toLowerCase())).sort((a,b)=>(b.lastUsedAt??b.updatedAt??'').localeCompare(a.lastUsedAt??a.updatedAt??''));
  const openRow=(row:JsonObject)=>{setSelection(row);if(view==='watchlist')setDetailMode('chart');setDetailOpen(true);};
  const weightSum=draft?.factors.reduce((sum,factor)=>sum+factor.weight,0)??0;
  const invalidFactors=draft?.mode==='factors'&&(!draft.factors.length||draft.factors.some(factor=>!Number.isFinite(factor.weight)||factor.weight<0)||weightSum<=0);
  const invalidStrategy=draft?.mode==='strategy'&&!draft.assets.some(asset=>asset.kind==='strategy');
  if(!ready)return <div className="r-page">{error?<><p role="alert">{error}</p><button onClick={()=>void load()}>重试读取选股工作区</button></>:<p role="status">正在恢复选股方案和已有结果…</p>}</div>;
  return <div className="r-screener-workspace"><header className="r-toolbar"><h1 className="r-screener-title">筛选与自选</h1><nav className="r-subtabs" aria-label="选股工作区视图"><button className={view==='screen'?'active':''} onClick={()=>{patchWorkspace({view:'screen'});setQuery({offset:0,limit:100});}}>选股</button><button className={view==='watchlist'?'active':''} onClick={()=>{patchWorkspace({view:'watchlist'});setQuery({offset:0,limit:100});}}>自选</button></nav><span className="r-spacer"/>{view==='screen'&&draft&&<><button disabled={saving} onClick={()=>void saveOnly()}>保存方案</button><button disabled={saving||busyJob(job)||invalidFactors||invalidStrategy||draft.archived} className="r-primary" onClick={()=>void run(false)}>{saving?'正在提交…':busyJob(job)?'正在运行…':'运行选股'}</button></>}</header>
    {error&&<p role="alert" className="r-screener-message">{error}</p>}
    {view==='screen'&&<><div className="r-toolbar"><input aria-label="搜索选股方案" placeholder="搜索方案" value={planSearch} onChange={event=>setPlanSearch(event.target.value)}/><select aria-label="方案分类" value={planFilter} onChange={event=>setPlanFilter(event.target.value)}><option value="recent">最近使用</option><option value="favorite">收藏</option><option value="archived">已归档</option></select><select aria-label="选择选股方案" disabled={saving} value={planId} onChange={event=>void choosePlan(event.target.value)}><option value="">{draft?'未保存的新方案':'选择已有方案'}</option>{filteredPlans.map(plan=><option value={plan.id} key={plan.id}>{plan.favorite?'★ ':''}{plan.name} · v{plan.version}</option>)}</select><details className="r-screener-plan-menu"><summary>方案操作</summary><div className="r-toolbar">{(['conditions','factors','strategy'] as const).map(mode=><button key={mode} disabled={saving} onClick={()=>start(mode)}>新建{({conditions:'条件',factors:'因子',strategy:'策略'})[mode]}方案</button>)}{draft&&<><button disabled={saving||dirty||!draft.id} title={dirty?'请先保存当前草稿':'复制已保存版本，不自动运行'} onClick={()=>void applyDaily()}>应用到每日研究</button>{(['copy','rename','favorite','archive'] as const).map(action=><button key={action} disabled={saving} onClick={()=>void metadata(action)}>{({copy:'复制',rename:'重命名',favorite:draft.favorite?'取消收藏':'收藏',archive:draft.archived?'取消归档':'归档'})[action]}</button>)}</>}</div></details></div>
      {!draft?<section className="r-screener-starts">{([['conditions','从条件开始','按数值、排名和交易日信号筛选。'],['factors','从因子开始','选择因子，设置方向和权重。'],['strategy','从策略开始','引用已有策略或模型，查看候选。']] as const).map(([mode,title,description])=><button key={mode} onClick={()=>start(mode)}><strong>{title}</strong><small>{description}</small></button>)}</section>:<><div className="r-toolbar"><strong>{draft.name}</strong><span className="r-note">{draft.id?`已保存 v${draft.version}`:'新方案'}{dirty?' · 配置已修改，旧结果未重算':''}</span><span className="r-spacer"/><label>数据日期 <input aria-label="选股日期" type="date" value={draft.date??''} onChange={event=>edit({date:event.target.value||undefined})}/></label><small>{draft.date?'指定交易日':'最近完整交易日'}</small></div><details className="r-screener-controls" open={!workspace.conditionsCollapsed} onToggle={event=>{if(event.currentTarget.open===!!workspace.conditionsCollapsed)patchWorkspace({conditionsCollapsed:!event.currentTarget.open});}}><summary>{({conditions:'条件',factors:'因子与条件',strategy:'策略与条件'})[draft.mode]} · {draft.conditions.children.length} 组／项</summary><div className="r-form-grid"><label className="r-field">数据来源<select aria-label="选股数据来源" value={draft.dataProjectId??''} onChange={event=>edit({dataProjectId:event.target.value||undefined})}><option value="">共享本地数据（无需项目）</option>{s.projects.map(project=><option key={project.id} value={project.id}>{project.name}</option>)}</select></label><label className="r-field">基础范围<select aria-label="选股基础范围" value={draft.universe.source} onChange={event=>edit({universe:{...draft.universe,source:event.target.value as ScreenerPlan['universe']['source']}})}><option value="all">全部覆盖证券</option><option value="manual">指定证券</option><option value="csi300">沪深 300</option><option value="csi500">中证 500</option></select></label><label className="r-field">最短上市天数<input aria-label="选股最短上市天数" type="number" min={0} value={draft.universe.minListingDays} onChange={event=>edit({universe:{...draft.universe,minListingDays:Number(event.target.value)}})}/></label><label className="r-check"><input type="checkbox" checked={draft.universe.excludeST} onChange={event=>edit({universe:{...draft.universe,excludeST:event.target.checked}})}/>排除 ST</label></div>{draft.universe.source==='manual'&&<SymbolEditor key={draft.id} symbols={draft.universe.symbols} onChange={symbols=>edit({universe:{...draft.universe,symbols}})}/>}
        <div className="r-toolbar"><button onClick={()=>void openAssets()}>选择研究成果</button><span className="r-note">固定来源版本 · 不修改原项目</span></div>{draft.assets.map(asset=><div className="r-toolbar" key={asset.id}><span>{asset.name}</span><small>{asset.projectName??'内置成果'} · {asset.revision}</small>{!asset.available&&<span>{asset.reason??'暂不可用'}</span>}<button aria-label={`移除成果${asset.name}`} onClick={()=>edit({assets:draft.assets.filter(value=>value.id!==asset.id),factors:asset.kind==='factor'?draft.factors.filter(value=>value.id!==String(asset.snapshot.factorId)):draft.factors})}>×</button></div>)}
        {draft.mode==='factors'&&<><table className="r-screener-weight-table"><thead><tr><th>因子</th><th>方向</th><th>权重</th><th>归一化占比</th></tr></thead><tbody>{draft.factors.map((factor,index)=><tr key={factor.id}><td>{draft.assets.find(asset=>asset.snapshot.factorId===factor.id)?.name??factor.id}</td><td><select aria-label={`${factor.id}方向`} value={factor.direction} onChange={event=>edit({factors:draft.factors.map((item,i)=>i===index?{...item,direction:Number(event.target.value) as 1|-1}:item)})}><option value={1}>越高越优</option><option value={-1}>越低越优</option></select></td><td><input aria-label={`${factor.id}权重`} type="number" min={0} step={0.1} value={factor.weight} onChange={event=>edit({factors:draft.factors.map((item,i)=>i===index?{...item,weight:Number(event.target.value)}:item)})}/></td><td>{weightSum>0&&factor.weight>=0?`${(factor.weight/weightSum*100).toFixed(1)}%`:'—'}</td></tr>)}</tbody></table>{invalidFactors&&<p className="r-note">至少选择一个因子；权重须非负，合计须大于零。缺失因子不会补零评分。</p>}</>}
        {draft.mode==='strategy'&&<p className="r-note">默认输出候选名单；此处不计算账户调仓信号，也不修改实际持仓。{invalidStrategy?'请先选择策略成果；模型可以作为附加成果。':''}</p>}
        <div className="r-toolbar"><label>排名参照<select aria-label="排名参照范围" value={draft.rankingReference} onChange={event=>edit({rankingReference:event.target.value as 'base'|'prefilter'})}><option value="base">基础范围过滤后</option><option value="prefilter">前置条件过滤后</option></select></label><label>最多入选<input aria-label="最多入选证券" type="number" min={1} value={draft.limit??30} onChange={event=>edit({limit:Number(event.target.value)})}/></label></div>{draft.rankingReference==='prefilter'&&<section><h3>前置条件</h3><p className="r-note">参照范围不包含后续排名条件本身。</p><ScreenerConditions value={draft.preconditions??emptyGroup()} onChange={preconditions=>edit({preconditions})} fields={fields}/></section>}<ScreenerConditions value={draft.conditions} onChange={conditions=>edit({conditions})} fields={fields}/><div className="r-toolbar"><button disabled={saving||busyJob(job)||invalidFactors||invalidStrategy||draft.archived} onClick={()=>void run(true)}>运行局部预览</button><small>数据不完整时保留无法判断名单，不能视为完整选股。</small></div></details></>}
      {job&&<p role="status" className="r-screener-message">{job.name} · {job.message}{busyJob(job)&&<button onClick={()=>void s.act(()=>request('jobs.cancel',{jobId:job.id}))}>取消运行</button>}</p>}
    </>}
    {assistantUndo&&<div className="r-toolbar"><span>本地助手条件修改</span><button disabled={JSON.stringify(draft)!==JSON.stringify(assistantUndo.after)} onClick={()=>{setWorkspace(value=>({...value,draft:assistantUndo.before}));setAssistantUndo(null);}}>撤销助手修改</button>{JSON.stringify(draft)!==JSON.stringify(assistantUndo.after)&&<small>草稿已有后续修改，保留当前内容。</small>}</div>}
    <div className="r-toolbar"><input aria-label="搜索已有选股结果" placeholder={view==='screen'?'在已有结果中搜索代码或名称':'在自选中搜索代码或名称'} value={search} onChange={event=>setSearch(event.target.value)}/>{view==='screen'&&<select aria-label="结果判断状态" value={resultStatus} onChange={event=>{setResultStatus(event.target.value);setQuery(value=>({...value,offset:0}));}}><option value="included">入选证券</option><option value="">全部判断</option><option value="excluded">未入选</option><option value="missing">数据不足</option><option value="outside">范围外</option></select>}<select aria-label="选股自选组" value={watchlistId} onChange={event=>{setWatchlistId(event.target.value);setQuery(value=>({...value,offset:0}));}}><option value="">选择自选组</option>{watchlists.map(list=><option key={list.id} value={list.id}>{list.name} · {list.symbols.length}</option>)}</select><button onClick={()=>void createWatchlist()}>新自选组</button>{view==='screen'&&<><button disabled={!result||!watchlistId||adding} onClick={()=>void addWatchlist('append')}>入选名单加入自选</button><details className="r-screener-plan-menu"><summary>名单操作</summary><div className="r-toolbar"><button disabled={!result||!selection||!watchlistId||adding} onClick={()=>void addWatchlist('append',true)}>所选证券加入自选</button><button disabled={!result||!watchlistId||adding} onClick={()=>{if(window.confirm('用本次入选名单替换所选自选组？原名单中未入选的证券将移除。'))void addWatchlist('replace');}}>替换自选名单</button></div></details></>}</div>
    {view==='screen'&&result&&<><div className="r-screener-counts"><span>范围 <strong>{result.counts.scope}</strong></span><span>有效 <strong>{result.counts.valid}</strong></span><span>入选 <strong>{result.counts.included}</strong></span><span>无法判断 <strong>{result.counts.missing}</strong></span><span>{result.asOfDate} · {result.status==='complete'?'完整结果':'局部预览'}</span>{(result.configChanged||dirty)&&<span>配置已变化，当前仍为旧结果</span>}</div>{result.message&&<p className="r-screener-message">{result.message}</p>}{result.diff&&<details><summary>与上次完整结果比较</summary><dl>{Object.entries(result.diff).map(([key,value])=><div key={key}><dt>{({added:'新增',removed:'退出',retained:'保留',scoreChanges:'可比评分变化',comparable:'评分可比'} as Record<string,string>)[key]??fieldLabel(key)}</dt><dd>{valueText(value,key)}</dd></div>)}</dl></details>}<div className="r-toolbar"><input aria-label="查询未入选证券原因" placeholder="输入代码，查看未入选原因" value={symbolSearch} onChange={event=>setSymbolSearch(event.target.value)}/><button disabled={!symbolSearch.trim()} onClick={()=>{setSelection({symbol:symbolSearch.trim()});setDetailMode('explanation');setDetailOpen(true);}}>查询判断原因</button></div></>}
    <section className="r-screener-results">{loading&&<p role="status">正在读取已有{view==='screen'?'结果':'自选行情'}…</p>}{displayedTable?<><MarketGrid key={view} preferenceKey={view==='watchlist'?'screener-watchlist':'screener'} table={displayedTable} selected={selectedIndex} onSelected={index=>openRow(rows[index])} onOpen={row=>{setSelection(row);setDetailMode('chart');setDetailOpen(true);}} query={query} onQuery={setQuery}/><div className="r-toolbar"><button disabled={!query.offset||loading} onClick={()=>setQuery(value=>({...value,offset:Math.max(0,(value.offset??0)-100)}))}>上一页</button><span>{table!.total?`${table!.offset+1}–${table!.offset+rows.length} / ${table!.total}`:'0'} 行 · {table!.asOfDate||'日期未提供'}</span><button disabled={loading||table!.offset+rows.length>=table!.total||!rows.length} onClick={()=>setQuery(value=>({...value,offset:(value.offset??0)+100}))}>下一页</button>{selection&&<button onClick={()=>setDetailOpen(value=>!value)}>{detailOpen?'收起股票详情':'展开股票详情'}</button>}</div></>:!loading&&<Empty title={view==='watchlist'?'选择或新建自选组':draft?'还没有本方案的结果':'选择一个起点'}>{view==='screen'?'恢复方案不会自动计算。检查配置后，明确点击运行选股。':'自选名单独立保存在本地。'}</Empty>}</section>
    {detailOpen&&selection&&<ScreenerDetail symbol={symbolOf(selection)} name={String(selection.name??'')} date={table?.asOfDate} height={workspace.detailHeight??300} onHeight={detailHeight=>patchWorkspace({detailHeight})} mode={detailMode} onMode={setDetailMode} onClose={()=>setDetailOpen(false)} onOpen={()=>w.open({kind:'quote',title:`${selection.name??symbolOf(selection)} · 行情`,instrument:{kind:'stock',symbol:symbolOf(selection)},date:table?.asOfDate})}><ScreenerExplanation value={explanation} loading={explainLoading} error={explainError} watchlist={view==='watchlist'}/></ScreenerDetail>}
    {assetsOpen&&<ScreenerAssetPicker items={assets.map(asset=>({key:asset.id,name:asset.name,kind:asset.kind,source:asset.projectName??'内置成果',version:asset.revision,available:asset.available,reason:asset.reason}))} loading={assetsLoading} error={assetError} onChoose={chooseAsset} onClose={()=>setAssetsOpen(false)}/>}</div>;
}
function ScreenerExplanation({value,loading,error,watchlist}:{value:JsonObject|null;loading:boolean;error:string;watchlist:boolean}) {
  if(watchlist)return <Empty title="自选名单没有本次选股判断">切回选股结果查看条件、排名和贡献。</Empty>;
  if(loading)return <p role="status">正在读取该证券的真实判断记录…</p>;
  if(error)return <p role="alert">{error}</p>;
  if(!value)return <Empty title="暂无判断记录"/>;
  return <div className="r-screener-explanation"><dl>{Object.entries(value).filter(([key,item])=>!['conditions','contributions'].includes(key)&&!Array.isArray(item)).map(([key,item])=><div key={key}><dt>{fieldLabel(key)}</dt><dd>{key==='status'?statusNames[String(item)]??String(item):valueText(item,key)}</dd></div>)}</dl>{['conditions','contributions'].map(key=>{const items=value[key];if(!Array.isArray(items)||!items.length)return null;const rows=items.filter((item):item is JsonObject=>!!item&&typeof item==='object'&&!Array.isArray(item)).map(row=>Object.fromEntries(Object.entries(row).filter(([field])=>field!=='id').map(([field,item])=>[({value:'实际值',rank:'排名',matched:'是否命中',field:'指标',factor:'因子',factorId:'因子',direction:'方向',weight:'权重',contribution:'评分贡献',score:'评分',percentile:'百分位'} as Record<string,string>)[field]??fieldLabel(field),field==='matched'?(item===true?'命中':item===false?'未命中':null):field==='field'?fieldLabel(String(item)):item])));return rows.length?<DataTable key={key} table={{name:key==='conditions'?'命中条件与实际值':'因子排名与贡献',columns:[...new Set(rows.flatMap(row=>Object.keys(row)))],rows}}/>:null;})}</div>;
}

function SymbolEditor({symbols,onChange}:{symbols:string[];onChange:(symbols:string[])=>void}) {
  const [text,setText]=useState(symbols.join(' '));const focused=useRef(false);
  useEffect(()=>{if(!focused.current)setText(symbols.join(' '));},[JSON.stringify(symbols)]);
  return <label className="r-field">证券代码<textarea aria-label="选股指定证券" rows={2} value={text} onFocus={()=>{focused.current=true;}} onBlur={()=>{focused.current=false;}} onChange={event=>{setText(event.target.value);onChange(event.target.value.split(/[\s,，;；]+/).filter(Boolean));}}/></label>;
}
