import React, { useEffect, useRef, useState } from "react";
import { PriceChart } from "./PriceChart";
import { Empty } from "./ui";

export interface AssetChoice {key:string;name:string;kind:string;source:string;version:string;available:boolean;reason?:string;}
export function ScreenerAssetPicker({items,loading,error,onChoose,onClose}:{items:AssetChoice[];loading:boolean;error:string;onChoose:(key:string)=>void;onClose:()=>void}) {
  const dialog=useRef<HTMLDialogElement>(null),[search,setSearch]=useState(""),[kind,setKind]=useState("");
  useEffect(()=>{dialog.current?.showModal();},[]);
  const matches=items.filter(item=>(!kind||item.kind===kind)&&`${item.name} ${item.source} ${item.version}`.toLowerCase().includes(search.toLowerCase()));
  return <dialog ref={dialog} className="r-screener-assets" aria-label="选择研究成果" onCancel={onClose}><header><div><h2>选择研究成果</h2><p>查看来源与版本，再加入当前方案。</p></div><button aria-label="关闭成果选择器" onClick={onClose}>×</button></header><div className="r-toolbar"><input autoFocus aria-label="搜索研究成果" placeholder="成果名称、项目或版本" value={search} onChange={event=>setSearch(event.target.value)}/><select aria-label="成果类型" value={kind} onChange={event=>setKind(event.target.value)}><option value="">所有成果</option><option value="factor">因子</option><option value="strategy">策略</option><option value="model">模型</option></select></div>{error&&<p role="alert">{error}</p>}{loading?<p role="status">正在读取已有研究成果…</p>:<div className="r-screener-asset-list">{matches.map(item=><button key={item.key} disabled={!item.available} onClick={()=>onChoose(item.key)}><span><strong>{item.name}</strong><small>{({factor:"因子",strategy:"策略",model:"模型"} as Record<string,string>)[item.kind]??item.kind} · {item.source}</small></span><span><small>版本 {item.version}</small>{!item.available&&<small>{item.reason||"此成果暂不可用"}</small>}</span></button>)}{!matches.length&&<Empty title="没有匹配的研究成果">调整搜索，或先在项目中保存研究成果。</Empty>}</div>}</dialog>;
}

export function ScreenerDetail({symbol,name,date,height,onHeight,mode,onMode,onClose,onOpen,children}:{symbol:string;name?:string;date?:string;height:number;onHeight:(value:number)=>void;mode:"chart"|"explanation";onMode:(mode:"chart"|"explanation")=>void;onClose:()=>void;onOpen:()=>void;children:React.ReactNode}) {
  const [maximized,setMaximized]=useState(false);
  const resize=(event:React.PointerEvent<HTMLDivElement>)=>{const target=event.currentTarget,start=event.clientY,initial=height;target.setPointerCapture(event.pointerId);const move=(next:PointerEvent)=>onHeight(Math.max(180,Math.min(750,initial+start-next.clientY)));const stop=()=>{target.removeEventListener("pointermove",move);target.removeEventListener("pointerup",stop);target.removeEventListener("pointercancel",stop);};target.addEventListener("pointermove",move);target.addEventListener("pointerup",stop);target.addEventListener("pointercancel",stop);};
  return <section className={`r-screener-detail${maximized?" is-maximized":""}`} style={maximized?undefined:{height}}><div className="r-screener-divider" role="separator" tabIndex={0} aria-label="调整股票详情高度" aria-orientation="horizontal" aria-valuemin={180} aria-valuemax={750} aria-valuenow={height} onPointerDown={resize} onKeyDown={event=>{if(event.key==='ArrowUp'||event.key==='ArrowDown'){event.preventDefault();onHeight(Math.max(180,Math.min(750,height+(event.key==='ArrowUp'?20:-20))));}}}/><div className="r-toolbar"><strong>{name||symbol}</strong><small>{symbol} · {date||"最新行情"}</small><nav className="r-subtabs" aria-label="股票详情视图"><button className={mode==='chart'?'active':''} onClick={()=>onMode('chart')}>行情</button><button className={mode==='explanation'?'active':''} onClick={()=>onMode('explanation')}>命中解释</button></nav><span className="r-spacer"/><button onClick={()=>setMaximized(value=>!value)}>{maximized?'还原详情':'最大化'}</button><button onClick={onOpen}>独立打开行情</button><button aria-label="收起股票详情" onClick={onClose}>×</button></div><div className="r-screener-detail-content">{mode==='chart'?<PriceChart key={symbol} embedded symbol={symbol} instrument={{kind:'stock',symbol,name}} asOfDate={date}/>:children}</div></section>;
}
