import React, {useEffect,useState} from 'react';
import {errorText,request} from './state';
export interface LocalAssistantStatus {
 enabled:boolean;runtimeInstalled:boolean;runtimeRunning:boolean;model:string;modelInstalled:boolean;modelsDirectory:string;
 installedModels:{model:string;sizeBytes:number;complete:boolean}[];loadedModels:{name?:string;model?:string;size?:number;size_vram?:number}[];
 candidates:{model:string;downloadBytes:number;resourceNote:string;sourceUrl:string}[];
 pull:{status:string;model:string|null;completed:number;total:number;error:string|null};message:string;
}
const size=(n:number)=>n>=1e9?`${(n/1e9).toFixed(1)} GB`:`${Math.round(n/1e6)} MB`;
export function SettingsLocalAssistant(){
 const [status,setStatus]=useState<LocalAssistantStatus|null>(null),[model,setModel]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let alive=true;void request<LocalAssistantStatus>('localAssistant.status').then(value=>{if(alive){setStatus(value);setModel(value.model);}}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[]);
 useEffect(()=>{if(status?.pull.status!=='running')return;let alive=true;const timer=setInterval(()=>{void request<LocalAssistantStatus>('localAssistant.status').then(value=>{if(alive)setStatus(value);}).catch(e=>{if(alive)setError(errorText(e));});},2000);return()=>{alive=false;clearInterval(timer);};},[status?.pull.status]);
 async function act(method:string,params?:object){if(busy)return;setBusy(true);setError('');try{setStatus(await request<LocalAssistantStatus>(method,params));}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 const candidate=status?.candidates.find(value=>value.model===model),installed=status?.installedModels.some(value=>value.model===model&&value.complete);
 return <section><h4>本地命令助手</h4><p className="r-note">在 Ctrl+K 中输入短指令，明确修改直接更新可撤销草稿，明确运行才提交任务。普通工具搜索始终可用；本地不可用时会明确提示，不转用在线服务。</p>{error&&<p role="alert">{error}</p>}{status?<><p role="status">{status.enabled?'已启用':'未启用'} · {status.runtimeInstalled?'运行环境已安装':'尚未安装 Ollama'} · {status.runtimeRunning?'本地服务运行中':'本地服务未运行'}</p><label className="r-field">本地模型<select aria-label="本地助手模型" value={model} disabled={busy||status.pull.status==='running'} onChange={event=>setModel(event.target.value)}>{status.candidates.map(value=><option key={value.model} value={value.model}>{value.model} · {size(value.downloadBytes)}{status.installedModels.some(item=>item.model===value.model&&item.complete)?' · 已安装':''}</option>)}</select></label>{candidate&&<p>{candidate.resourceNote}</p>}<p className="r-note">模型目录：{status.modelsDirectory}</p><div className="r-toolbar"><button disabled={busy||!status.runtimeInstalled||!installed||status.pull.status==='running'} onClick={()=>void act('localAssistant.enable',{model})}>启用所选模型</button>{!installed&&candidate&&<button disabled={busy||!status.runtimeInstalled||status.pull.status==='running'} onClick={()=>void act('localAssistant.pull',{model,confirmed:true})}>下载 {model}（约 {size(candidate.downloadBytes)}）</button>}<button disabled={busy||(!status.enabled&&!status.runtimeRunning)} onClick={()=>void act('localAssistant.disable')}>关闭并释放资源</button><button disabled={busy} onClick={()=>void act('localAssistant.status')}>刷新状态</button></div>{status.pull.status!=='idle'&&<p role="status">下载 {status.pull.model}：{({running:'进行中',completed:'已完成，请启用模型',failed:'失败'} as Record<string,string>)[status.pull.status]??status.pull.status}{status.pull.total>0?` · ${Math.min(100,Math.round(status.pull.completed/status.pull.total*100))}%`:''}{status.pull.error?` · ${status.pull.error}`:''}</p>}<p>{status.loadedModels.length?`内存中：${status.loadedModels.map(value=>`${value.name??value.model}（${size(value.size??0)}）`).join('、')}`:'当前没有已加载模型'}</p><p className="r-note">{status.message}</p></>:<p>正在读取本地环境…</p>}</section>;
}
