import React, { useEffect, useState } from 'react';
import type { WorkspaceState } from '../../../../../packages/contracts/src/research';
import { errorText, request } from './state';
type Display=Partial<Pick<WorkspaceState,'density'|'readingFontSize'|'sidebarWidth'|'aiWidth'|'sidebarVisible'|'aiVisible'|'rightPanel'>>;
export function SettingsProjectDisplay({projectId,defaults}:{projectId:string;defaults:WorkspaceState}){
  const [value,setValue]=useState<Display|null>(null),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{let alive=true;setValue(null);setError('');void request<{overrides:Display}>('workspace.project.get',{projectId}).then(result=>{if(alive){setValue(result.overrides);setSaved(JSON.stringify(result.overrides));}}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[projectId]);
  async function save(overrides:Display){setBusy(true);setError('');try{await request('workspace.project.save',{projectId,overrides});setValue(overrides);setSaved(JSON.stringify(overrides));window.dispatchEvent(new CustomEvent('v3-project-display-changed',{detail:{projectId}}));window.v3Research?.workspace?.broadcast({method:'workspace.project.preferences',params:{projectId}});setNotice('项目显示偏好已保存；全局默认保持不变。');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  const patch=(key:keyof Display,next:unknown)=>setValue(current=>({...current,[key]:next}));
  return <section><p className="r-note">仅覆盖当前项目的显示偏好，不改变研究参数或恢复旧标签。未勾选项沿用全局；当前视图临时调整仍优先。</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{value===null?<p>正在读取项目显示偏好…</p>:<>{([['density','表格密度'],['readingFontSize','阅读字号'],['sidebarVisible','研究目录'],['aiVisible','右侧区域'],['sidebarWidth','目录宽度'],['aiWidth','右栏宽度'],['rightPanel','右栏内容']] as const).map(([key,label])=><div className="r-setting-row" key={key}><label><input aria-label={`项目覆盖${label}`} type="checkbox" checked={key in value} onChange={event=>{if(event.target.checked)patch(key,defaults[key]??(key==='readingFontSize'?14:undefined));else {const next={...value};delete next[key];setValue(next);}}}/>{label}</label>{key in value?(key==='density'?<select aria-label="项目表格密度" value={value.density} onChange={event=>patch(key,event.target.value)}><option value="comfortable">标准 32px</option><option value="compact">紧凑 26px</option></select>:key==='rightPanel'?<select aria-label="项目右栏内容" value={value.rightPanel} onChange={event=>patch(key,event.target.value)}><option value="ai">研究助手</option><option value="parameters">完整参数</option></select>:key==='sidebarVisible'||key==='aiVisible'?<select aria-label={`项目${label}`} value={String(value[key])} onChange={event=>patch(key,event.target.value==='true')}><option value="true">显示</option><option value="false">隐藏</option></select>:<input aria-label={`项目${label}`} type="number" min={key==='readingFontSize'?12:key==='sidebarWidth'?170:280} max={key==='readingFontSize'?20:key==='sidebarWidth'?380:700} value={Number(value[key])} onChange={event=>patch(key,Number(event.target.value))}/>):<span className="r-note">沿用全局</span>}</div>)}<div className="r-toolbar"><button disabled={busy||JSON.stringify(value)===saved} onClick={()=>void save(value)}>保存项目显示偏好</button><button disabled={busy||!Object.keys(value).length} onClick={()=>void save({})}>恢复全局默认</button><button onClick={()=>window.dispatchEvent(new Event('v3-clear-view-display'))}>清除当前视图临时调整</button></div></>}</section>;
}
