import React, { useEffect, useState } from 'react';
import type { DailyResearchPlan, Watchlist } from '../../../../../packages/contracts/src/research';
import { errorText, request } from './state';
interface UpdateSettings {enabled:boolean;watchlistIds:string[];dailyPlanIds:string[]}
export function SettingsDataUpdates(){
  const [value,setValue]=useState<UpdateSettings|null>(null),[saved,setSaved]=useState(''),[watchlists,setWatchlists]=useState<Watchlist[]>([]),[plans,setPlans]=useState<DailyResearchPlan[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  useEffect(()=>{let alive=true;void Promise.all([request<{dataUpdates?:UpdateSettings}>('settings.get'),request<Watchlist[]>('watchlists.list'),request<DailyResearchPlan[]>('dailyPlans.list')]).then(([settings,groups,daily])=>{if(!alive)return;const next={enabled:false,watchlistIds:[],dailyPlanIds:[],...settings.dataUpdates};setValue(next);setSaved(JSON.stringify(next));setWatchlists(groups);setPlans(daily);}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[]);
  const toggle=(key:'watchlistIds'|'dailyPlanIds',id:string)=>setValue(current=>current?{...current,[key]:current[key].includes(id)?current[key].filter(value=>value!==id):[...current[key],id]}:current);
  return <>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<p className="r-note">默认按需获取。开启后，仅在程序运行时，于工作日 16 点后更新所选范围，每日最多尝试一次；不会启动选股或训练。</p>{!value?<p>正在读取更新偏好…</p>:<><label className="r-check"><input aria-label="启用盘后范围更新" type="checkbox" checked={value.enabled} onChange={event=>setValue({...value,enabled:event.target.checked})}/>开启盘后数据更新</label><section><h4>自选范围</h4>{watchlists.map(group=><label className="r-check" key={group.id}><input aria-label={`盘后更新自选${group.name}`} type="checkbox" checked={value.watchlistIds.includes(group.id)} onChange={()=>toggle('watchlistIds',group.id)}/>{group.name} · {group.symbols.length} 只</label>)}{!watchlists.length&&<p className="r-note">还没有自选组。</p>}</section><section><h4>每日研究范围</h4>{plans.map(plan=><label className="r-check" key={plan.id}><input aria-label={`盘后更新方案${plan.name}`} type="checkbox" checked={value.dailyPlanIds.includes(plan.id)} onChange={()=>toggle('dailyPlanIds',plan.id)}/>{plan.name} · 固定 v{plan.planVersion}</label>)}{!plans.length&&<p className="r-note">还没有每日研究方案。</p>}</section>{value.watchlistIds.filter(id=>!watchlists.some(group=>group.id===id)).map(id=><p key={id} className="r-note">已选自选组不可用 <button onClick={()=>toggle('watchlistIds',id)}>移除此范围</button></p>)}{value.dailyPlanIds.filter(id=>!plans.some(plan=>plan.id===id)).map(id=><p key={id} className="r-note">已选每日方案不可用 <button onClick={()=>toggle('dailyPlanIds',id)}>移除此范围</button></p>)}<p className="r-note">首次准备近 400 个自然日，已有数据增量更新。仅选择明确范围，不自动扩展为全市场；失败不会无限重试。</p><button disabled={busy||JSON.stringify(value)===saved||value.enabled&&!value.watchlistIds.length&&!value.dailyPlanIds.length} onClick={()=>{setBusy(true);setError('');void request<{dataUpdates?:UpdateSettings}>('settings.save',{settings:{dataUpdates:value}}).then(result=>{const next=result.dataUpdates??value;setValue(next);setSaved(JSON.stringify(next));setNotice('盘后更新偏好已保存，未立即启动研究。');}).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}>保存数据更新偏好</button></>}</>;
}
