import React, { useEffect, useRef, useState } from "react";
import type { WorkspaceState, ComputeSettings, EffectiveResources, DataSourceSettings } from "../../../../../packages/contracts/src/research";
import { errorText, request } from "./state";
import { useWorkspace } from "./workspace";
import { Field } from "./ui";

import { defaultShortcuts, eventShortcut, shortcutConflicts, shortcutLabels, type ShortcutAction } from "./shortcuts";

import { SettingsLocalAssistant } from './SettingsLocalAssistant';
import { SettingsProjectDisplay } from "./SettingsProjectDisplay";
import { SettingsAIOverrides } from "./SettingsAIOverrides";
import { SettingsDataUpdates } from "./SettingsDataUpdates";
import { SettingsTransfer } from "./SettingsTransfer";
import { SettingsResearchPresets } from "./SettingsResearchPresets";
import { SettingsNavigation } from "./SettingsNavigation";
import { SettingsStorage } from "./SettingsStorage";

type Section = "general" | "backup" | "appearance" | "workspace" | "charts" | "compute" | "sources" | "storage" | "presets" | "updates" | "ai" | "local";
const sections: {id:Section;title:string;keywords:string}[] = [
  {id:"general",title:"通用",keywords:"启动 关闭 托盘 更新 版本 通知"},
  {id:"appearance",title:"外观",keywords:"主题 浅色 深色 跟随系统 密度 行高 缩放 字号"},
  {id:"workspace",title:"工作区与快捷键",keywords:"目录 助手 侧栏 宽度 键盘"},
  {id:"charts",title:"行情与图表",keywords:"模板 默认 周期 证券 画线 十字线"},
  {id:"sources",title:"数据源",keywords:"日线 财务 板块 分时 微盘 通达信 免费 备用源"},
  {id:"storage",title:"数据与存储",keywords:"占用 空间 缓存 清理 目录"},
  {id:"updates",title:"数据更新",keywords:"盘后 按需 自动 自选 范围 定时"},
  {id:"compute",title:"计算与任务",keywords:"资源 并行 线程 优先 CPU"},
  {id:"presets",title:"研究模板",keywords:"预设 因子 处理 成本 费用 约束 验证"},
  {id:"backup",title:"备份与诊断",keywords:"设置 导入 导出 JSON 备份 诊断 本地"},
  {id:"local",title:"本地命令助手",keywords:"Ollama 本地 下载 模型 释放 Ctrl K"},
  {id:"ai",title:"AI 与研究助手",keywords:"模型 API 地址 密钥 温度 服务"},
];
interface ServiceSettings { general?:{checkUpdates:boolean};dataSources?:DataSourceSettings;dataSourceCapabilities?:{id:string;name:string;categories:string[];description:string}[];compute?:ComputeSettings;effectiveResources?:EffectiveResources;ai:{baseUrl:string;model:string;apiKey:string;temperature:number}; [key:string]:unknown; }
export function SettingsDialog({open,section:initialSection="appearance",close}:{open:boolean;section?:Section;close:()=>void}) {
  const w=useWorkspace(), prefs=w.globalPreferences??w.preferences, dialog=useRef<HTMLDialogElement>(null);
  const [displayScope,setDisplayScope]=useState<"global"|"project">("global");
  const [section,setSection]=useState<Section>(initialSection),[query,setQuery]=useState("");
  const [config,setConfig]=useState<ServiceSettings|null>(null),[saved,setSaved]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [compute,setCompute]=useState<ComputeSettings>({profile:"interactive"});
  const [computeSaved,setComputeSaved]=useState('');
  const [sources,setSources]=useState<DataSourceSettings|null>(null),[sourcesSaved,setSourcesSaved]=useState('');
  const [keys,setKeys]=useState({...defaultShortcuts,...prefs.shortcuts});
  useEffect(()=>{setKeys({...defaultShortcuts,...prefs.shortcuts});},[JSON.stringify(prefs.shortcuts)]);
  const keyErrors=shortcutConflicts(keys),keysDirty=JSON.stringify(keys)!==JSON.stringify({...defaultShortcuts,...prefs.shortcuts});

  const [update,setUpdate]=useState<{checkedAt:string;currentVersion:string;latestVersion?:string;available:boolean;prerelease?:boolean;url?:string;error?:string}|null>(null);
  const dirty=!!config&&JSON.stringify(config.ai)!==saved;
  useEffect(()=>{const node=dialog.current;if(!node)return;if(open){if(!node.open)node.showModal();setSection(initialSection);}else if(node.open)node.close();},[open,initialSection]);
  useEffect(()=>{if(!open||config)return;let alive=true;void request<ServiceSettings>("settings.get").then(value=>{if(alive){setConfig(value);setSources(value.dataSources??null);setSourcesSaved(JSON.stringify(value.dataSources??null));setSaved(JSON.stringify(value.ai));setCompute(value.compute??{profile:"interactive"});setComputeSaved(JSON.stringify(value.compute??{profile:"interactive"}));}}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[open,config]);
  async function preference(patch:Partial<WorkspaceState>){setError("");try{await (w.saveGlobalPreferences??w.savePreferences)(patch);setNotice("显示偏好已保存");}catch(e){setError(errorText(e));}}
  async function saveService(){if(!config||busy)return;setBusy(true);setError("");try{await request("settings.save",{settings:{ai:config.ai}});setSaved(JSON.stringify(config.ai));setNotice("AI 配置已保存，连接状态以实际请求为准。");window.dispatchEvent(new Event("v3-settings-saved"));}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function saveCompute(){if(busy)return;setBusy(true);setError("");try{const next=await request<ServiceSettings>("settings.save",{settings:{compute}});setConfig(current=>current?{...current,compute:next.compute,effectiveResources:next.effectiveResources}:next);setCompute(next.compute??compute);setComputeSaved(JSON.stringify(next.compute??compute));setNotice("资源偏好已保存，仅对后续任务生效。");}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function saveSources(){if(!sources||busy)return;setBusy(true);setError("");try{const next=await request<ServiceSettings>("settings.save",{settings:{dataSources:sources}});setSources(next.dataSources??sources);setSourcesSaved(JSON.stringify(next.dataSources??sources));setConfig(current=>current?{...current,dataSources:next.dataSources,dataSourceCapabilities:next.dataSourceCapabilities}:next);setNotice("数据源偏好已保存，后续请求按所选来源处理；已有数据不会自动迁移或重算。");}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  const matches=sections.filter(item=>`${item.title} ${item.keywords}`.toLowerCase().includes(query.toLowerCase()));
  const selected=matches.find(item=>item.id===section)??matches[0];
  return <dialog ref={dialog} className="r-settings-dialog" aria-labelledby="r-settings-title" onCancel={event=>{event.preventDefault();close();}}>
    <header><h2 id="r-settings-title">设置</h2><span className="r-spacer"/><span className="r-note">Esc 返回研究</span><button aria-label="关闭设置" onClick={close}>×</button></header>
    <div className="r-settings-layout"><aside><input aria-label="搜索设置" placeholder="搜索设置…" value={query} onChange={e=>setQuery(e.target.value)}/><nav aria-label="设置分类">{matches.map(item=><button key={item.id} aria-current={selected?.id===item.id?"page":undefined} onClick={()=>setSection(item.id)}>{item.title}</button>)}</nav><p className="r-note">仅展示当前已接入的设置。</p></aside>
    <main><h3>{selected?.title??"没有匹配设置"}</h3>{error&&<p role="alert">{error}</p>}{notice&&<p className="r-note" role="status">{notice}</p>}
    {selected?.id==="general"&&<><section><h4>启动与关闭</h4><p className="r-note">启动进入研究首页。关闭窗口时，有运行任务则进入托盘，空闲则退出；再次打开功能时恢复其草稿与已有结果。</p></section><section><h4>版本更新</h4>{config&&<div className="r-setting-row"><div><strong>自动检查新版本</strong><p>仅安装版每天最多检查一次；不自动下载或安装。</p></div><input aria-label="自动检查更新" type="checkbox" checked={config.general?.checkUpdates!==false} onChange={event=>{const checkUpdates=event.target.checked;setError('');void request<ServiceSettings>('settings.save',{settings:{general:{checkUpdates}}}).then(value=>{setConfig(current=>current?{...current,general:value.general??{checkUpdates}}:value);setNotice('更新检查偏好已保存。');}).catch(e=>setError(errorText(e)));}}/></div>}<button disabled={busy} onClick={()=>{setBusy(true);setError('');void request<NonNullable<typeof update>>('updates.check').then(setUpdate).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}>{busy?'正在检查…':'检查更新'}</button>{update&&<><p>当前版本 {update.currentVersion} · {update.latestVersion?`最新发布 ${update.latestVersion}${update.prerelease?' · 研究预览版':''}`:'未取得最新版本信息'}</p>{update.error?<p role="alert">{update.error}</p>:update.latestVersion&&<p role="status">{update.available?'有新版本，可前往发布页手动下载。':'当前未发现可用更新。'}</p>}<p className="r-note">检查时间：{new Date(update.checkedAt).toLocaleString('zh-CN')}</p>{update.url&&<button onClick={()=>void window.v3Research!.openExternal(update.url!)}>打开发布页</button>}</>}</section></>}
    {selected?.id==="local"&&<SettingsLocalAssistant/>}
    {selected?.id==="updates"&&<SettingsDataUpdates/>}
    {selected?.id==="presets"&&<SettingsResearchPresets/>}
    {selected?.id==="backup"&&<SettingsTransfer onImported={()=>setConfig(null)}/>}
    <SettingsStorage active={selected?.id==='storage'}/>
    {selected?.id==="appearance"&&<><p className="r-note">调整显示偏好，当前研究、图表和会话保持原位。</p><section><h4>主题</h4><div className="r-theme-options">{([['light','浅色'],['dark','深色'],['system','跟随系统']] as const).map(([value,label])=><button key={value} aria-pressed={prefs.theme===value} onClick={()=>void preference({theme:value})}><span className={`r-theme-preview ${value}`} aria-hidden="true"><i/><i/><i/></span>{label}{prefs.theme===value&&<span aria-hidden="true"> ✓</span>}</button>)}</div></section><section><h4>大小与阅读</h4><div className="r-setting-row"><div><strong>整体缩放</strong><p>调整控件、表格和图表的整体大小。</p></div><select aria-label="整体缩放" value={prefs.zoomFactor??1} onChange={event=>void preference({zoomFactor:Number(event.target.value)})}>{[.8,.9,1,1.1,1.25,1.5].map(value=><option key={value} value={value}>{Math.round(value*100)}%</option>)}</select></div><div className="r-setting-row"><div><strong>阅读字号</strong><p>仅调整正文、研报与助手回复，不改变控件和表格。</p></div><select aria-label="阅读字号" value={prefs.readingFontSize??14} onChange={event=>void preference({readingFontSize:Number(event.target.value)})}>{[12,13,14,15,16,18,20].map(value=><option key={value} value={value}>{value} px</option>)}</select></div><p className="r-reading-preview">阅读预览：先检查数据覆盖，再查看研究结果。</p></section><section><h4>界面密度</h4><div className="r-setting-row"><div><strong>表格行高</strong><p>标准 32px，紧凑 26px；只改变表格行高。</p></div><div className="r-toolbar">{([['comfortable','标准'],['compact','紧凑']] as const).map(([value,label])=><button key={value} aria-pressed={prefs.density===value} onClick={()=>void preference({density:value})}>{label}</button>)}</div></div></section></>}
    {selected?.id==="workspace"&&<><label className="r-field">显示设置适用范围<select aria-label="显示设置适用范围" value={displayScope} onChange={event=>setDisplayScope(event.target.value as 'global'|'project')}><option value="global">全局默认</option><option value="project" disabled={!w.active?.projectId}>当前项目</option></select></label>{displayScope==='project'&&w.active?.projectId?<SettingsProjectDisplay key={w.active.projectId} projectId={w.active.projectId} defaults={prefs}/>:<><SettingsNavigation value={prefs.navigation} save={navigation=>void preference({navigation})}/><section><h4>侧栏</h4><div className="r-setting-row"><div><strong>研究目录</strong><p>显示项目与全局功能入口。</p></div><input aria-label="显示研究目录" type="checkbox" checked={prefs.sidebarVisible!==false} onChange={e=>void preference({sidebarVisible:e.target.checked})}/></div><div className="r-setting-row"><div><strong>研究助手</strong><p>关闭设置后保留当前会话与草稿。</p></div><input aria-label="显示研究助手" type="checkbox" checked={prefs.aiVisible!==false} onChange={e=>void preference({aiVisible:e.target.checked})}/></div></section><section><h4>快捷键</h4><p className="r-note">点击输入框后按组合键。输入框和编辑浮层保留原有键盘操作。</p>{(Object.keys(defaultShortcuts) as ShortcutAction[]).map(action=><div className="r-setting-row" key={action}><label htmlFor={`shortcut-${action}`}>{shortcutLabels[action]}</label><div className="r-toolbar"><input id={`shortcut-${action}`} aria-label={`${shortcutLabels[action]}快捷键`} readOnly value={keys[action]} placeholder="未绑定" onKeyDown={event=>{if(event.key==='Tab')return;event.preventDefault();event.stopPropagation();if(event.key==='Escape'){event.currentTarget.blur();return;}const binding=eventShortcut(event.nativeEvent);if(binding)setKeys(value=>({...value,[action]:binding}));}}/><button aria-label={`清除${shortcutLabels[action]}快捷键`} onClick={()=>setKeys(value=>({...value,[action]:''}))}>清除</button></div></div>)}{keyErrors.map(message=><p key={message} role="alert">{message}</p>)}<div className="r-toolbar"><button disabled={!keysDirty||!!keyErrors.length} className="r-primary" onClick={()=>void preference({shortcuts:keys})}>保存快捷键</button><button onClick={()=>setKeys({...defaultShortcuts})}>恢复默认键位</button></div></section><section><h4>布局偏好</h4><p className="r-note">布局只保存侧栏、密度、宽度和分栏方式。应用时保留当前研究标签，不恢复旧证券、项目或会话。</p><div className="r-toolbar"><button onClick={()=>window.dispatchEvent(new Event('v3-save-layout'))}>保存当前显示布局</button></div>{Object.keys(prefs.layoutPresets??{}).map(name=><div className="r-setting-row" key={name}><strong>{name}</strong><div className="r-toolbar"><button onClick={()=>window.dispatchEvent(new CustomEvent('v3-apply-layout',{detail:name}))}>应用</button><button onClick={()=>{const next={...prefs.layoutPresets};delete next[name];void preference({layoutPresets:next});}}>删除</button></div></div>)}{!!Object.keys(prefs.presets??{}).length&&<p className="r-note">旧版含具体对象的布局已保留为历史记录，不会自动载入。</p>}</section></>}</>}
    {selected?.id==="charts"&&<><p className="r-note">各图的十字线与缩放独立。切换证券保留当前图配置，临时修改不更新默认模板。</p><section><h4>新图默认模板</h4>{(['stock','index','industry','concept'] as const).map(kind=>{const templates=prefs.chartDefaults;const value=templates?.[kind]??(templates?.period?templates:null);return <div className="r-setting-row" key={kind}><strong>{({stock:"股票",index:"指数",industry:"行业",concept:"概念"})[kind]}</strong><span>{value?"已保存模板":"使用初始设置"}</span></div>;})}<p className="r-note">在行情图中调整周期、指标和价格轴，再点击“保存为默认”。模板不包含证券或画线。</p></section></>}
    {selected?.id==="sources"&&<><p className="r-note">按数据类别选择来源。文件来源需要先导入资料；这里不会自动下载数据或启动研究。</p>{!sources?<p role="status">当前服务未返回数据源配置。</p>:<><section><h4>分类来源</h4>{([['daily','股票日线',['baostock','akshare','file']],['financials','财务数据',['baostock','file']],['boards','行业与概念',['akshare','file']],['intraday','分时行情',['akshare','file']],['microcap','微盘指数',['tdx','file']]] as const).map(([key,label,choices])=><div className="r-setting-row" key={key}><strong>{label}</strong><select aria-label={`${label}数据源`} value={sources[key]} onChange={event=>setSources({...sources,[key]:event.target.value})}>{choices.map(choice=><option key={choice} value={choice}>{config?.dataSourceCapabilities?.find(value=>value.id===choice)?.name??({baostock:'BaoStock',akshare:'AKShare',tdx:'通达信',file:'本地文件'})[choice]}</option>)}</select></div>)}<div className="r-setting-row"><div><strong>看盘备用源</strong><p>允许兼容来源失败时切换备用源；正式研究保持明确来源。</p></div><input aria-label="允许看盘备用源" type="checkbox" checked={sources.quoteFallback} onChange={event=>setSources({...sources,quoteFallback:event.target.checked})}/></div><button className="r-primary" disabled={busy||JSON.stringify(sources)===sourcesSaved} onClick={()=>void saveSources()}>保存数据源偏好</button></section><section><h4>来源能力</h4>{config?.dataSourceCapabilities?.map(source=><div key={source.id}><strong>{source.name}</strong><p className="r-note">{source.description}</p></div>)}</section></>}</>}
    {selected?.id==="compute"&&<><p className="r-note">为后续任务分配资源。正在运行的任务保持原设置，同一项目及数据目录仍需串行。</p>{!config?<p>正在读取资源设置…</p>:!config.effectiveResources?<p role="status">当前后端未提供实际资源设置，请重启开发服务后再试。</p>:<><section><h4>资源档位</h4><div className="r-compute-profiles">{([['interactive','交互优先','1 个计算任务 · 每任务最多 2 线程'],['balanced','均衡','1 个计算任务 · 每任务最多 4 线程'],['compute','计算优先','2 个计算任务 · 每任务最多 4 线程']] as const).map(([profile,label,description])=><button key={profile} aria-pressed={compute.profile===profile} onClick={()=>setCompute({profile})}><strong>{label}</strong><span>{description}</span></button>)}</div><p className="r-note">以上为请求上限，实际分配会按可用核心数收缩。</p><details><summary>高级资源限制</summary><Field label="最多并行计算任务"><input type="number" min={1} step={1} value={compute.maxConcurrentJobs??(compute.profile==='compute'?2:1)} onChange={e=>setCompute({...compute,maxConcurrentJobs:Number(e.target.value)})}/></Field><Field label="每任务最多线程"><input type="number" min={1} step={1} value={compute.threadsPerJob??(compute.profile==='interactive'?2:4)} onChange={e=>setCompute({...compute,threadsPerJob:Number(e.target.value)})}/></Field></details><div className="r-toolbar"><button className="r-primary" disabled={busy||JSON.stringify(compute)===computeSaved||[compute.maxConcurrentJobs,compute.threadsPerJob].some(value=>value!==undefined&&(!Number.isInteger(value)||value<1))} onClick={()=>void saveCompute()}>{busy?"正在保存…":"保存资源设置"}</button><span className="r-note">{JSON.stringify(compute)!==computeSaved?"尚未应用当前修改":"已应用到后续任务"}</span></div></section><section><h4>当前生效值</h4><dl className="r-settings-shortcuts"><div><dt>可用核心</dt><dd>{config.effectiveResources.availableCpus}</dd></div><div><dt>并行计算任务</dt><dd>{config.effectiveResources.maxConcurrentJobs}</dd></div><div><dt>每任务线程上限</dt><dd>{config.effectiveResources.threadsPerJob}</dd></div><div><dt>Qlib 内核 / Optuna 并行试验</dt><dd>{config.effectiveResources.qlibKernels} / {config.effectiveResources.optunaParallelTrials}</dd></div></dl>{config.effectiveResources.limitations.map(message=><p className="r-note" key={message}>{message}</p>)}</section></>}</>}
    {selected?.id==="ai"&&<><p className="r-note">在线或本地兼容 API。保存配置不会启动研究，也不会自动切换服务。</p>{config?<form onSubmit={e=>{e.preventDefault();void saveService();}}><Field label="兼容 API 地址"><input value={config.ai.baseUrl} onChange={e=>setConfig({...config,ai:{...config.ai,baseUrl:e.target.value}})}/></Field><Field label="模型名称"><input value={config.ai.model} onChange={e=>setConfig({...config,ai:{...config.ai,model:e.target.value}})}/></Field><Field label="API Key"><input type="password" autoComplete="off" value={config.ai.apiKey} onChange={e=>setConfig({...config,ai:{...config.ai,apiKey:e.target.value}})}/></Field><Field label="Temperature"><input type="number" min={0} max={2} step={.1} value={config.ai.temperature} onChange={e=>setConfig({...config,ai:{...config.ai,temperature:Number(e.target.value)}})}/></Field><div className="r-toolbar"><span>{dirty?"有未保存修改，关闭后草稿保留":"配置未改动"}</span><button type="submit" className="r-primary" disabled={busy||!dirty||!Number.isFinite(config.ai.temperature)}>{busy?"正在保存…":"保存 AI 配置"}</button></div></form>:<p>正在读取服务设置…</p>}</>}
    {config&&<SettingsAIOverrides active={selected?.id==="ai"} defaultAI={config.ai} defaultDirty={dirty}/>}
    </main></div>
  </dialog>;
}
