import React, { useEffect, useState } from 'react';
import type { JsonObject, ResearchPreset } from '../../../../../packages/contracts/src/research';
import { errorText, request } from './state';
import { presetLabels } from './ResearchPresetToolbar';
import { costsDefaults, CostsEditor, factorDefaults, FactorProcessingEditor, portfolioDefaults, PortfolioEditor, validationDefaults, ValidationEditor } from './configuration';
const defaults={factorProcessing:factorDefaults,costs:costsDefaults,portfolio:portfolioDefaults,validation:validationDefaults};
export function SettingsResearchPresets(){
  const [category,setCategory]=useState<ResearchPreset['category']>('factorProcessing'),[items,setItems]=useState<ResearchPreset[]>([]),[id,setId]=useState(''),[name,setName]=useState(''),[value,setValue]=useState<JsonObject>(structuredClone(factorDefaults)),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function load(){setItems(await request<ResearchPreset[]>('researchPresets.list'));}
  useEffect(()=>{void load().catch(e=>setError(errorText(e)));},[]);
  function fresh(next=category){setCategory(next);setId('');setName('');setValue(structuredClone(defaults[next]));setNotice('');}
  async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <><p className="r-note">预设只保存参数副本。研究编辑器中明确选用后才复制到当前草稿，不改变旧配置。</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="r-toolbar"><select aria-label="研究预设类别" value={category} disabled={busy} onChange={event=>fresh(event.target.value as ResearchPreset['category'])}>{Object.entries(presetLabels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><select aria-label="已有研究预设" value={id} disabled={busy} onChange={event=>{const item=items.find(item=>item.id===event.target.value);if(!item){fresh();return;}setId(item.id);setName(item.name);setValue({...structuredClone(defaults[category]),...structuredClone(item.value)});}}><option value="">新预设</option>{items.filter(item=>item.category===category).map(item=><option key={item.id} value={item.id}>{item.name} · v{item.revision}</option>)}</select></div><label className="r-field">预设名称<input aria-label="研究预设名称" value={name} onChange={event=>setName(event.target.value)}/></label>{category==='factorProcessing'&&<FactorProcessingEditor value={value} onChange={setValue} presets={false}/>} {category==='costs'&&<CostsEditor value={value} onChange={setValue} presets={false}/>} {category==='portfolio'&&<PortfolioEditor value={value} onChange={setValue} presets={false}/>} {category==='validation'&&<><p className="r-note">验证预设不包含训练、验证、测试的六个固定日期。</p><ValidationEditor value={value} onChange={setValue} dates={{}} onDates={()=>{}} presets={false} showDates={false}/></>}<div className="r-toolbar"><button className="r-primary" disabled={busy||!name.trim()} onClick={()=>void act(async()=>{const saved=await request<ResearchPreset>('researchPresets.save',{preset:{id:id||undefined,name:name.trim(),category,value}});await load();setId(saved.id);setNotice('预设已保存，已有研究配置保持不变。');})}>保存研究预设</button><button disabled={busy} onClick={()=>fresh()}>新建预设</button>{id&&<button disabled={busy} onClick={()=>void act(async()=>{await request('researchPresets.delete',{id});await load();fresh();setNotice('预设已删除，已复制到研究的配置保留。');})}>删除此预设</button>}</div></>;
}
