import React, { useEffect, useRef, useState } from 'react';
import { errorText, request } from './state';

interface StoragePaths {dataDirectory:string;newProjectDirectory:string;message?:string}
interface StorageEntry {projectId:string|null;name?:string;path?:string;status:string;categories?:Record<string,{bytes:number;shared:boolean}>}
const categories:Record<string,string>={data:'研究数据',experiments:'实验与固定输入',cache:'可重建缓存',exports:'导出文件'};
function size(bytes:number){if(bytes<1024)return `${bytes} B`;if(bytes<1024**2)return `${(bytes/1024).toFixed(1)} KB`;if(bytes<1024**3)return `${(bytes/1024**2).toFixed(1)} MB`;return `${(bytes/1024**3).toFixed(2)} GB`;}
export function SettingsStorage({active}:{active:boolean}) {
  const [entries,setEntries]=useState<StorageEntry[]|null>(null),[busy,setBusy]=useState(false),[clearing,setClearing]=useState<string|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [paths,setPaths]=useState<StoragePaths|null>(null),[savedPaths,setSavedPaths]=useState(''),[pathBusy,setPathBusy]=useState(false);
  useEffect(()=>{if(!active||paths)return;void request<{effectiveStorage?:StoragePaths}>('settings.get').then(value=>{if(value.effectiveStorage){setPaths(value.effectiveStorage);setSavedPaths(JSON.stringify(value.effectiveStorage));}}).catch(e=>setError(errorText(e)));},[active]);
  const pending=useRef<{id:string;cancelled:boolean}|null>(null),mounted=useRef(true);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;const read=pending.current;if(read){read.cancelled=true;void request('reads.cancel',{readId:read.id}).catch(()=>{});}};},[]);
  function cancel(){const read=pending.current;if(!read)return;read.cancelled=true;setNotice('已请求停止检查。');void request('reads.cancel',{readId:read.id}).catch(e=>setError(errorText(e)));}
  async function inspect(){if(pending.current)return;const read={id:crypto.randomUUID(),cancelled:false};pending.current=read;setBusy(true);setError('');setNotice('');try{const rows=await request<StorageEntry[]>('storage.inspect',{readId:read.id});if(mounted.current&&!read.cancelled){setEntries(rows);setNotice('占用检查完成；共享目录只计算一次。');}}catch(e){if(mounted.current&&!read.cancelled)setError(errorText(e));}finally{if(pending.current===read)pending.current=null;if(mounted.current)setBusy(false);}}
  async function clear(entry:StorageEntry){if(clearing!==null)return;const key=entry.projectId??'shared';setClearing(key);setError('');try{const value=await request<{cleared:boolean;bytes:number;message:string;references?:{kind:string;id:string}[]}>('storage.clearCache',{projectId:entry.projectId});if(!mounted.current)return;setNotice(value.message+(value.cleared?`（${size(value.bytes)}）`:value.references?.length?`，共 ${value.references.length} 处引用。`:''));if(value.cleared)setEntries(rows=>rows?.map(row=>row.projectId===entry.projectId?{...row,categories:{...row.categories,cache:{bytes:0,shared:false}}}:row)??null);}catch(e){if(mounted.current)setError(errorText(e));}finally{if(mounted.current)setClearing(null);}}
  return <div hidden={!active}><section><h4>默认目录</h4>{paths?<>{([['dataDirectory','数据主目录','data'],['newProjectDirectory','新项目默认目录','projectDefault']] as const).map(([key,label,purpose])=><label className="r-field" key={key}>{label}<div className="r-toolbar"><input aria-label={label} value={paths[key]} onChange={event=>setPaths({...paths,[key]:event.target.value})}/><button disabled={pathBusy} onClick={()=>{setPathBusy(true);void window.v3Research!.chooseDirectory({purpose}).then(path=>{if(path)setPaths({...paths,[key]:path});}).catch(e=>setError(errorText(e))).finally(()=>setPathBusy(false));}}>选择{label}</button></div></label>)}<p className="r-note">{paths.message??'目录变更用于后续资料，不自动迁移已有项目或研报。'}这些本机路径不包含在设置包中。</p><button disabled={pathBusy||busy||clearing!==null||JSON.stringify(paths)===savedPaths||!paths.dataDirectory.trim()||!paths.newProjectDirectory.trim()} onClick={()=>{setPathBusy(true);setError('');void request<{effectiveStorage?:StoragePaths}>('settings.save',{settings:{storage:{dataDirectory:paths.dataDirectory,newProjectDirectory:paths.newProjectDirectory}}}).then(value=>{if(value.effectiveStorage){setPaths(value.effectiveStorage);setSavedPaths(JSON.stringify(value.effectiveStorage));}setEntries(null);setNotice('默认目录已保存；已有资料未迁移。可重新检查占用。');}).catch(e=>setError(errorText(e))).finally(()=>setPathBusy(false));}}>保存默认目录</button></>:<p className="r-note">当前服务尚未返回目录配置。</p>}</section><p className="r-note">手动检查各项目的本地占用。切换设置分类不会重新扫描。</p><div className="r-toolbar"><button disabled={busy||clearing!==null} onClick={()=>void inspect()}>{busy?'正在检查占用…':entries?'刷新占用':'检查存储占用'}</button>{busy&&<button onClick={cancel}>停止检查</button>}</div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{entries?.map(entry=><section key={entry.projectId??'shared'}><h4>{entry.name??'不可用项目'}</h4><p className="r-note" style={{overflowWrap:'anywhere'}}>{entry.path}</p>{entry.status!=='ready'?<p>项目位置不可用，未计算占用。</p>:<><dl className="r-settings-shortcuts">{Object.entries(entry.categories??{}).map(([key,value])=><div key={key}><dt>{categories[key]??key}</dt><dd>{value.shared?'共享目录，已在前项计入':size(value.bytes)}</dd></div>)}</dl><button disabled={busy||clearing!==null||!entry.categories?.cache?.bytes} onClick={()=>void clear(entry)}>{clearing===(entry.projectId??'shared')?'正在清理…':'清理可重建缓存'}</button></>}</section>)}<p className="r-note">清理前会检查运行任务和产物引用；行情、固定输入和实验不会被清理。</p></div>;
}
