import React, { useState } from "react";
import type { JsonObject, JsonValue } from "../../../../../packages/contracts/src/research";
import { errorText, request } from "./state";
import { DataTable } from "./ui";
interface ImportPreview {package:JsonObject;differences:{section:string;key:string;current:JsonValue;incoming:JsonValue}[];layoutConflicts:string[];}
export function SettingsTransfer({onImported}:{onImported:()=>void}) {
  const [preview,setPreview]=useState<ImportPreview|null>(null),[diagnostics,setDiagnostics]=useState<JsonObject|null>(null),[conflict,setConflict]=useState<'keep'|'replace'>('keep'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  async function act(fn:()=>Promise<void>){if(busy)return;setBusy(true);setError('');try{await fn();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  const exportJson=async(value:JsonObject,name:string)=>{const path=await window.v3Research!.exportFile({format:'json',content:JSON.stringify(value,null,2),suggestedName:name});if(path)setNotice(`已保存到本地：${path}`);};
  return <>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<section><h4>设置包</h4><p className="r-note">导出显示、快捷键和可复用设置，不包含密钥、会话、项目路径或研究数据。</p><div className="r-toolbar"><button disabled={busy} onClick={()=>void act(async()=>exportJson(await request<JsonObject>('settings.export'),'V3设置.json'))}>导出设置包</button><button disabled={busy} onClick={()=>void act(async()=>{const paths=await window.v3Research!.chooseFiles({purpose:'settings'});if(!paths[0])return;setPreview(await request<ImportPreview>('settings.importPreview',{path:paths[0]}));setConflict('keep');})}>选择设置包并预览</button></div>{preview&&<><DataTable table={{name:'导入前差异',columns:['分类','设置','当前值','导入值'],rows:preview.differences.map(item=>({'分类':item.section,'设置':item.key,'当前值':item.current,'导入值':item.incoming}))}}/>{preview.layoutConflicts.length>0&&<><p>同名布局：{preview.layoutConflicts.join('、')}</p><label className="r-field">同名布局处理<select aria-label="同名布局处理" value={conflict} onChange={event=>setConflict(event.target.value as 'keep'|'replace')}><option value="keep">保留本机同名布局</option><option value="replace">替换为导入布局</option></select></label></>}<div className="r-toolbar"><button disabled={busy} className="r-primary" onClick={()=>void act(async()=>{await request('settings.import',{package:preview.package,conflict});setPreview(null);setNotice('已导入设置；当前研究对象保持不变。');window.dispatchEvent(new Event('v3-workspace-preferences-refresh'));onImported();})}>应用预览中的设置</button><button onClick={()=>setPreview(null)}>取消导入</button></div></>}</section><section><h4>本地诊断</h4><p className="r-note">先查看将导出的内容，再保存本地文件；不会自动上传。</p><button disabled={busy} onClick={()=>void act(async()=>setDiagnostics(await request<JsonObject>('diagnostics.preview')))}>预览诊断信息</button>{diagnostics&&<><pre className="r-diagnostics-preview">{JSON.stringify(diagnostics,null,2)}</pre><button disabled={busy} onClick={()=>void act(()=>exportJson(diagnostics,'V3本地诊断.json'))}>导出这份诊断信息</button></>}</section></>;
}
