import React, { useEffect, useRef, useState } from 'react';
import type { DailyResearchPlan, JsonObject, SimulationAccount, SimulationBinding, SimulationBindingSource } from '../../../../../packages/contracts/src/research';
import { request } from './state';
import { useWorkspace } from './workspace';
import { Field, valueText } from './ui';
import { accountRef } from './SelectionPositionsSourceEditor';

type Mutate = (operation: string, params: object) => Promise<SimulationAccount>;
type Run = (work: () => Promise<void>) => void;
interface Props { account: SimulationAccount; disabled: boolean; mutate: Mutate; run: Run; }
interface Preview { name: string; source: SimulationBindingSource; sourceVersion: string | null; snapshot: JsonObject; }

export function SimulationBindings({ account, disabled, mutate, run }: Props) {
  const w = useWorkspace();
  const [plans, setPlans] = useState<DailyResearchPlan[]>([]);
  const [sourceKey, setSourceKey] = useState('');
  const [allocation, setAllocation] = useState('100');
  const [preview, setPreview] = useState<{ bindingId?: string; value: Preview } | null>(null);
  const sources = [...plans.map(p => ({ key: JSON.stringify(['daily', p.id]), label: `每日方案 · ${p.name}`, source: { kind: 'dailyPlan' as const, dailyPlanId: p.id } })), ...w.strategies.map(s => ({ key: JSON.stringify(['strategy', s.projectId, s.id]), label: `项目策略 · ${s.name} · ${s.projectId}`, source: { kind: 'strategy' as const, projectId: s.projectId, strategyId: s.id } }))];
  const source = sources.find(s => s.key === sourceKey)?.source;
  const total = account.bindings?.reduce((n, b) => n + b.allocation, 0);
  useEffect(() => { setPreview(null); }, [account.revision]);
  return <section><h2>策略绑定与固定版本</h2><p className="r-note">新版本只管理后续新开仓；旧仓按入场版本退出。停新开仓、转手工和清仓是独立操作。</p>
    {account.bindings === undefined ? <p>旧账户未记录绑定版本，不能推断为当前策略。请先显式迁入。</p> : <>{!account.bindings.length && <p>尚未绑定策略，账户可保留现金。</p>}<div className="simulation-grid">{account.bindings.map(b => <BindingCard key={`${b.id}:${account.revision}`} binding={b} disabled={disabled} run={run} mutate={mutate} onPreview={() => run(async () => { const value = await request<Preview>('simulation.accounts.bindings.preview', { ...accountRef(account), bindingId: b.id }); setPreview({ bindingId: b.id, value }); })} />)}</div><p className="r-note">已分配 {total === undefined ? '未知' : `${(total * 100).toFixed(2)}%`}。未分配资金保留为现金。</p>
    <details><summary>添加策略绑定</summary><div className="r-toolbar"><button disabled={disabled} onClick={() => run(async () => setPlans(await request<DailyResearchPlan[]>('dailyPlans.list')))}>读取每日方案</button><select aria-label="绑定来源" disabled={disabled} value={sourceKey} onChange={e => { setSourceKey(e.target.value); setPreview(null); }}><option value="">选择每日方案或项目策略</option>{sources.map(s => <option key={s.key} value={s.key}>{s.label}</option>)}</select><label>资金占比 % <input aria-label="新绑定资金占比" type="number" min="0" max="100" value={allocation} disabled={disabled} onChange={e => setAllocation(e.target.value)} /></label><button disabled={disabled || !source} onClick={() => run(async () => { const value = await request<Preview>('simulation.accounts.bindings.preview', { ...accountRef(account), source }); setPreview({ value }); })}>预览来源版本</button><button disabled={disabled || !source || allocation === '' || !Number.isFinite(Number(allocation)) || Number(allocation) < 0 || Number(allocation) > 100} onClick={() => run(async () => { await mutate('bindings.save', { source, allocation: Number(allocation) / 100, allowNewEntries: true }); setSourceKey(''); })}>绑定来源当前版本</button></div></details></>}
    {preview && <section className="simulation-card"><h3>{preview.value.name} · 待采用来源 {preview.value.sourceVersion ?? '版本未知'}</h3>{preview.bindingId && <><p>当前固定来源版本：{account.bindings?.find(b => b.id === preview.bindingId)?.versions.find(v => v.id === account.bindings?.find(b => b.id === preview.bindingId)?.currentVersionId)?.sourceVersion ?? '未知'}</p><details><summary>当前固定参数</summary><pre className="simulation-code">{JSON.stringify(account.bindings?.find(b => b.id === preview.bindingId)?.versions.find(v => v.id === account.bindings?.find(b => b.id === preview.bindingId)?.currentVersionId)?.snapshot ?? null, null, 2)}</pre></details></>}<details open><summary>待采用参数</summary><pre className="simulation-code">{JSON.stringify(preview.value.snapshot, null, 2)}</pre></details><div className="r-toolbar">{preview.bindingId && <button disabled={disabled || preview.value.sourceVersion === null} onClick={() => run(async () => { await mutate('bindings.adopt', { bindingId: preview.bindingId, expectedSourceVersion: preview.value.sourceVersion }); setPreview(null); })}>采用预览版本 · 保留旧仓规则</button>}<button disabled={disabled} onClick={() => setPreview(null)}>关闭预览</button></div></section>}
  </section>;
}
function BindingCard({ binding, disabled, run, mutate, onPreview }: { binding: SimulationBinding; disabled: boolean; run: Run; mutate: Mutate; onPreview: () => void }) {
  const [allocation, setAllocation] = useState(String(binding.allocation * 100));
  const version = binding.versions.find(v => v.id === binding.currentVersionId);
  return <article className="simulation-card"><h3>{binding.name}</h3><p className="r-note">{binding.source.kind === 'dailyPlan' ? '每日方案' : '项目策略'} · 当前来源版本 {version?.sourceVersion ?? '未知'} · {binding.allowNewEntries ? '允许新开仓' : '已停新开仓'}</p><div className="r-toolbar"><label>占比 % <input type="number" min="0" max="100" aria-label={`${binding.name}资金占比`} disabled={disabled} value={allocation} onChange={e => setAllocation(e.target.value)} /></label><button disabled={disabled || allocation === '' || !Number.isFinite(Number(allocation)) || Number(allocation) < 0 || Number(allocation) > 100 || Number(allocation) === binding.allocation * 100} onClick={() => run(async () => { await mutate('bindings.save', { bindingId: binding.id, allocation: Number(allocation) / 100 }); })}>保存占比</button><button disabled={disabled} onClick={() => run(async () => { await mutate('bindings.save', { bindingId: binding.id, allowNewEntries: !binding.allowNewEntries }); })}>{binding.allowNewEntries ? '停止新开仓' : '允许新开仓'}</button><button disabled={disabled} onClick={onPreview}>预览新版本</button></div><details><summary>保留的固定版本（{binding.versions.length}）</summary>{binding.versions.map(v => <details key={v.id}><summary>{v.id === binding.currentVersionId ? '当前 · ' : ''}{v.sourceVersion ?? '来源版本未知'} · {v.createdAt}</summary><p>{v.id}</p><pre className="simulation-code">{JSON.stringify(v.snapshot, null, 2)}</pre></details>)}</details></article>;
}
export function SimulationOwnership({ account, disabled, mutate, run }: Props) {
  const [chosen, setChosen] = useState<string[]>([]);
  const [confirm, setConfirm] = useState<'manual' | 'liquidate' | null>(null);
  useEffect(() => { setChosen([]); setConfirm(null); }, [account.revision]);
  return <section><h2>当前持仓归属</h2>{account.ownership === undefined ? <p>旧记录未保存归属与入场版本，迁入后默认手工管理。</p> : !account.ownership.length ? <p>当前没有持仓归属记录。</p> : <><div className="r-table-scroll"><table className="simulation-table"><thead><tr><th>选择</th><th>证券 / 管理</th><th>数量 / 可卖 / 待到账</th><th>绑定与入场版本</th><th>成本总额</th></tr></thead><tbody>{account.ownership.map(o => <tr key={o.id}><td><input type="checkbox" aria-label={`选择归属 ${o.symbol} ${o.id}`} disabled={disabled} checked={chosen.includes(o.id)} onChange={() => { setConfirm(null); setChosen(ids => ids.includes(o.id) ? ids.filter(id => id !== o.id) : [...ids, o.id]); }} /></td><td>{o.symbol}<small>{o.management === 'manual' ? '手工管理' : '固定规则管理'}</small></td><td>{o.quantity} / {o.sellableQuantity} / {o.pendingQuantity}</td><td>{o.bindingId ? account.bindings?.find(b => b.id === o.bindingId)?.name ?? '绑定记录未知' : '无策略绑定'}<small>{o.entryVersionId ?? '入场版本未知'}</small></td><td>{valueText(o.costBasis)}</td></tr>)}</tbody></table></div><div className="r-toolbar"><button disabled={disabled || !chosen.length} onClick={() => setConfirm('manual')}>所选归属转为手工管理</button><button disabled={disabled || !chosen.length} onClick={() => setConfirm('liquidate')}>明确清仓所选归属…</button></div>{confirm && <div className="simulation-danger"><p>{confirm === 'manual' ? '转手工后不再按原策略自动管理，持仓数量保持原值。' : '仅对所选归属登记清仓意图，推进时按可卖数量和实际行情执行；不会立即变为现金，未成交不会伪报成功。'}已选 {chosen.length} 项。</p><div className="r-toolbar"><button disabled={disabled} onClick={() => run(async () => { await mutate(confirm === 'manual' ? 'ownership.transferToManual' : 'ownership.liquidate', { ownershipIds: chosen }); setConfirm(null); })}>{confirm === 'manual' ? '确认转手工' : '确认登记清仓意图'}</button><button disabled={disabled} onClick={() => setConfirm(null)}>返回</button></div></div>}</>}</section>;
}

// Keep the original payload after an uncertain failure, including its original revision.
export function useStableRequest() {
  const pending = useRef<{ key: string; payload: object } | null>(null);
  return { get(key: string, payload: object) { if (pending.current?.key !== key) pending.current = { key, payload: { ...payload, requestId: crypto.randomUUID() } }; return pending.current.payload; }, clear() { pending.current = null; } };
}
export function SimulationCashFlow({ account, disabled, mutate, run }: Props) {
  const [direction, setDirection] = useState<'deposit' | 'withdraw'>('deposit');
  const [amount, setAmount] = useState(''); const [note, setNote] = useState('');
  const [confirm, setConfirm] = useState(false); const stable = useStableRequest();
  const valid = amount !== '' && Number.isFinite(Number(amount)) && Number(amount) > 0 && (direction !== 'withdraw' || Number(amount) <= account.cash);
  const known = account.valuationStatus === 'known' && typeof account.unitNav === 'number' && account.unitNav > 0;
  return <details><summary>入金 / 出金</summary><p className="r-note">生效时点：{account.asOfDate ? `${account.asOfDate} 已完成收盘` : `${account.startDate} 开始前`}。外部资金单独记账，单位净值剔除入出金。出金只使用可用现金，不自动卖出。网络失败后请保留此表单重试同一次操作；换账户、关闭页面或重启后，先核对流水与余额再决定是否重新提交。</p>{!known && <p role="status">估值或单位净值未知，暂不可入出金。</p>}<div className="r-form-grid"><Field label="方向"><select value={direction} disabled={disabled} onChange={e => { setDirection(e.target.value as 'deposit' | 'withdraw'); setConfirm(false); stable.clear(); }}><option value="deposit">入金</option><option value="withdraw">出金</option></select></Field><Field label="金额（元）"><input type="number" min="0.01" step="0.01" value={amount} disabled={disabled} onChange={e => { setAmount(e.target.value); setConfirm(false); stable.clear(); }} /></Field><Field label="备注"><input value={note} disabled={disabled} onChange={e => { setNote(e.target.value); setConfirm(false); stable.clear(); }} /></Field></div><button disabled={disabled || !known || !valid} onClick={() => setConfirm(true)}>核对资金操作</button>{confirm && <div className="r-toolbar"><span>确认{direction === 'deposit' ? '入金' : '出金'} {amount} 元 · {account.asOfDate ?? `${account.startDate} 开始前`}</span><button disabled={disabled || !known || !valid} onClick={() => run(async () => { const key = JSON.stringify([direction, amount, note]); const payload = stable.get(key, { ...accountRef(account), expectedRevision: account.revision, direction, amount: Number(amount), note }); await mutate('cashFlows.create', payload); stable.clear(); setAmount(''); setConfirm(false); })}>确认记账 / 失败后重试</button><button disabled={disabled} onClick={() => setConfirm(false)}>返回</button></div>}</details>;
}
export function SimulationCopy({ account, disabled, mutate, run, onCreated }: Props & { onCreated: (account: SimulationAccount) => void }) {
  const [name, setName] = useState(`${account.name} 副本`); const [date, setDate] = useState(account.asOfDate ?? '');
  const stable = useStableRequest(); const legacy = !!account.projectId;
  return <details><summary>{legacy ? '将旧账户复制迁入全局' : '历史修正 · 创建分支'}</summary><p className="r-note">{legacy ? '保留原账户和历史。无法确定的归属与版本明确列为未知，迁入持仓默认手工管理。' : '从所选日收盘之后继续。要修正某一日，请选择它之前已完成的交易日；原账户历史保留。日期必须存在已保存收盘记录。'}</p><p className="r-note">网络失败请保留表单重试；换账户、关闭或重启后先检查账户列表，避免重复复制。本页面不保证跨重启保留请求编号。</p><div className="r-form-grid"><Field label="新账户名称"><input value={name} disabled={disabled} onChange={e => { setName(e.target.value); stable.clear(); }} /></Field>{!legacy && <Field label="从该日收盘之后继续"><input type="date" max={account.asOfDate ?? undefined} value={date} disabled={disabled} onChange={e => { setDate(e.target.value); stable.clear(); }} /></Field>}</div><button disabled={disabled || !name.trim() || (!legacy && (!date || !account.asOfDate || date > account.asOfDate))} onClick={() => run(async () => { const payload = stable.get(JSON.stringify([name, date]), legacy ? { source: accountRef(account), expectedRevision: account.revision, name: name.trim() } : { ...accountRef(account), expectedRevision: account.revision, fromDate: date, name: name.trim() }); const created = await mutate(legacy ? 'importLegacy' : 'branch', payload); stable.clear(); onCreated(created); })}>{legacy ? '复制迁入全局 / 重试' : '创建分支 / 重试'}</button></details>;
}
