import React, { useEffect, useRef, useState } from "react";
import type { DataCoverage, Experiment, ExperimentDetails, JsonObject, MarketOverview, MarketQuery, MarketTable, ResearchObjectRef, ResearchTable, SavedScreener, ScreenFilter, StockPanorama, Watchlist, WorkspacePanel } from "../../../../../packages/contracts/src/research";
import { errorText, request, useResearch } from "./state";
import { useWorkspace } from "./workspace";
import { DataTable, Empty, Field, Heading, Plot, valueText, fieldLabel, tableReportHtml, tableValue, tableNumber } from "./ui";
import { PagedExperimentTable } from "./PagedTable";
import { PriceChart } from "./PriceChart";
import { PositionsEditor } from "./SelectionPanel";
import { PortfolioEditor, object, portfolioDefaults } from "./configuration";
export function Coverage({ items }: { items: DataCoverage[] }) { return <details className="r-coverage"><summary>数据日期与覆盖 · {items.length} 项</summary>{items.map((c,i) => <div className="r-coverage-row" key={i}><strong>{c.label || c.dataset}</strong><span>{c.source}</span><span>{c.startDate || "—"} — {c.endDate || "—"}</span><span>{c.status === "available" ? "可用" : c.status === "partial" ? "部分覆盖" : "未取得"}{c.estimated ? " · 估算" : ""}</span><p>{c.message}</p></div>)}</details>; }
function experimentDescription(experiment: Experiment) {
 const params=experiment.parameters; const kind=experiment.kind;
 if(kind==="backtest.run") { const method=({single_factor:"单因子",multi_factor:"多因子",model_score:"模型评分"} as Record<string,string>)[String(params.template)]??"策略"; const frequency=({daily:"每日",weekly:"每周",monthly:"每月"} as Record<string,string>)[String(params.rebalance)]; return [method+"回测",typeof params.topN==="number"?`${params.topN}只持仓`:null,frequency?`${frequency}调仓`:null].filter(Boolean).join(" · "); }
 if(kind==="selection.run")return Array.isArray(params.strategies)?`${params.strategies.length}个策略合并选股 · 调仓清单`:"每日选股 · 目标组合与调仓清单";
 if(kind==="factor.analyze")return `因子分析${Array.isArray(params.factorIds)?` · ${params.factorIds.length}个因子`:""} · 有效性与分组表现`;
 if(kind==="model.train")return `${String(params.model??"模型")}训练 · 按时间验证`;
 if(kind==="optimize.run")return "参数寻优 · 验证集选参与独立测试";
 return kind==="data.import"?"数据导入":"数据更新";
}
export function TodayPanel() { const s = useResearch(); const w = useWorkspace(); return <div className="r-page"><Heading title="今日工作台" description="继续研究，检查启用策略，生成今天的选股清单。" /><div className="r-today-actions"><button onClick={() => w.open({ kind:"selection",title:"每日选股" })}><strong>每日选股</strong><span>启用策略 → 合并目标 → 调仓清单</span></button><button onClick={() => w.open({ kind:"market",title:"市场概况" })}><strong>观察市场</strong><span>指数、行业、广度与个股</span></button><button onClick={() => w.open({ kind:"screener",title:"筛选与自选" })}><strong>筛选与自选</strong><span>保存筛选方案，连接研究股票池</span></button></div><h2>继续研究</h2>{w.strategies.length ? <div className="r-strategy-list">{w.strategies.map(st => <button key={`${st.projectId}:${st.id}`} onClick={() => w.open({ kind:"strategy",title:st.name,projectId:st.projectId,strategyId:st.id })}><strong>{st.name}</strong><span>{s.projects.find(p => p.id === st.projectId)?.name}</span><span>{st.enabled ? `已启用 · 资金 ${Math.round(st.allocation*100)}%` : "草稿 · 未启用"}</span><span>打开 →</span></button>)}</div> : <Empty title="开始第一项研究">在左侧新建或打开项目；市场、自选和实际持仓可以直接使用。</Empty>}<div className="r-toolbar"><h2>近期实验</h2><button onClick={() => w.open({kind:"compare",title:"实验比较"})}>跨策略比较</button></div><div className="r-experiment-list">{s.experiments.slice(0,12).map(e => <button key={`${e.projectId}:${e.id}`} onClick={() => w.open({kind:"experiment",title:e.name,projectId:e.projectId,strategyId:e.strategyId,experimentId:e.id})}><strong>{e.name}</strong><span title={e.summary}>{experimentDescription(e)}</span><time>{new Date(e.createdAt).toLocaleString("zh-CN")}</time></button>)}</div><h2 className="r-section-heading">待处理任务</h2>{s.jobs.filter(j => ["failed","interrupted","running","queued"].includes(j.status)).slice(0,6).map(j => <p key={j.id} className="r-note">{j.name} · {j.message}</p>)}</div>; }
export function MarketPanel({ screening }: { screening: boolean }) {
 const s = useResearch(); const w = useWorkspace(); const [overview,setOverview]=useState<MarketOverview|null>(null); const [table,setTable]=useState<MarketTable|null>(null); const [query,setQuery]=useState<MarketQuery>(()=>({ offset:0,limit:100,...object(w.preferences.tablePreferences?.marketQuery) })); const [search,setSearch]=useState(String(object(w.preferences.tablePreferences?.marketQuery).search??"")); const [loading,setLoading]=useState(false);
 const [watchlists,setWatchlists]=useState<Watchlist[]>([]); const [screeners,setScreeners]=useState<SavedScreener[]>([]); const [field,setField]=useState("close"); const [operator,setOperator]=useState<ScreenFilter["operator"]>("gte"); const [value,setValue]=useState(""); const [selected,setSelected]=useState(0); const [name,setName]=useState(""); const [target,setTarget]=useState("");
 useEffect(()=>{ void w.savePreferences({tablePreferences:{...w.preferences.tablePreferences,marketQuery:query as JsonObject}}); },[JSON.stringify(query)]);
 useEffect(()=>{ const timer=setTimeout(()=>setQuery(q=>({...q,search,offset:0})),260);return()=>clearTimeout(timer);},[search]);
 useEffect(()=>{void s.act(async()=>{const [wl,sc]=await Promise.all([request<Watchlist[]>("watchlists.list"),request<SavedScreener[]>("screeners.list")]);setWatchlists(wl);setScreeners(sc);if(!screening)setOverview(await request<MarketOverview>("market.overview"));});},[screening,s.revision]);
 useEffect(()=>{let alive=true;setLoading(true);void s.act(async()=>{const result=await request<MarketTable>("market.screen",query);if(alive){setTable(result);setSelected(0);if(result.rows[0])choose(result.rows[0]);}}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[JSON.stringify(query),s.revision]);
 async function allRows(){ const rows:JsonObject[]=[]; let offset=0; while(true){const page=await request<MarketTable>("market.screen",{...query,offset,limit:500});rows.push(...page.rows);if(!page.rows.length||rows.length>=page.total)return { ...page, rows };offset+=page.rows.length;} }
 const choose=(row:JsonObject)=>{const symbol=String(row.symbol??row.code??"");if(symbol)w.linkStock(symbol);};
 return <div className="r-page"><Heading title={screening?"筛选与自选":"市场概况"} description="查询本地真实覆盖；代码、中文名称和拼音搜索覆盖全部分页。" />{overview&&<><div className="r-metrics">{Object.entries(overview.summary).map(([k,v])=><div key={k}><span>{fieldLabel(k)}</span><strong>{tableValue(v,k,"市场概况")}</strong></div>)}</div>{overview.indices.length>0&&<DataTable table={{name:"指数",columns:Object.keys(overview.indices[0]),rows:overview.indices}}/>}{overview.industries.length>0&&<DataTable table={{name:"行业",columns:Object.keys(overview.industries[0]),rows:overview.industries}}/>}{overview.breadth.length>0&&<DataTable table={{name:"市场广度",columns:Object.keys(overview.breadth[0]),rows:overview.breadth}}/>}</>}
 <div className="r-toolbar"><input aria-label="全市场搜索" placeholder="代码 / 名称 / 拼音，跨全部页面搜索" value={search} onChange={e=>setSearch(e.target.value)}/><input aria-label="查询日期" type="date" value={query.date??""} onChange={e=>setQuery({...query,date:e.target.value||undefined,offset:0})}/><select aria-label="选择自选组" value={query.watchlistId??""} onChange={e=>setQuery({...query,watchlistId:e.target.value||undefined,offset:0})}><option value="">全市场 / 全部覆盖</option>{watchlists.map(wl=><option key={wl.id} value={wl.id}>{wl.name}</option>)}</select><select aria-label="加载筛选方案" value="" onChange={e=>{const sc=screeners.find(x=>x.id===e.target.value);if(sc){setQuery({...sc.query,offset:0});setSearch(sc.query.search??"");}}}><option value="">已保存方案</option>{screeners.map(sc=><option key={sc.id} value={sc.id}>{sc.name}</option>)}</select></div>
 <details open={screening}><summary>筛选条件 · {(query.filters??[]).length} 项</summary><div className="r-toolbar"><select aria-label="筛选字段" value={field} onChange={e=>setField(e.target.value)}>{[...new Set(["close",...(table?.columns??[])])].map(k=><option key={k} value={k}>{table?.fieldLabels?.[k]??fieldLabel(k)}</option>)}</select><select aria-label="筛选运算" value={operator} onChange={e=>setOperator(e.target.value as ScreenFilter["operator"])}>{[["gte","≥"],["gt",">"],["lte","≤"],["lt","<"],["eq","等于"],["ne","不等于"],["contains","包含"]].map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><input aria-label="筛选值" value={value} onChange={e=>setValue(e.target.value)}/><button disabled={!value.trim()} onClick={()=>{setQuery({...query,offset:0,filters:[...(query.filters??[]),{field,operator,value:operator==="contains"||!Number.isFinite(Number(value))?value:Number(value)}]});setValue("");}}>添加条件</button><select aria-label="条件关系" value={query.match??"all"} onChange={e=>setQuery({...query,match:e.target.value as "all"|"any",offset:0})}><option value="all">满足全部</option><option value="any">满足任一</option></select></div><div className="r-chips">{query.filters?.map((f,i)=><button key={i} onClick={()=>setQuery({...query,offset:0,filters:query.filters!.filter((_,j)=>j!==i)})}>{fieldLabel(f.field)} {f.operator} {valueText(f.value)} ×</button>)}</div></details>
 <div className="r-toolbar"><input aria-label="保存名称" placeholder="筛选方案 / 自选组名称" value={name} onChange={e=>setName(e.target.value)}/><button disabled={!name.trim()} onClick={()=>void s.act(async()=>{await request("screeners.save",{screener:{id:crypto.randomUUID(),name,query:{...query,offset:0}}});setScreeners(await request("screeners.list"));s.setNotice("筛选方案已保存");})}>保存筛选方案</button><button disabled={!name.trim()||loading} onClick={()=>void s.act(async()=>{const result=await allRows();await request("watchlists.save",{watchlist:{id:crypto.randomUUID(),name,symbols:result.rows.map(r=>String(r.symbol??r.code)).filter(Boolean)}});setWatchlists(await request("watchlists.list"));s.setNotice(`已保存 ${result.rows.length} 只到自选组`);})}>结果存为自选组</button>{query.watchlistId&&<button onClick={()=>void s.act(async()=>{await request("watchlists.delete",{id:query.watchlistId});setWatchlists(await request("watchlists.list"));setQuery({...query,watchlistId:undefined,offset:0});})}>删除当前自选组</button>}<button onClick={()=>w.open({kind:"stock",title:"联动个股",id:"stock:linked"},"right")}>打开联动个股</button></div>
 <div className="r-toolbar"><select aria-label="目标策略股票池" value={target} onChange={e=>setTarget(e.target.value)}><option value="">选择目标策略股票池</option>{w.strategies.map(st=><option key={st.id} value={st.id}>{st.name}</option>)}</select>{([false,true] as const).map(dynamic=><button disabled={!target} key={String(dynamic)} onClick={()=>void s.act(async()=>{const st=w.strategies.find(x=>x.id===target)!;const rows=dynamic?[]:(await allRows()).rows;await request("strategies.save",{projectId:st.projectId,strategy:{id:st.id,universe:{...st.universe,name:name||"筛选股票池",source:dynamic?"all":"manual",symbols:rows.map(r=>String(r.symbol??r.code)),query:dynamic?query:undefined}}});await w.reload();s.setNotice(dynamic?"动态条件已保存到策略股票池":"完整静态名单已保存到策略股票池");})}>{dynamic?"保存动态条件池":"保存静态名单池"}</button>)}</div>
 {loading&&<p role="status">正在读取市场数据…</p>}{table&&<><MarketGrid table={table} selected={selected} onSelected={i=>{setSelected(i);choose(table.rows[i]);}} onOpen={row=>w.open({kind:"stock",title:`${row.name??""} ${row.symbol??row.code}`,symbol:String(row.symbol??row.code)})} query={query} onQuery={setQuery}/><div className="r-toolbar"><button disabled={!query.offset} onClick={()=>setQuery({...query,offset:Math.max(0,(query.offset??0)-100)})}>上一页</button><span>{table.total?`${table.offset+1}–${table.offset+table.rows.length} / ${table.total}`:"0"} 行 · {table.asOfDate||"暂无日期"}</span><button disabled={table.offset+table.rows.length>=table.total} onClick={()=>setQuery({...query,offset:(query.offset??0)+100})}>下一页</button>{(["csv","xlsx"] as const).map(format=><button key={format} disabled={loading} onClick={()=>void s.act(async()=>{const all=await allRows();const result=await request<{path:string}>("exports.table",{table:all,name:name||"筛选结果",format});await window.v3Research!.exportFile({format,sourcePath:result.path,suggestedName:`${name||"筛选结果"}.${format}`});})}>导出全部 {format.toUpperCase()}</button>)}</div><Coverage items={table.coverage}/></>}
 </div>;
}
export function marketValue(value: unknown, key: string) { return tableValue(value,key,"市场"); }
function MarketGrid({table,selected,onSelected,onOpen,query,onQuery}:{table:MarketTable;selected:number;onSelected:(i:number)=>void;onOpen:(r:JsonObject)=>void;query:MarketQuery;onQuery:(q:MarketQuery)=>void}) {
 const w=useWorkspace(); const saved=object(w.preferences.tablePreferences?.market);
 const strings=(value:unknown)=>Array.isArray(value)?value.filter((x):x is string=>typeof x==="string"):[];
 const defaultColumns=["symbol","name","rawClose","changeRatio","amount","rawTurn","industry",table.columns.includes("peTTM")?"peTTM":"pettm",table.columns.includes("pbMRQ")?"pbMRQ":"pbmrq","fund_net_amount","chip_benefit"].filter(k=>table.columns.includes(k));
 const [order,setOrder]=useState<string[]>(strings(saved.order));
 const [visible,setVisible]=useState<string[]|null>(Array.isArray(saved.visible)?strings(saved.visible):strings(saved.order).length?strings(saved.order):null);
 const [widths,setWidths]=useState<JsonObject>(object(saved.widths));
 const [pinned,setPinned]=useState<string[]>(["symbol",...strings(saved.pinned).filter(k=>k!=="symbol")]);
 const [columnsOpen,setColumnsOpen]=useState(false); const [columnSearch,setColumnSearch]=useState("");
 const selectedColumns=visible??defaultColumns;
 const allColumns=[...new Set([...order,...defaultColumns,...table.columns])].filter(k=>table.columns.includes(k));
 const columns=[...pinned.filter(k=>table.columns.includes(k)&&selectedColumns.includes(k)),...allColumns.filter(k=>selectedColumns.includes(k)&&!pinned.includes(k))];
 const width=(key:string)=>Number(widths[key]??(key==="symbol"?94:key==="name"?100:key==="industry"?116:106));
 const label=(key:string)=>({rawClose:"现价（元）",changeRatio:"涨跌幅",amount:"成交额",rawTurn:"换手率",fund_net_amount:"主力净流入",chip_benefit:"获利比例"} as Record<string,string>)[key]??table.fieldLabels?.[key]??fieldLabel(key);
 const persist=(o=order,wi=widths,p=pinned,v=selectedColumns)=>void w.savePreferences({tablePreferences:{market:{order:o,widths:wi,pinned:p,visible:v}}});
 const pinStyle=(key:string,index:number)=>pinned.includes(key)?{position:"sticky" as const,left:columns.slice(0,index).reduce((n,c)=>n+width(c),0)}:{};
 return <><div className="r-toolbar"><button onClick={()=>setColumnsOpen(v=>!v)}>列设置（{columns.length}）</button><span>↑ ↓ 选择 · Enter 查看个股</span></div>{columnsOpen&&<section className="r-column-settings"><div className="r-toolbar"><input aria-label="搜索可选列" placeholder="查找字段名称" value={columnSearch} onChange={e=>setColumnSearch(e.target.value)}/><button onClick={()=>{setVisible(defaultColumns);setOrder(defaultColumns);setPinned(["symbol"]);persist(defaultColumns,widths,["symbol"],defaultColumns);}}>恢复常用列</button></div><div className="r-columns-editor">{allColumns.filter(key=>`${label(key)} ${key}`.toLowerCase().includes(columnSearch.toLowerCase())).map((key,i)=><div key={key}><label className="r-column-name"><input aria-label={`显示${label(key)}`} type="checkbox" disabled={key==="symbol"} checked={selectedColumns.includes(key)} onChange={()=>{const next=selectedColumns.includes(key)?selectedColumns.filter(k=>k!==key):[...selectedColumns,key];setVisible(next);persist(order,widths,pinned,next);}}/><span>{label(key)}</span></label><label><input aria-label={`固定${label(key)}`} type="checkbox" disabled={key==="symbol"} checked={pinned.includes(key)} onChange={()=>{const next=pinned.includes(key)?pinned.filter(k=>k!==key):[...pinned,key];setPinned(next);persist(order,widths,next);}}/>固定</label><input aria-label={`${label(key)}列宽`} type="number" min={65} max={480} value={width(key)} onChange={e=>setWidths({...widths,[key]:Math.max(65,Math.min(480,Number(e.target.value)))})} onBlur={()=>persist()}/><button disabled={i===0} aria-label={`${label(key)}前移`} onClick={()=>{const next=[...allColumns];[next[i-1],next[i]]=[next[i],next[i-1]];setOrder(next);persist(next);}}>前移</button></div>)}</div></section>}
 <div className="r-table-scroll r-market-grid" tabIndex={0} role="grid" aria-label="市场证券表" onKeyDown={e=>{if(e.key==="ArrowDown"||e.key==="ArrowUp"){e.preventDefault();if(e.key==="ArrowDown"&&selected===table.rows.length-1&&table.offset+table.rows.length<table.total)onQuery({...query,offset:table.offset+table.rows.length});else if(e.key==="ArrowUp"&&selected===0&&table.offset>0)onQuery({...query,offset:Math.max(0,table.offset-(query.limit??100))});else onSelected(Math.max(0,Math.min(table.rows.length-1,selected+(e.key==="ArrowDown"?1:-1))));}if(e.key==="Enter"&&table.rows[selected])onOpen(table.rows[selected]);}}><table><thead><tr>{columns.map((key,i)=><th key={key} style={{minWidth:width(key),width:width(key),...pinStyle(key,i),...(pinned.includes(key)?{zIndex:3}:{})}}><button onClick={()=>onQuery({...query,sortBy:key,descending:query.sortBy===key?!query.descending:false,offset:0})}>{label(key)}{query.sortBy===key?(query.descending?" ↓":" ↑"):""}</button></th>)}</tr></thead><tbody>{table.rows.map((row,i)=><tr key={String(row.symbol??i)} aria-selected={selected===i} className={selected===i?"selected":""} onClick={()=>onSelected(i)} onDoubleClick={()=>onOpen(row)}>{columns.map((key,n)=><td key={key} title={valueText(row[key],key)} className={tableNumber(row[key],key)!==null?`r-number ${/change|return|pct/i.test(key)?Number(row[key])>0?"r-up":Number(row[key])<0?"r-down":"":""}`:""} style={{width:width(key),...pinStyle(key,n),...(pinned.includes(key)?{zIndex:1}:{})}}>{marketValue(row[key],key)}</td>)}</tr>)}</tbody></table>{!table.rows.length&&<Empty title="没有匹配的证券">调整条件，或在数据中心补充数据。</Empty>}</div></>;
}
type StockTableKey = "financials" | "factors" | "flow" | "chips" | "events" | "seats";
interface StockTablePage extends ResearchTable { total: number; offset: number; limit: number; asOfDate?: string; }
const stockTableLabels: Record<StockTableKey,string> = { financials:"财务", factors:"因子", flow:"资金流", chips:"筹码", events:"龙虎榜", seats:"机构 / 营业部" };
export function StockPanel({panel}:{panel:WorkspacePanel}) {
 const s=useResearch(); const w=useWorkspace();
 const [symbol,setSymbol]=useState(panel.symbol??""); const [input,setInput]=useState(symbol); const [pinned,setPinned]=useState(panel.linkGroup !== "linked" && !!panel.symbol);
 const [data,setData]=useState<StockPanorama|null>(null); const [tab,setTab]=useState("chart"); const [notes,setNotes]=useState(""); const [date,setDate]=useState("");
 const [loading,setLoading]=useState(false); const [failure,setFailure]=useState(""); const [retry,setRetry]=useState(0);
 useEffect(()=>{w.updatePanel(panel.id,{symbol:symbol||undefined,linkGroup:pinned?undefined:"linked",...(symbol?{title:`${symbol} · ${pinned?"个股":"联动"}`}:{})});},[symbol,pinned]);
 useEffect(()=>{const handler=(event:Event)=>{if(!pinned){const next=(event as CustomEvent<string>).detail;setSymbol(next);setInput(next);}};window.addEventListener("v3-stock-link",handler);return()=>window.removeEventListener("v3-stock-link",handler);},[pinned]);
 useEffect(()=>{let alive=true;setData(null);setFailure("");setNotes("");if(!symbol){setLoading(false);return;}setLoading(true);
   void request<StockPanorama>("market.stock",{symbol,projectId:panel.projectId,date:date||undefined}).then(result=>{if(alive){setData(result);setNotes(result.notes);}}).catch(error=>{if(alive)setFailure(errorText(error));}).finally(()=>{if(alive)setLoading(false);});
   return()=>{alive=false;};
 },[symbol,date,panel.projectId,s.revision,retry]);
 const description=loading?"正在读取个股资料…":failure?"个股资料读取失败":`查看截至：${date||"最新数据"} · 实际数据日期：${data?.asOfDate||"暂无覆盖"}`;
 return <div className="r-page"><div className="r-toolbar"><form className="r-toolbar" onSubmit={e=>{e.preventDefault();setSymbol(input.trim());}}><input aria-label="个股代码" placeholder="输入证券代码" value={input} onChange={e=>setInput(e.target.value)}/><button>查看</button></form><button aria-pressed={pinned} onClick={()=>setPinned(v=>!v)}>{pinned?"已固定股票":"跟随列表联动"}</button><label className="r-inline-field">查看截至 <input aria-label="个股资料截止日期" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button disabled={!date} onClick={()=>setDate("")}>最新数据</button></div>
 {!symbol?<Empty title="选择一只股票">在市场列表用鼠标或方向键选择，或输入证券代码。</Empty>:<><Heading title={`${data?.name??""} ${symbol}`} description={description}/>{failure&&<div className="r-local-error" role="alert"><p>{failure}</p><button onClick={()=>setRetry(v=>v+1)}>重试读取资料</button></div>}<nav className="r-subtabs">{[["chart","日线"],...Object.entries(stockTableLabels),["notes","笔记"]].map(([key,label])=><button key={key} className={tab===key?"active":""} onClick={()=>setTab(key)}>{label}</button>)}</nav>
 {tab==="chart"?<PriceChart embedded symbol={symbol} asOfDate={date||undefined}/>:tab==="notes"?<><textarea aria-label="个股研究笔记" rows={12} value={notes} disabled={!data} onChange={e=>setNotes(e.target.value)}/><button disabled={!data} onClick={()=>void s.act(async()=>{await request("market.notes.save",{symbol,notes});s.setNotice("个股笔记已保存");})}>保存笔记</button></>:loading?<p role="status">正在读取{stockTableLabels[tab as StockTableKey]}…</p>:data?<StockTablePanel key={`${symbol}:${date}:${tab}`} symbol={symbol} projectId={panel.projectId} date={date||undefined} table={tab as StockTableKey} preview={data[tab as StockTableKey]}/>:!failure&&<Empty title="没有可用的个股资料"/>}
 {data&&<Coverage items={data.coverage}/>}</>}</div>;
}
function StockTablePanel({symbol,projectId,date,table,preview}:{symbol:string;projectId?:string;date?:string;table:StockTableKey;preview:ResearchTable}) {
 const s=useResearch(); const limit=200;
 const [offset,setOffset]=useState(()=>{const total=Number((preview as Partial<StockTablePage>).total??preview.rows.length);return Math.max(0,Math.floor((total-1)/limit)*limit);});
 const [page,setPage]=useState<StockTablePage|null>(null);const [loading,setLoading]=useState(false);const [failure,setFailure]=useState("");const [retry,setRetry]=useState(0);
 useEffect(()=>{let alive=true;setLoading(true);setFailure("");setPage(null);
   void request<StockTablePage>("market.stock.table",{symbol,projectId,date,table,offset,limit}).then(result=>{if(alive){if(offset>0&&offset>=result.total){setOffset(Math.max(0,Math.floor((result.total-1)/limit)*limit));return;}setPage(result);}}).catch(error=>{if(alive)setFailure(errorText(error));}).finally(()=>{if(alive)setLoading(false);});
   return()=>{alive=false;};
 },[symbol,projectId,date,table,offset,s.revision,retry]);
 return <section aria-label={`${stockTableLabels[table]}完整记录`}>{loading&&<p role="status">正在读取{stockTableLabels[table]}记录…</p>}{failure&&<div className="r-local-error" role="alert"><p>{failure}</p><button onClick={()=>setRetry(v=>v+1)}>重试读取表格</button></div>}{page&&<><DataTable table={{...page,name:stockTableLabels[table]}}/><div className="r-toolbar"><button disabled={loading||offset===0} onClick={()=>setOffset(0)}>最早记录</button><button disabled={loading||offset===0} onClick={()=>setOffset(Math.max(0,offset-limit))}>上一页</button><span>{page.total?`${page.offset+1}–${page.offset+page.rows.length} / ${page.total} 行`:"0 行"} · 日期升序</span><button disabled={loading||offset+page.rows.length>=page.total} onClick={()=>setOffset(offset+limit)}>下一页</button><button disabled={loading||offset+page.rows.length>=page.total} onClick={()=>setOffset(Math.max(0,Math.floor((page.total-1)/limit)*limit))}>最新记录</button></div><p className="r-note">搜索与表头排序作用于当前页。完整导出包含截至{date||"最新数据日期"}的全部记录。</p><StockExports table={page} tableKey={table} symbol={symbol} projectId={projectId} date={date}/></>}</section>;
}
export function GlobalSelection(){const s=useResearch();const w=useWorkspace();const saveRef=useRef<(()=>Promise<void>)|null>(null);const [allocations,setAllocations]=useState<Record<string,number>>({});const [update,setUpdate]=useState(true);const [portfolio,setPortfolio]=useState<JsonObject>({...portfolioDefaults});const [busy,setBusy]=useState(false);const [chosen,setChosen]=useState<string[]>([]);
 useEffect(()=>{const enabled=w.strategies.filter(st=>st.enabled&&st.active);setChosen(enabled.map(st=>st.id));setAllocations(Object.fromEntries(enabled.map(st=>[st.id,st.allocation])));},[w.strategies.map(st=>`${st.id}:${st.enabled}:${st.allocation}`).join("|")]);
 const total=chosen.reduce((n,id)=>n+(allocations[id]??0),0);return <div className="r-page"><Heading title="每日多策略选股" description="以各策略已启用快照计算，合并同一证券后对全局实际持仓生成净调仓清单。"/><div className="r-table-scroll"><table><thead><tr><th>参与</th><th>策略</th><th>启用日期</th><th>资金占比 %</th></tr></thead><tbody>{w.strategies.map(st=><tr key={st.id}><td><input aria-label={`选择${st.name}`} type="checkbox" disabled={!st.enabled||!st.active} checked={chosen.includes(st.id)} onChange={()=>setChosen(ids=>ids.includes(st.id)?ids.filter(id=>id!==st.id):[...ids,st.id])}/></td><td><button onClick={()=>w.open({kind:"strategy",title:st.name,projectId:st.projectId,strategyId:st.id})}>{st.name}</button></td><td>{st.active?.updatedAt?.slice(0,10)??"尚未启用"}</td><td><input aria-label={`${st.name}资金占比`} type="number" min={0} max={100} value={Math.round((allocations[st.id]??st.allocation)*10000)/100} onChange={e=>setAllocations({...allocations,[st.id]:Number(e.target.value)/100})}/></td></tr>)}</tbody></table></div><p className="r-note">分配资金 {(total*100).toFixed(2)}% · 未分配 {(Math.max(0,1-total)*100).toFixed(2)}% 留作现金</p><button disabled={busy||!chosen.length||total>1.000001||total<=0} onClick={()=>{setBusy(true);void s.act(async()=>{for(const st of w.strategies.filter(st=>chosen.includes(st.id)))await request("strategies.activate",{projectId:st.projectId,strategyId:st.id,allocation:allocations[st.id]??st.allocation});await w.reload();s.setNotice("资金占比已保存，继续使用原启用参数");}).finally(()=>setBusy(false));}}>保存资金占比</button><PositionsEditor saveRef={saveRef}/><details><summary>合并组合约束</summary><PortfolioEditor value={portfolio} onChange={setPortfolio}/></details><label className="r-check"><input type="checkbox" checked={update} onChange={e=>setUpdate(e.target.checked)}/>生成前更新数据</label><div className="r-toolbar"><button className="r-primary" disabled={busy||!chosen.length||total>1.000001||total<=0} onClick={()=>{setBusy(true);void s.act(async()=>{await saveRef.current?.();await request("jobs.submit",{spec:{kind:"selection.run",name:"多策略每日选股",parameters:{strategies:w.strategies.filter(st=>chosen.includes(st.id)).map(st=>({projectId:st.projectId,strategyId:st.id,allocation:allocations[st.id]??st.allocation})),portfolio,updateData:update}}});s.setNotice("每日选股已进入任务队列；实际持仓保持不变");}).finally(()=>setBusy(false));}}>生成合并调仓清单</button></div><SelectionResults/><h2>选股实验</h2><div className="r-experiment-list">{s.experiments.filter(e=>e.kind==="selection.run").map(e=><button key={e.id} onClick={()=>w.open({kind:"experiment",title:e.name,projectId:e.projectId,experimentId:e.id})}><strong>{e.name}</strong><span title={e.summary}>{experimentDescription(e)}</span><time>{e.createdAt.slice(0,10)}</time></button>)}</div></div>;
}
function SelectionResults(){
 const s=useResearch();const w=useWorkspace();const [selected,setSelected]=useState("");const [view,setView]=useState("candidates");const [detail,setDetail]=useState<ExperimentDetails|null>(null);const [failure,setFailure]=useState("");const [retry,setRetry]=useState(0);
 const experiments=s.experiments.filter(e=>e.kind==="selection.run"&&Array.isArray(e.parameters.strategies));const experiment=experiments.find(e=>`${e.projectId??""}:${e.id}`===selected)??experiments[0];
 useEffect(()=>{let alive=true;setDetail(null);setFailure("");if(experiment)void request<ExperimentDetails>("experiments.get",{projectId:experiment.projectId,experimentId:experiment.id}).then(d=>{if(alive)setDetail(d);}).catch(e=>{if(alive)setFailure(errorText(e));});return()=>{alive=false;};},[experiment?.id,experiment?.projectId,s.revision,retry]);
 return <section><h2>合并选股结果</h2>{!experiment?<Empty title="尚无合并结果">生成清单后，候选、目标组合、净调仓和策略贡献会显示在这里。</Empty>:<><div className="r-toolbar"><select aria-label="查看合并选股实验" value={`${experiment.projectId??""}:${experiment.id}`} onChange={e=>setSelected(e.target.value)}>{experiments.map(e=><option key={`${e.projectId??""}:${e.id}`} value={`${e.projectId??""}:${e.id}`}>{e.name} · {new Date(e.createdAt).toLocaleString("zh-CN")}</option>)}</select><button onClick={()=>w.open({kind:"experiment",title:experiment.name,projectId:experiment.projectId,experimentId:experiment.id})}>完整结果 / 导出</button></div><nav className="r-subtabs">{[["candidates","候选"],["target_weights","目标组合"],["rebalance","净调仓"],["strategy_contributions","策略贡献"]].map(([key,label])=><button key={key} className={view===key?"active":""} onClick={()=>setView(key)}>{label}</button>)}</nav>{failure?<p role="alert">{failure} <button onClick={()=>setRetry(v=>v+1)}>重试</button></p>:!detail?<p role="status">正在读取合并结果…</p>:<>{detail.details.executable===false&&<p role="alert">当前组合不可执行：{valueText(detail.details.conflicts)}</p>}{detail.tables.some(t=>t.name===view)?<PagedExperimentTable key={`${experiment.id}:${view}`} projectId={experiment.projectId} experimentId={experiment.id} table={view}/>:<Empty title="该实验没有此项记录"/>}</>}</>}</section>;
}
export function DataCenter(){const s=useResearch();const [coverage,setCoverage]=useState<DataCoverage[]>([]);const [start,setStart]=useState("2015-01-01");const [end,setEnd]=useState(new Date().toLocaleDateString("en-CA"));const [symbols,setSymbols]=useState("");const [source,setSource]=useState("baostock");const [financials,setFinancials]=useState(true);const [alternative,setAlternative]=useState<string[]>([]);const [dataset,setDataset]=useState("auto");
 useEffect(()=>{void s.act(async()=>setCoverage(await request("data.catalog")));},[s.revision]);return <div className="r-page"><Heading title="共享数据中心" description="共享本地数据供多个项目使用。任务区支持取消与重跑，覆盖范围以实际缓存为准。"/><div className="r-form-grid"><Field label="开始日期"><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></Field><Field label="结束日期"><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></Field><Field label="数据源"><select value={source} onChange={e=>setSource(e.target.value)}><option value="baostock">BaoStock</option><option value="akshare">AKShare</option></select></Field><Field label="证券代码（逗号分隔）"><input value={symbols} onChange={e=>setSymbols(e.target.value)}/></Field></div><div className="r-toolbar"><label><input type="checkbox" checked={financials} onChange={e=>setFinancials(e.target.checked)}/>公告财务</label>{[["flow","资金流"],["chips","筹码（估算）"],["lhb","龙虎榜"]].map(([key,label])=><label key={key}><input type="checkbox" checked={alternative.includes(key)} onChange={()=>setAlternative(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key])}/>{label}</label>)}<button className="r-primary" disabled={!start||!end||start>end} onClick={()=>void s.act(async()=>{await request("jobs.submit",{spec:{kind:"data.update",parameters:{startDate:start,endDate:end,source,financials,alternativeData:alternative,...(symbols.trim()?{symbols:symbols.split(/[,，\s]+/).filter(Boolean)}:{})}}});s.setNotice("数据更新已提交，可在底部任务查看进度");})}>增量更新</button></div><div className="r-toolbar"><select aria-label="导入数据集" value={dataset} onChange={e=>setDataset(e.target.value)}>{[["auto","自动识别"],["prices","日线"],["financials","财务"],["flow","资金流"],["chips","筹码"],["lhb","龙虎榜"]].map(([key,title])=><option value={key} key={key}>{title}</option>)}</select><button onClick={()=>void s.act(async()=>{const files=await window.v3Research!.chooseFiles();if(files.length)await request("jobs.submit",{spec:{kind:"data.import",parameters:{files,dataset}}});})}>导入 CSV / Parquet</button></div><Coverage items={coverage}/></div>;
}
export function ComparePanel({refs,panelId}:{refs:ResearchObjectRef[];panelId:string}){const s=useResearch();const w=useWorkspace();const [selected,setSelected]=useState<string[]>(refs.map(r=>`${r.projectId??""}:${r.experimentId}`));const [details,setDetails]=useState<ExperimentDetails[]>([]);const [metric,setMetric]=useState("net");
 async function loadComparison(){ const result=await request<ExperimentDetails[]>("experiments.compare",{experiments:candidates.filter(e=>selected.includes(`${e.projectId??""}:${e.id}`)).map(e=>({projectId:e.projectId,experimentId:e.id}))}); await Promise.all(result.map(async d=>{for(const name of ["benchmark","drawdown"]){if(!d.tables.some(t=>t.name===name))continue;const rows:JsonObject[]=[];let offset=0;while(true){const page=await request<ResearchTable&{total:number}>("experiments.table",{projectId:d.experiment.projectId,experimentId:d.experiment.id,table:name,offset,limit:500});rows.push(...page.rows);offset+=page.rows.length;if(offset>=page.total||!page.rows.length){d.tables=d.tables.map(t=>t.name===name?{...t,rows}:t);break;}}}}));setDetails(result);}

 useEffect(()=>{w.updatePanel(panelId,{experimentRefs:s.experiments.filter(e=>selected.includes(`${e.projectId??""}:${e.id}`)).map(e=>({kind:"experiment",title:e.name,projectId:e.projectId,experimentId:e.id}))});},[selected.join("|"),s.experiments.length]);
 const candidates=s.experiments; const flatten=(value:unknown,prefix=""):Record<string,string>=>value&&typeof value==="object"&&!Array.isArray(value)?Object.assign({},...Object.entries(value).map(([k,v])=>flatten(v,prefix?`${prefix}.${k}`:k))):{[prefix]:valueText(value)};
 const params=details.map(d=>flatten(d.experiment.parameters));const keys=[...new Set(params.flatMap(p=>Object.keys(p)))].filter(k=>new Set(params.map(p=>p[k])).size>1);
 return <div className="r-page"><Heading title="实验比较" description="跨项目与策略比较输入差异、净值、基准、回撤、持仓和交易。"/><details open={!details.length}><summary>选择实验（{selected.length}）</summary><div className="r-compare-choices">{candidates.map(e=>{const id=`${e.projectId??""}:${e.id}`;return <label key={id}><input type="checkbox" checked={selected.includes(id)} onChange={()=>setSelected(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/>{e.name} · {e.createdAt.slice(0,10)}</label>;})}</div></details><button disabled={selected.length<2} onClick={()=>void s.act(async()=>{await loadComparison();})}>比较所选实验</button>{details.length>0&&<><DataTable table={{name:"参数差异",columns:["参数",...details.map((d,i)=>`${i+1} ${d.experiment.name}`)],rows:keys.map(k=>Object.fromEntries([["参数",k],...details.map((d,i)=>[`${i+1} ${d.experiment.name}`,params[i][k]??"—"])])) as JsonObject[]}}/><DataTable table={{name:"核心指标",columns:["实验",...new Set(details.flatMap(d=>Object.keys(d.experiment.metrics)))],rows:details.map(d=>({实验:d.experiment.name,...d.experiment.metrics}))}}/><nav className="r-subtabs">{[["net","净值与基准"],["drawdown","回撤"],["holdings","持仓"],["trades","交易"]].map(([id,title])=><button key={id} className={metric===id?"active":""} onClick={()=>setMetric(id)}>{title}</button>)}</nav>{metric==="net"||metric==="drawdown"?<Plot title={metric==="net"?"各实验净值 / 基准":"各实验回撤"} option={{tooltip:{trigger:"axis"},legend:{type:"scroll"},xAxis:{type:"time"},yAxis:{type:"value",scale:true},series:details.flatMap(d=>{const table=d.tables.find(t=>t.name===(metric==="net"?"benchmark":"drawdown"));return table?table.columns.filter(c=>c!=="date"&&table.rows.some(r=>typeof r[c]==="number")).map(c=>({name:`${d.experiment.name} · ${c==="portfolio"?"策略":"基准"}`,type:"line" as const,showSymbol:false,data:table.rows.map(r=>[String(r.date),typeof r[c]==="number"?r[c]:null])})):metric==="net"?d.series.map(series=>({name:`${d.experiment.name} · ${series.name}`,type:"line" as const,showSymbol:false,data:series.points.map(p=>[p.date,p.value])})):[];})}}/>:details.map(d=><section key={d.experiment.id}><h2>{d.experiment.name}</h2>{d.tables.filter(t=>metric==="holdings"?/holding|持仓/i.test(t.name):/trade|交易/i.test(t.name)).map(t=><PagedExperimentTable key={t.name} projectId={d.experiment.projectId} experimentId={d.experiment.id} table={t.name}/>)}</section>)}</>}</div>;
}

function StockExports({table,tableKey,symbol,projectId,date}:{table:StockTablePage;tableKey:StockTableKey;symbol:string;projectId?:string;date?:string}) {
 const s=useResearch();const [busy,setBusy]=useState(false);
 async function exportData(format:"csv"|"xlsx"|"pdf") { setBusy(true);await s.act(async()=>{const name=`${symbol}-${stockTableLabels[tableKey]}${date?`-${date}`:""}`;
   if(format!=="pdf") { const result=await request<{path:string}>("market.stock.export",{symbol,projectId,date,table:tableKey,format});const path=await window.v3Research!.exportFile({format,sourcePath:result.path,suggestedName:`${name}.${format}`});if(path)s.setNotice(`已完整导出：${path}`); }
   else { const html=tableReportHtml({title:name,table,description:`当前页 ${table.offset+1}–${table.offset+table.rows.length} / ${table.total} 行。查看截至：${date||table.asOfDate||"最新数据"}。本页全部列按列组分开排版，完整历史记录请导出 CSV / Excel。`});const path=await window.v3Research!.exportFile({format,html,suggestedName:`${name}-当前页.pdf`});if(path)s.setNotice(`当前页已导出：${path}`); }
 });setBusy(false);}
 return <div className="r-toolbar"><span>完整记录：{table.total} 行</span><button disabled={busy} onClick={()=>void exportData("csv")}>完整导出 CSV</button><button disabled={busy} onClick={()=>void exportData("xlsx")}>完整导出 Excel</button><button disabled={busy||!table.rows.length} onClick={()=>void exportData("pdf")}>当前页 PDF</button>{busy&&<span role="status">正在导出…</span>}</div>;
}
